### ISSUE TITLE
[HW] <TIKTOKCLONE>

### ISSUE THREAD

**Issue by ankulverma** [datastaxdevs/workshop-social-media-tiktok#10]
**Name:** <Priyansh Verma>
**Email:** <uniankul@gmail.com>
**Linkedin Profile:** <www.linkedin.com/in/priyansh-verma-6a4653167>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/41675715/119710323-d6dd1500-be7b-11eb-95b4-e322a2b8cb95.png)
![image](https://user-images.githubusercontent.com/41675715/119710349-e0ff1380-be7b-11eb-92ee-b7b69bfbc688.png)
![image](https://user-images.githubusercontent.com/41675715/119710402-f07e5c80-be7b-11eb-837c-6de1cdd50b55.png)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Great job, Ankul!

**Comment by SonicDMG** [comment]
Thank you so much Ankul, here you go. https://api.badgr.io/public/assertions/EvpablaARp2LxyHcWWigRA?identity__email=uniankul%40gmail.com
