### ISSUE TITLE
[HW] Aditya Yaduvanshi

### ISSUE THREAD

**Issue by adityayaduvanshi** [datastaxdevs/workshop-social-media-tiktok#100]
**Name:** Aditya Yaduvanshi
**Email:**  aditya97y@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/theaditya-yaduvanshi-/

Attach the homework step I screenshots below:
-----------------------------------------
![tiktok1](https://user-images.githubusercontent.com/38696088/125670034-40966374-5423-43af-9d78-1ac32664df9d.PNG)
![tiktok2](https://user-images.githubusercontent.com/38696088/125670145-225802ae-d735-4516-b236-564539f781f7.PNG)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![tiktok3](https://user-images.githubusercontent.com/38696088/125670214-0eed32a3-01c7-4c5f-8541-47e9b9902acc.PNG)
![tiktok4](https://user-images.githubusercontent.com/38696088/125670272-3aa44d4d-439c-4def-b3c7-a391afe97a2d.PNG)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Aditya! Looks good!

**Comment by HadesArchitect** [comment]
Hey **Aditya Yaduvanshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/hYYab1YSTUq3A1rBKOcEow
