### ISSUE TITLE
[HW] <Akhil Madutha>

### ISSUE THREAD

**Issue by Akhil-UI** [datastaxdevs/workshop-social-media-tiktok#101]
**Name:** Akhil Madutha
**Email:** aakhi53@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/akhil-madutha/>

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/25749552/125670422-30213a00-5be3-48b7-baf5-392dcc27c7b4.png)
![image](https://user-images.githubusercontent.com/25749552/125670371-7b141a69-a654-48c4-a422-aca3f927e0eb.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/25749552/125670261-f82de9e7-b302-4a48-8084-814550afb49e.png)

**Comment by SonicDMG** [comment]
Hi there. Even though the image above was only from your gitpod env I was able to load up your site from your deployed app https://objective-mayer-eab8f6.netlify.app. Looks good.

**Comment by HadesArchitect** [comment]
Hey **Akhil Madutha**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OOWjnIReQRGi3az4MeeHOw
