### ISSUE TITLE
[HW] Prashanth K V

### ISSUE THREAD

**Issue by PrashKV** [datastaxdevs/workshop-social-media-tiktok#102]
**Name:** Prashanth K V
**Email:** prashanthhegde195@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (223)](https://user-images.githubusercontent.com/64456676/125671233-b296aef2-82e5-42ac-8a95-0a250954b6a1.png)

![Screenshot (234)](https://user-images.githubusercontent.com/64456676/125670645-07597035-8b52-431b-a68b-213f03fdb8b5.png)
![Screenshot (233)](https://user-images.githubusercontent.com/64456676/125671055-1d224566-8da3-4936-a751-cf47099197ce.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
-- image removed by team --

![Screenshot (225)_LI](https://user-images.githubusercontent.com/64456676/125670772-1a087ace-cd9f-46f6-aea2-cc84ff38f80f.jpg)
![Screenshot (226)](https://user-images.githubusercontent.com/64456676/125670783-291b2cca-e33e-472e-9efa-31745e818500.png)
-- image removed by team --
![Screenshot (228)_LI](https://user-images.githubusercontent.com/64456676/125670790-f73301cd-24dd-4ad0-aeaf-b963cc9a9b70.jpg)

**Comment by SonicDMG** [comment]
Hi there. Could you please provide your email address so we can issue your badge?

Also, I removed a set of images that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.

**Comment by PrashKV** [comment]
Sorry for the inconvenience, I've added my email ID

**Comment by HadesArchitect** [comment]
Hey **Prashanth K V**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Gr7j6j47SGGJGHFR8qocQg

**Comment by SonicDMG** [comment]
No worries at all. There you go. :)
