### ISSUE TITLE
[HW] Tiktok Clone Gervie Barczyk

### ISSUE THREAD

**Issue by gervieb** [datastaxdevs/workshop-social-media-tiktok#103]
**Name:** Gervie Barczyk
**Email:** gerviebarczyk@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gerviebar/

Attach the homework step I screenshots below:
-----------------------------------------
![github-repo](https://user-images.githubusercontent.com/72528204/125670300-440a76fa-bda0-4836-8c33-53e3dbd64445.png)

![generated-token](https://user-images.githubusercontent.com/72528204/125670712-d8e4f1e8-54af-45ed-82f1-b3403dbc8a6a.png)

![gitpod](https://user-images.githubusercontent.com/72528204/125670133-0dc4f7d7-5ed9-4666-b0fb-fc014d07ebe3.png)

![tiktok](https://user-images.githubusercontent.com/72528204/125670215-d9e658e2-faf7-4329-bcb0-18b7b7588ffd.png)

Attach the homework step II screenshots below:
-----------------------------------------
![netlify](https://user-images.githubusercontent.com/72528204/125671029-c78ee063-3e2f-4a37-a4b3-8274edf7099c.png)

![swagger](https://user-images.githubusercontent.com/72528204/125671040-25e9190a-9813-423f-a7aa-af6dead6dfc0.png)

![responses](https://user-images.githubusercontent.com/72528204/125671051-8cebef38-dafe-4d7b-804d-dfa46a880e22.png)

**Comment by RyanWelford** [comment]
Awesome, Gervie! Well done!

**Comment by HadesArchitect** [comment]
Hey **Gervie Barczyk**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/04USI7RvRMOVDqXxmA38lg
