### ISSUE TITLE
[HW]  Ashwani Ranjan

### ISSUE THREAD

**Issue by ranjanOO7** [datastaxdevs/workshop-social-media-tiktok#104]
**Name:** Ashwani Ranjan
**Email:** ranjan.ashwani.ar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ashwani-ranjan-972046216

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (110)](https://user-images.githubusercontent.com/86527021/125672604-d44e2b4d-3947-48f2-a9e3-80bde2b1a3ae.png)

![Screenshot (112)](https://user-images.githubusercontent.com/86527021/125672550-5aa2ea2c-f6d1-45f1-91dc-426eac5ecff9.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot (107)](https://user-images.githubusercontent.com/86527021/125672645-924d0028-e4c4-4ac2-9314-173e7466efc5.png)

**Comment by RyanWelford** [comment]
Looks great, Ashwani! Thanks for your submission. We'll get a badge out to you shortly.

**Comment by HadesArchitect** [comment]
Hey **Ashwani Ranjan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-_kBGrXvTNSsQ7rXjtiqCw
