### ISSUE TITLE
[HW] Zain Ali Baig

### ISSUE THREAD

**Issue by zab0707** [datastaxdevs/workshop-social-media-tiktok#105]
**Name:** Zain Ali Baig
**Email:** zainbaig8@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/zain-ali-baig-8a6557195

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

1. Login or Register to Astra DB and create database
![image](https://user-images.githubusercontent.com/54724336/125675168-d154cbcb-6435-4ee2-b312-2548d9019187.png)

2. Deploy to Netlify
![image](https://user-images.githubusercontent.com/54724336/125675366-3345e0d0-1ace-4723-9c4c-60ebb1bfa36b.png)

3. Access YOUR GitHub repository
![image](https://user-images.githubusercontent.com/54724336/125675483-1bb0ef98-847c-4a16-a459-82d9fc8dae99.png)

4. Launch GitPod IDE
![image](https://user-images.githubusercontent.com/54724336/125675862-f638c287-b5b1-4ac5-b088-d81197c7db44.png)

5. Install the Netlify CLI (Command Line Interface)
![image](https://user-images.githubusercontent.com/54724336/125675963-a5e89983-3fe0-4e89-85d0-64e63e286392.png)

6. Generate application token to securely connect to the database
![1](https://user-images.githubusercontent.com/54724336/125676283-bca08a7b-fe88-4681-94ce-512681b8a541.jpg)

7. Configure and connect database
![2](https://user-images.githubusercontent.com/54724336/125676548-f0441a20-e578-4e02-9e35-fadf1f0b0e2b.jpg)

8. Launch your app
![image](https://user-images.githubusercontent.com/54724336/125676658-18fa0832-2545-4620-be84-a686a5e53371.png)

9. Connect Netlify to your site
![image](https://user-images.githubusercontent.com/54724336/125676779-bd7a795a-36ff-485e-bd09-2b06c78ad1af.png)

10. Deploy to production
![image](https://user-images.githubusercontent.com/54724336/125676902-2114e519-339b-42d7-aeb7-fd966f77b28f.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks great, Zain! Congrats!

**Comment by HadesArchitect** [comment]
Hey **Zain Ali Baig**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UrB5qWcYSG-Xe9mGdMvzmQ
