### ISSUE TITLE
[HW] Adeline

### ISSUE THREAD

**Issue by TanukiA** [datastaxdevs/workshop-social-media-tiktok#106]
**Name:** Adeline Fong Li Ling
**Email:** bukubukuu47@gmail.com
**Linkedin Profile:** Don't own

Attach the homework step I screenshots below:
-----------------------------------------

### 1. Create Astra DB
<img width="667" alt="0 1" src="https://user-images.githubusercontent.com/76217469/125685041-c9563772-f3fb-4f04-971c-39291955d1fa.png">

### 2. Deploy to Netlify
<img width="881" alt="0 2" src="https://user-images.githubusercontent.com/76217469/125685105-5e3f67ea-c6a1-4030-a779-f665970cae4b.png">
<img width="896" alt="0 3" src="https://user-images.githubusercontent.com/76217469/125685144-86a0b89d-18cb-464e-b042-8c5a50a86350.png">

### 3. Launch app
<img width="502" alt="0 7" src="https://user-images.githubusercontent.com/76217469/125685379-f6f06abc-1360-42c9-945c-d6ee896bcbec.png">

### 4. Connect Netlify to the site
<img width="573" alt="0 8" src="https://user-images.githubusercontent.com/76217469/125685398-c2e80fd3-43c7-405d-98e6-dc26a3dbb246.png">
<img width="676" alt="0 9" src="https://user-images.githubusercontent.com/76217469/125685437-d01ad765-7c0a-4bed-975a-2fafb0c2cbaf.png">

### 5. Deploy to production
<img width="591" alt="0 10" src="https://user-images.githubusercontent.com/76217469/125685531-84ad7617-75eb-4c37-baf1-3fe605b490aa.png">
<img width="933" alt="0 11" src="https://user-images.githubusercontent.com/76217469/125685572-44a9fc22-f71f-4204-ae03-e31d93ce05cc.png">

**Comment by RyanWelford** [comment]
Awesome job, Adeline! Thanks for joining us!

**Comment by HadesArchitect** [comment]
Hey **Adeline Fong Li Ling**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/THtfZy0_T0y7MP7nMXhoSQ
