### ISSUE TITLE
[HW] Andrea J

### ISSUE THREAD

**Issue by Turo-Rudi** [datastaxdevs/workshop-social-media-tiktok#107]
**Name:** Andrea Józsa
**Email:** agent8917@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/andrea-j%C3%B3zsa-0542a23b/

Attach the homework step I screenshots below:
-----------------------------------------
![Week2 HW1](https://user-images.githubusercontent.com/81749739/125687592-c7c70742-bed2-45d9-860c-0186284d745d.png)
![Week2 HW2](https://user-images.githubusercontent.com/81749739/125687626-760165e5-6202-4119-842a-aa13a6b53556.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Week2 HW5](https://user-images.githubusercontent.com/81749739/125689045-9bc462e0-bc8a-44c0-a6b2-9c43a3a31dae.png)

**Comment by RyanWelford** [comment]
Looks like you successfully deployed! Well done! I had to remove some images from your submission as they had your token in them. I would suggest clearing your token out in 'Token Management' as a precaution.

**Comment by HadesArchitect** [comment]
Hey **Andrea Józsa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WpwXwSkdStmH8yxjVUou-A
