### ISSUE TITLE
[HW] Parth Gulhane

### ISSUE THREAD

**Issue by ParthGulhane** [datastaxdevs/workshop-social-media-tiktok#108]
**Name:** Parth Gulhane 
**Email:** parthgulhane14@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------
<SCREENSHOTS>

![Screenshot (260)](https://user-images.githubusercontent.com/87273634/125689885-499d6906-ba9d-4766-8638-f5099cbf2389.png)

![Screenshot (261)](https://user-images.githubusercontent.com/87273634/125689899-d913f5a9-a6b2-49d6-b69a-37ab6111f5ae.png)

![Screenshot (262)](https://user-images.githubusercontent.com/87273634/125689910-850d91dc-e58a-4f2c-86de-10ecdc206c15.png)

![Screenshot (263)](https://user-images.githubusercontent.com/87273634/125689924-c7b2e5f1-349b-4d24-ab36-ebc95220691b.png)

Attach the homework step II screenshots below:
-----------------------------------------
<SCREENSHOTS>

![Screenshot (265)_LI](https://user-images.githubusercontent.com/87273634/125690567-8f885bcf-f3d9-471b-ba8d-cc61cf7aefe6.jpg)

![Screenshot (260)_LI](https://user-images.githubusercontent.com/87273634/125690288-51cbaff5-9f52-41b1-b001-dce584f7bbf4.jpg)

**Comment by RyanWelford** [comment]
Nicely done, Parth! Thanks!

**Comment by ParthGulhane** [comment]
I don't got my badge for my second week workshop.

**Comment by HadesArchitect** [comment]
Hey **Parth Gulhane**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/usF05ohFQFyz_NWrIUv3DA
