### ISSUE TITLE
[HW]Nikesh

### ISSUE THREAD

**Issue by Nikesht** [datastaxdevs/workshop-social-media-tiktok#11]
**Name:** Nikesh
**Email:** nikesh.tanwer@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nikesht2905/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/8111019/119710698-49e68b80-be7c-11eb-89d9-495549d73dd3.png)

**Comment by RyanWelford** [comment]
Looks like a successful deploy! Thanks Nikesh!

**Comment by SonicDMG** [comment]
Awesome Nikesh, here you go. https://api.badgr.io/public/assertions/8qabYbWaQAydQfw5bNQzYQ?identity__email=nikesh.tanwer%40gmail.com
