### ISSUE TITLE
[HW] Pamela Jung

### ISSUE THREAD

**Issue by pamify** [datastaxdevs/workshop-social-media-tiktok#110]
**Name:** Pamela Jung
**Email:** pamjung@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pamjung/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![TikTok Clone](https://user-images.githubusercontent.com/72463342/125697415-a87d9a1c-8b6d-4ef3-99c5-f6eef3e0b12d.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

List of collections

![List of collections](https://user-images.githubusercontent.com/72463342/125697349-4ec6ac94-84bb-4571-ab7a-0fcd1e9310bf.png)

Search documents in a collection

![Search documents in a collection](https://user-images.githubusercontent.com/72463342/125697226-fae57f50-6725-43c9-83a0-6bcc10eb3cb9.png)

**Comment by HadesArchitect** [comment]
Hey **Pamela Jung**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MAO5VmfnTNmGZhevOmbzRw
