### ISSUE TITLE
[HW] Dheirya Tyagi (Just A Fellow Doge)

### ISSUE THREAD

**Issue by Dheirya** [datastaxdevs/workshop-social-media-tiktok#111]
**Name:** Dheirya Tyagi
**Email:**  redman2customerservice@gmail.com
**Linkedin Profile:**  I don't have one. 😔
[![Netlify Status](https://api.netlify.com/api/v1/badges/bef3d5f7-5f5c-4ea5-b0c0-ab381cbbf68c/deploy-status)](https://app.netlify.com/sites/reactok/deploys)

Attach the homework step I screenshots below:
-----------------------------------------

![Screen Shot 2021-07-14 at 12 13 14 PM](https://user-images.githubusercontent.com/69175561/125705665-418e34dd-fc55-4f5a-a2d5-f6de77bc945c.png)
![Screen Shot 2021-07-14 at 12 11 20 PM](https://user-images.githubusercontent.com/69175561/125705691-b8fb9faa-aa03-4f4e-80ad-f5a55f5357a8.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screen Shot 2021-07-14 at 7 34 48 PM](https://user-images.githubusercontent.com/69175561/125706088-aac2ebf9-7160-46f9-8739-711a45231382.png)
![Screen Shot 2021-07-14 at 7 35 12 PM](https://user-images.githubusercontent.com/69175561/125706104-13be0b3b-c471-46a0-8b79-00dc559313fb.png)

Extra Credit:
-----------------------------------------
[![Netlify Status](https://api.netlify.com/api/v1/badges/bef3d5f7-5f5c-4ea5-b0c0-ab381cbbf68c/deploy-status)](https://app.netlify.com/sites/reactok/deploys)
I watched [the tutorial by Anna Kubow](https://youtu.be/IATOicvih5A). I updated some of the app css and customized it. The url for my website is at [https://reactok.netlify.app/#/](https://reactok.netlify.app/#/). Here are some screenshots from the website:
![Screen Shot 2021-07-14 at 7 31 36 PM](https://user-images.githubusercontent.com/69175561/125706304-57986b7b-9e75-42bc-8651-0c7cd0f8c902.png)
![Screen Shot 2021-07-14 at 7 41 22 PM](https://user-images.githubusercontent.com/69175561/125706366-2f65cc05-61b4-48cd-9149-8e232a6757b9.png)
![Screen Shot 2021-07-14 at 7 44 54 PM](https://user-images.githubusercontent.com/69175561/125706563-afb5731c-745a-4544-82f5-3b11a7f1e66a.png)

**Comment by HadesArchitect** [comment]
Hey **Dheirya Tyagi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/d_MUgsLlRuqpkU9doQCXiA
