### ISSUE TITLE
[HW] Jeremy Santos

### ISSUE THREAD

**Issue by jjmsantos** [datastaxdevs/workshop-social-media-tiktok#112]
**Name:** Jeremy Santos
**Email:** jeremy.santos1010@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jeremyjmsantos/

Attach the homework step I screenshots below:
-----------------------------------------

![astradb](https://user-images.githubusercontent.com/77421219/125709668-489d6567-ed1c-4d1b-b687-ab0f7ecae92a.jpg)
![astratoken](https://user-images.githubusercontent.com/77421219/125710035-8a19a1f2-7e5e-45b8-9b25-53079097009f.jpg)
![netlify-site](https://user-images.githubusercontent.com/77421219/125711786-3e5b2a0c-21b6-4882-bdc7-77a02c72fe5b.jpg)
![gitpod-sample](https://user-images.githubusercontent.com/77421219/125711704-38f0558d-bab5-494f-adc2-b777f25fa441.jpg)
![astra-getdocuments](https://user-images.githubusercontent.com/77421219/125712336-d9a4a1e2-0c5e-4775-b6c9-11943f115c03.jpg)
![astra-getcollections](https://user-images.githubusercontent.com/77421219/125712337-40d6cc8a-eec3-4661-af8f-b55a1467b1bb.jpg)
![deployedsite](https://user-images.githubusercontent.com/77421219/125712490-4fb2b1c0-122e-401f-85b0-4a3425939fec.jpg)

**Comment by HadesArchitect** [comment]
Hey **Jeremy Santos**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3ac4-q9qRYS0mwoITnbqVQ
