### ISSUE TITLE
[HW] <THEONA CIOCIRLAN>

### ISSUE THREAD

**Issue by TheonaCiocirlan** [datastaxdevs/workshop-social-media-tiktok#113]
**Name:** THEONA CIOCIRLAN
**Email:** theona.ciocirlan@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/theona-ciocirlan>

Attach the homework step I screenshots below:
-----------------------------------------

- ![Screenshot (155)](https://user-images.githubusercontent.com/83605038/125715627-50c30849-9d1a-4f5c-9c9e-818cc62f38d7.png)
- ![Screenshot (158)](https://user-images.githubusercontent.com/83605038/125715628-cd5d4407-5d4e-4e0f-a818-d4141fa7f65d.png)
- ![Screenshot (157)](https://user-images.githubusercontent.com/83605038/125715631-deaf1ba2-6266-47a6-b9b7-4dad531c852f.png)
- ![Screenshot (156)](https://user-images.githubusercontent.com/83605038/125715632-dbcae474-abde-4d47-a3da-07c71ca98cea.png)

**Comment by HadesArchitect** [comment]
Hey **THEONA CIOCIRLAN**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EzfCrDGUTeaeDzMW88VfSA
