### ISSUE TITLE
[HW] Sumit Sharma

### ISSUE THREAD

**Issue by sumitaccess007** [datastaxdevs/workshop-social-media-tiktok#114]
**Name:** Sumit Sharma
**Email:** sumitaccess007@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sumit-sharma-007/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125721056-70f24b68-5107-40ec-828b-6088680f11a1.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125721218-673b8afb-6891-4518-982f-6aebfd80b373.png)

Attach the homework step III screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125721353-97de9e2f-9c0f-4f54-8236-9eed152f9339.png)

Attach the homework step IV screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125721582-19e6b04c-e7db-4c2c-9e32-229458297c75.png)

Attach the homework step V screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125721750-c6f53350-bd57-47c3-9aa7-89f61034597a.png)

Attach the homework step VI screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125723197-e677f463-08bd-4fd7-94b0-c5dd8da8f30b.png)

Attach the homework step VII screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125723419-f761c39f-4454-4f8b-b687-914d8fdc76d4.png)

Attach the homework step VIII screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125723656-8ec35535-a6b4-4c41-9af1-537451f01163.png)

Attach the homework step IX screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125723984-5da9e730-3517-41d5-8e35-66be9d3caf53.png)

Attach the homework step X screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/14336951/125724089-31e892ad-4571-4922-afe6-6a93e3329eaf.png)

**Comment by SonicDMG** [comment]
Nice documentation. 

Also, I removed a an image that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.

**Comment by HadesArchitect** [comment]
Hey **Sumit Sharma**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MqNJn0oKScKPmKrd_iUNhQ
