### ISSUE TITLE
[HW] Zhoucai Ni

### ISSUE THREAD

**Issue by zhoucaiNi** [datastaxdevs/workshop-social-media-tiktok#115]
**Name:** Zhoucai Ni
**Email:** nizhoucai@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/zhoucai-ni-3257a8189/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/53072233/125724755-efaaad60-6de2-4369-86d4-edde72ded2bd.png)

![image](https://user-images.githubusercontent.com/53072233/125724919-0bdc4c27-f54a-4f25-ad3a-c23fdc46af4c.png)

![image](https://user-images.githubusercontent.com/53072233/125725490-f3d2933f-31de-4155-9b58-915d3d55e11b.png)

![image](https://user-images.githubusercontent.com/53072233/125725751-7c14a32e-3a35-4486-8a9f-832a1ef64799.png)

![image](https://user-images.githubusercontent.com/53072233/125725617-e1b58acf-1da8-42a2-9d4d-fbf113c523c4.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Zhoucai Ni**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/fNyEnu5sSrOMUsB330iSRw
