### ISSUE TITLE
[HW] Batchu Lakshmi Alekhya

### ISSUE THREAD

**Issue by lakshmialekhya406** [datastaxdevs/workshop-social-media-tiktok#116]
**Name:** Batchu Lakshmi Alekhya
**Email:** lakshmialekhya406@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/lakshmi-alekhya-12b620200

Attach the homework step I screenshots below:
-----------------------------------------
step 1:
![b](https://user-images.githubusercontent.com/73642162/125739142-0ffc7632-2150-47b5-bda2-cf7cc0a5a3ed.png)
step 2:
![c](https://user-images.githubusercontent.com/73642162/125739188-88a9bf94-cad5-4b93-b869-07db5bb59615.png)
step 3:
![a](https://user-images.githubusercontent.com/73642162/125739220-72ef90c2-b79f-4cbe-9f36-6096c972261f.png)
step 4:
![f](https://user-images.githubusercontent.com/73642162/125739311-45deaca9-35fc-444a-aa66-ca1db960a021.png)
step 5:
![d](https://user-images.githubusercontent.com/73642162/125739351-ba712389-fb8e-4bc8-8ad3-42ef7910f722.png)
step 7:
![e](https://user-images.githubusercontent.com/73642162/125739380-f4034e3f-f436-44dc-b53a-ca6ea98ceae1.png)
step 8:
![g](https://user-images.githubusercontent.com/73642162/125739410-b82c2836-d496-4e90-9fc2-0b32aacb2161.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --
![x](https://user-images.githubusercontent.com/73642162/125739498-66a47e89-f981-40ca-8b15-6689044f522a.png)

**Comment by HadesArchitect** [comment]
Hey **Batchu Lakshmi Alekhya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ACWDWvVaQEStuz-9CIzvvg

**Comment by SonicDMG** [comment]
Also, I removed a set of images that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.
