### ISSUE TITLE
[TIKTOKCLONE] <ABHISHEK MAURYA>

### ISSUE THREAD

**Issue by ABHISHEK1163** [datastaxdevs/workshop-social-media-tiktok#117]
**Name:** ABHISHEK MAURYA
**Email:** abhishek1163.cse19@chitkara.edu.in
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![s1](https://user-images.githubusercontent.com/87027732/125741962-9d1a1e8e-a260-496b-bd52-ee0612f0cc46.png)
![s2](https://user-images.githubusercontent.com/87027732/125742330-ac2ba9e2-77e1-4a11-94d7-42ab193acb11.png)
![s3](https://user-images.githubusercontent.com/87027732/125742607-b44981fe-47ba-40d2-ae2e-399f16822ce8.png)
![s4](https://user-images.githubusercontent.com/87027732/125742828-2cba7f0c-3b22-472e-84f6-4a6ac8a7ed0b.png)
![s5](https://user-images.githubusercontent.com/87027732/125743251-751b82ee-b44b-48e3-a20d-48cb9d5863b3.png)
![s6](https://user-images.githubusercontent.com/87027732/125743536-a91acb71-f213-4042-a9a8-6dd5c5a6f4f1.png)
![s7](https://user-images.githubusercontent.com/87027732/125743850-a64d4d07-2a41-4ceb-9ba5-cf0a597d4cd8.png)
NETLIFY LINK : https://quirky-goldwasser-f3664c.netlify.app/#/

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **ABHISHEK MAURYA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OofZnYQ2TPO_k8IMHMT-Lg
