### ISSUE TITLE
[HW] Sharath Koushik

### ISSUE THREAD

**Issue by sharathkoushik** [datastaxdevs/workshop-social-media-tiktok#118]
**Name:** Sharath Koushik
**Email:** sharath.koushik@gmail.com
**Linkedin Profile:** www.linkedin.com/in/sharathkoushik

![image](https://user-images.githubusercontent.com/77142757/125751635-b813e491-241d-4911-b8e5-1f820b929ad7.png)
![image](https://user-images.githubusercontent.com/77142757/125751650-a214bccb-6555-4351-8cd4-e938ae765ee2.png)
![image](https://user-images.githubusercontent.com/77142757/125751662-b7d403fe-b1c4-42c3-b486-790b86269a19.png)
![image](https://user-images.githubusercontent.com/77142757/125752135-c20fc14e-a0db-455e-af8c-78006174e400.png)
![image](https://user-images.githubusercontent.com/77142757/125752191-3db8188c-d599-4162-b364-c937be04a407.png)

**Comment by SonicDMG** [comment]
Hi there, the app looks good, but I don't it deployed and working up on your netlify site. Could you please provide a screen of the full deployment.

**Comment by sharathkoushik** [comment]
Hi David,

  Below is the screenshot I had captured during the lab.  Unfortunately I am not able to run the gitpod now to redo it since it is giving Deadline exceeded error. The app was functional as expected in the instructions. Not sure if this helps.

![Screen](https://user-images.githubusercontent.com/77142757/126046125-09932993-5b27-4254-9845-f3481c662163.png)

**Comment by SonicDMG** [comment]
Ok, sorry you are running into that trouble. Not sure what the "deadline exceeded" error is honestly. Not one we have run into or I've looked into. I see that you have the local app working just fine and you got to the point where you were building for netlify. I'll go ahead and give a pass because you clearly did the work. I also appreciate you following up.

**Comment by HadesArchitect** [comment]
Hey **Sharath Koushik**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/wypok8tQRFa48K7gvBd2bA
