### ISSUE TITLE
[HW] MANI TEJA

### ISSUE THREAD

**Issue by ManiTeja-31** [datastaxdevs/workshop-social-media-tiktok#119]
**Name:** MANI TEJA
**Email:**     manitejachalavadi765@gmail.com
**Linkedin Profile:**  linkedin.com/in/mani-teja-617052207

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot 2021-07-15 121127](https://user-images.githubusercontent.com/79055194/125769030-623db4a3-6e26-4d56-85b2-02821ab5d000.png)
<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot 2021-07-15 153329](https://user-images.githubusercontent.com/79055194/125770628-f222fd40-8f46-4c5d-b008-021a97c3ec66.png)
<SCREENSHOTS>
![Screenshot 2021-07-15 153435](https://user-images.githubusercontent.com/79055194/125770700-35299a0d-1854-44cd-895f-18adaee75daa.png)
![Screenshot 2021-07-15 153453](https://user-images.githubusercontent.com/79055194/125770725-61a39fb3-5186-4b19-88ad-2aa989035a73.png)

**Comment by RyanWelford** [comment]
Looks like you got through everything! Thanks MANI!

**Comment by ManiTeja-31** [comment]
> Looks like you got through everything! Thanks MANI!

accepted but didn't got any badge sir

**Comment by HadesArchitect** [comment]
Hey **MANI TEJA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EHVH7DEUQ0uRsgRuE3EPtA

**Comment by SonicDMG** [comment]
Looks like something did't work with the badge automation so I kicked it off again. There you go.
