### ISSUE TITLE
[HW] Gabriel Francis

### ISSUE THREAD

**Issue by GabrielDaKing** [datastaxdevs/workshop-social-media-tiktok#12]
**Name:** Gabriel Francis
**Email:** gncis8@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/gabriel-francis/

https://keen-lewin-0d071b.netlify.app

Attach the homework screenshots below:
-----------------------------------------

![Screenshot_1](https://user-images.githubusercontent.com/34449228/119710836-77333980-be7c-11eb-8b6e-e463e17fa3e4.png)
-- images removed by team --
![Screenshot_3](https://user-images.githubusercontent.com/34449228/119710841-79959380-be7c-11eb-899b-b645d22a71a1.png)
![Screenshot_4](https://user-images.githubusercontent.com/34449228/119710871-81edce80-be7c-11eb-8e36-cf599e142197.png)
![Screenshot_5](https://user-images.githubusercontent.com/34449228/119710879-831efb80-be7c-11eb-82e2-8d18eaaa0875.png)

**Comment by RyanWelford** [comment]
Nice! Thanks Gabriel!

**Comment by SonicDMG** [comment]
Well done Gabriel. Thank you and here's your badge -> https://api.badgr.io/public/assertions/rtzsRXNwQ1GH3xkkszlVfg?identity__email=gncis8%40gmail.com

**Comment by GabrielDaKing** [comment]
Thank you so much !!
