### ISSUE TITLE
[HW] Ananya Banerjee | Build a TikTok Clone Workshop

### ISSUE THREAD

**Issue by aspiringananya** [datastaxdevs/workshop-social-media-tiktok#121]
**Name:** Ananya Banerjee
**Email:** aspiringananya@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ananya-b-982a6b51/
**Site Link:** https://affectionate-babbage-7132a7.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1434" alt="Screenshot 2021-07-15 at 3 42 22 PM" src="https://user-images.githubusercontent.com/33785332/125783764-54702d2e-a4da-4f4f-aac6-0cb6d5c43609.png">

<img width="1338" alt="Screenshot 2021-07-15 at 3 42 41 PM" src="https://user-images.githubusercontent.com/33785332/125784377-49f5fac6-439a-47ec-bce9-6fb885c731cd.png">

<img width="1403" alt="Screenshot 2021-07-15 at 4 20 05 PM" src="https://user-images.githubusercontent.com/33785332/125784394-9f8123a0-a04c-40d8-a9b1-690ff8baf65b.png">

<img width="1430" alt="Screenshot 2021-07-15 at 4 20 46 PM" src="https://user-images.githubusercontent.com/33785332/125784398-19131394-068f-438a-84f8-8f2f9b559983.png">

<img width="1424" alt="Screenshot 2021-07-15 at 4 21 29 PM" src="https://user-images.githubusercontent.com/33785332/125784405-93013ef7-7b68-4084-8df6-f3779ec5b52d.png">

<img width="1437" alt="Screenshot 2021-07-15 at 4 53 59 PM" src="https://user-images.githubusercontent.com/33785332/125784427-457f50a7-e1e2-41e7-8783-c939c64c2a90.png">

<img width="1425" alt="Screenshot 2021-07-15 at 4 54 33 PM" src="https://user-images.githubusercontent.com/33785332/125784442-89036b16-419c-46eb-aa51-94608f913056.png">

<img width="1436" alt="Screenshot 2021-07-15 at 4 55 07 PM" src="https://user-images.githubusercontent.com/33785332/125784463-56331350-3207-42d2-bbf8-6524169aba0e.png">

<img width="1437" alt="Screenshot 2021-07-15 at 4 57 24 PM" src="https://user-images.githubusercontent.com/33785332/125784483-a7970334-6bc2-4002-93e1-f4bb276a79e5.png">

<img width="957" alt="Screenshot 2021-07-15 at 5 11 19 PM" src="https://user-images.githubusercontent.com/33785332/125784500-096a0699-e203-4ce6-946c-b133b19a6124.png">

Attach the homework step II screenshots below:
-----------------------------------------

<img width="1434" alt="Screenshot 2021-07-15 at 5 37 06 PM" src="https://user-images.githubusercontent.com/33785332/125786126-2b8089c6-c700-4fe4-8b8c-f4bd3a4fe86d.png">

<img width="1409" alt="Screenshot 2021-07-15 at 5 42 22 PM" src="https://user-images.githubusercontent.com/33785332/125786151-81288d13-cbe3-43fe-a887-733c92efb3c0.png">

**Comment by HadesArchitect** [comment]
Hey **Ananya Banerjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/U8PtsJkrTsKacR54SjC5RQ
