### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by AnjaliVis** [datastaxdevs/workshop-social-media-tiktok#122]
**Name:** Anjali Vishwakarma
**Email:** hazel.anjali@gmail.com
**Linkedin Profile:** linkedin.com/in/anjali-vishwakarma-078911162

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (1535)](https://user-images.githubusercontent.com/49023170/125799410-96ac3018-ac3d-4de7-91d6-0e7a7d5a8fdc.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Anjali Vishwakarma**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kl3pYGw3SomMvdYiLFTjaw
