### ISSUE TITLE
[HW] <Vemal K.S>

### ISSUE THREAD

**Issue by Vemal587** [datastaxdevs/workshop-social-media-tiktok#123]
Name: Vemal K.S
Email: vemal587@yahoo.com
Linkedin Profile: https://www.linkedin.com/in/vemal-k-s-106746113

Screenshots:
Create an Astra DB:
<img width="678" alt="Tiktok1" src="https://user-images.githubusercontent.com/85180620/125800121-b247e1b0-58f5-495e-8e0f-ba0043ae2c78.PNG">

Deploy Netlify:
<img width="960" alt="Tiktok2" src="https://user-images.githubusercontent.com/85180620/125800149-de888567-ab4c-4d06-af26-e82bfe9cf931.PNG">

My GitHub repository:
<img width="500" alt="TikTok3" src="https://user-images.githubusercontent.com/85180620/125800171-24727a61-715f-41e0-b038-a9816f2e8a68.PNG">

Gitpod IDE:
<img width="948" alt="Tiktok4" src="https://user-images.githubusercontent.com/85180620/125800210-4f7992b0-b49c-4a6d-996a-0e4dde0820c3.PNG">

Install the Netlify CLI:
<img width="953" alt="Tiktok5" src="https://user-images.githubusercontent.com/85180620/125800221-11adff9d-19fb-444b-b5f7-51f6a2145fb8.PNG">

Generate Application Token:
![Tiktok6](https://user-images.githubusercontent.com/85180620/125800325-bcb8ebcc-cd97-4f9a-b804-8c40dacbffc5.png)

Tiktok Clone Application:
<img width="956" alt="Tiktok7" src="https://user-images.githubusercontent.com/85180620/125800241-399335ba-668e-420a-8b2a-61bed1d67852.PNG">

List Collections named tktkposts:
<img width="898" alt="Tiktok8" src="https://user-images.githubusercontent.com/85180620/125800254-a3157001-d364-419b-bb03-386c47974d7a.PNG">

Search Documents:
<img width="942" alt="Tiktok9" src="https://user-images.githubusercontent.com/85180620/125800275-627d9fbb-adf1-4d66-9546-1183e40eb73b.PNG">

Serverless functions:
<img width="953" alt="Tiktok10" src="https://user-images.githubusercontent.com/85180620/125801298-92cdc266-f3d1-4a1e-b0b4-52327705da00.PNG">

**Comment by HadesArchitect** [comment]
Hey **Vemal K.S**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_GJ7laZQQ0qBanqNxGcZ0w
