### ISSUE TITLE
[HW] <Shamshad Akther>

### ISSUE THREAD

**Issue by shamshadkhan** [datastaxdevs/workshop-social-media-tiktok#124]
**Name:** Shamshad Akther
**Email:** shamshad.cse90@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/shamshad-akther/>

Attach the homework step I screenshots below:
-----------------------------------------
### 1. Login or Register to AstraDB and create database
![1](https://user-images.githubusercontent.com/12265243/125809299-5e151996-4bbc-4b92-90d5-27d937eb76a3.PNG)
### 2. Deploy to Netlify
![2](https://user-images.githubusercontent.com/12265243/125809412-67f9ead6-0fb1-4547-b0dc-ddf072b5e419.PNG)
### 3. Access YOUR GitHub repository
![3](https://user-images.githubusercontent.com/12265243/125812338-232f9f88-6a72-402e-8209-179c5b2bd906.PNG)
### 4. Launch GitPod IDE
![4](https://user-images.githubusercontent.com/12265243/125809911-67bea21e-6c79-4b52-9b51-81a53cc8a2ae.PNG)
### 5. Install the Netlify CLI (Command Line Interface)
![5](https://user-images.githubusercontent.com/12265243/125810517-b49a90f4-cc4b-4ccf-9bc1-00ff153b29c9.PNG)
### 6. Generate application token to securely connect to the database
![6](https://user-images.githubusercontent.com/12265243/125810677-89eca84c-8446-4607-8f75-e52220d656b7.PNG)
### 7. Configure and connect database
![7](https://user-images.githubusercontent.com/12265243/125810879-522178c6-67cf-4a72-9a1f-2063feb95269.PNG)
### 8. Launch your app
![8](https://user-images.githubusercontent.com/12265243/125810968-44608568-930c-4539-a71e-17741338a1a1.PNG)
### 9. Connect Netlify to your site
![9](https://user-images.githubusercontent.com/12265243/125811270-9e465073-5d70-4631-9728-8a76b841eea5.PNG)
### 10. Deploy to production
![10](https://user-images.githubusercontent.com/12265243/125811423-6eebbe38-3254-46a5-a3e5-050b8919fe6b.PNG)
![image](https://user-images.githubusercontent.com/12265243/125811610-636c3510-ad71-4ec0-9a77-11582eafdbd5.png)
<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
### 11. Connecting the Database
![11](https://user-images.githubusercontent.com/12265243/125811862-80c35471-b78d-4c72-8e88-6fdb9334e780.PNG)
### 12. Search documents in a collection
![12](https://user-images.githubusercontent.com/12265243/125812028-615059b4-991e-4aa7-b416-0300cb341db8.PNG)
### 13. Netlify Functions
![13](https://user-images.githubusercontent.com/12265243/125812159-02893624-9369-4814-b57d-1c0687271075.PNG)
<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Shamshad Akther**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ddit2x7kQg-q4BtRPd0yXA
