### ISSUE TITLE
[HW] puru

### ISSUE THREAD

**Issue by Puru-Soni** [datastaxdevs/workshop-social-media-tiktok#125]
**Name:** Puru
**Email:** puru20010105@gmail.com
**Linkedin Profile:** www.linkedin.com/in/puru-soni-646188205

Attach the homework step I screenshots below:
-----------------------------------------
Creating database:
![part_1_database](https://user-images.githubusercontent.com/74522965/125815915-d8e2b3d2-934d-4066-b9f3-d23979915918.jpg)

Deploying TikTok clone site:
![part1_tiktok_deployment](https://user-images.githubusercontent.com/74522965/125816000-180bc6d8-4237-45a5-a984-de2b0316af89.jpg)

Linking with Netlify:
![linking_netlify_tiktok](https://user-images.githubusercontent.com/74522965/125816061-eff70cac-ea31-413e-bbc9-f4531c6a5571.jpg)

Attach the homework step II screenshots below:
-----------------------------------------
 Collection in our database called "tktkposts":
![part2 1](https://user-images.githubusercontent.com/74522965/125816329-b281e042-d0b6-4df9-9e66-1c6b62556365.jpg)

Documents stored in a database:
![part_2](https://user-images.githubusercontent.com/74522965/125816421-f14a9039-e4db-4e5e-bcae-b20be064949a.jpg)

PART - 3:
![part2_endpoint](https://user-images.githubusercontent.com/74522965/125816644-af3b6051-243a-49df-8669-8f686ef9c47d.jpg)
![part2_posts](https://user-images.githubusercontent.com/74522965/125816651-57a6b513-90dc-4a62-8e4b-595dc98a5a7e.jpg)

**Comment by HadesArchitect** [comment]
Hey **Puru**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/bzsCpc9oTcWFRDRhC6IOqg
