### ISSUE TITLE
Rohan Goyal

### ISSUE THREAD

**Issue by 37rohan** [datastaxdevs/workshop-social-media-tiktok#127]
**Name:** Rohan Goyal
**Email:** rohangoyal264@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rohan-goyal-3a1744200/

# Screenshots of Database:
![Screenshot_1](https://user-images.githubusercontent.com/76154317/125820533-2f796db0-fe98-42d7-9df3-1135a228c150.png)
![Screenshot_2](https://user-images.githubusercontent.com/76154317/125820538-dc1483ff-8fac-47e8-a898-c5db4f3c0d6a.png)

## Deploy on Netlify and Repo on my GitHub:
![Screenshot_8](https://user-images.githubusercontent.com/76154317/125820600-31b223d0-e23c-401c-a481-98b915bb1ea9.png)
![Screenshot_9](https://user-images.githubusercontent.com/76154317/125820611-088d8218-0f03-4294-b9a0-62193c98f5b2.png)
## Changes in Gitpod Where i used to add another post:
![Screenshot_3](https://user-images.githubusercontent.com/76154317/125820662-7135ec34-d15a-41a5-82ff-54ce538765b9.png)
![Screenshot_4](https://user-images.githubusercontent.com/76154317/125820681-1fa09992-e453-4ef1-b009-215649025123.png)
![Screenshot_5](https://user-images.githubusercontent.com/76154317/125820685-e59dcc98-d9e9-4857-bb4b-15b720286a01.png)
![Screenshot_6](https://user-images.githubusercontent.com/76154317/125820689-ffbffa5d-037c-4bac-b32f-318a45f8f15e.png)

## Sucessfully added video:
![Screenshot_7](https://user-images.githubusercontent.com/76154317/125820707-61f2ac49-ffda-432a-8125-7095bc30d8a1.png)

**Comment by HadesArchitect** [comment]
Hey **Rohan Goyal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qFfoBKpRS0aLu1z32-ahUg
