### ISSUE TITLE
[HW]  Vishal

### ISSUE THREAD

**Issue by vishalprabha** [datastaxdevs/workshop-social-media-tiktok#128]
**Name:** Vishal Prabhachandar
**Email:** viprabha97@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/vishalprabha/

**Screenshots:**

Astra DB creation
![Screen Shot 2021-07-15 at 9 36 25 PM](https://user-images.githubusercontent.com/15261547/125821966-906d6d39-d1a3-4265-bbe6-eb09cd7df213.png)

Deployment in netlify with custom domain name 
![Screen Shot 2021-07-15 at 9 40 44 PM](https://user-images.githubusercontent.com/15261547/125822035-9d52fb04-8ed7-4e1c-a2d6-dde283428614.png)

Swagger UI
![Screen Shot 2021-07-15 at 9 42 13 PM](https://user-images.githubusercontent.com/15261547/125822172-97502142-dbab-47bf-87ff-69b6b7959292.png)

Serverless functions in netlify
![Screen Shot 2021-07-15 at 9 36 56 PM](https://user-images.githubusercontent.com/15261547/125822282-b7ac98b7-5a02-482b-8a2b-c21b7fad1448.png)

The serverless function executed in chrome
![Screen Shot 2021-07-15 at 9 41 29 PM](https://user-images.githubusercontent.com/15261547/125822517-5d6d8624-fc2b-4660-b0bf-397fc3b10bfd.png)

Deployed URL: https://documentapi-tiktok.vishalprabha.com/#/

**Comment by HadesArchitect** [comment]
Hey **Vishal Prabhachandar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/wHQc7cxPTbCgvQycjMosXQ
