### ISSUE TITLE
[HW] Talia Blain

### ISSUE THREAD

**Issue by razrobill** [datastaxdevs/workshop-social-media-tiktok#129]
**Name:** Talia Blain
**Email:** tb1126@york.ac.uk
**Linkedin Profile:** https://www.linkedin.com/in/talia-blain-0788291b1/

Attach the homework step I screenshots below:
-----------------------------------------

  

<img width="1440" alt="Screenshot 2021-07-15 at 16 48 08" src="https://user-images.githubusercontent.com/87183550/125822841-c581e441-da29-4c47-9147-a2d53cd56424.png">
<img width="1440" alt="Screenshot 2021-07-15 at 16 47 55" src="https://user-images.githubusercontent.com/87183550/125822859-e06fd168-5bd5-4ebe-8d0f-d50e26a60d44.png">

Attach the homework step II screenshots below:
-----------------------------------------

-- image removed by team --

<img width="1440" alt="Screenshot 2021-07-15 at 16 48 16" src="https://user-images.githubusercontent.com/87183550/125822881-bb950e0a-7402-4c72-b22b-cfbf42caede3.png">

<img width="1440" alt="Screenshot 2021-07-15 at 17 06 52" src="https://user-images.githubusercontent.com/87183550/125822946-6e85bf41-421f-406b-a70c-517f68ee49ad.png">

**Comment by HadesArchitect** [comment]
Hey **Talia Blain**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pWvw3TYzR3ukdGr21qHnLQ

**Comment by SonicDMG** [comment]
Also, I removed an image that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.
