### ISSUE TITLE
[HW] Build a TikTok clone

### ISSUE THREAD

**Issue by nfelicio1976** [datastaxdevs/workshop-social-media-tiktok#13]
**Name:** Nuno Jose Morais Felicio
**Email:** nfelicio@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nuno-felicio-a8b4356/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot 2021-05-26 18 21 59](https://user-images.githubusercontent.com/72761634/119710589-6c65ae00-be56-11eb-8cab-4f0e6dfb882f.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot 2021-05-26 18 22 27](https://user-images.githubusercontent.com/72761634/119710782-ae8eef80-be56-11eb-9f7a-575c72d64b61.png)
![Screenshot 2021-05-26 18 25 55](https://user-images.githubusercontent.com/72761634/119710822-bbabde80-be56-11eb-8418-099dd7ab9498.png)

![Screenshot 2021-05-26 18 21 54](https://user-images.githubusercontent.com/72761634/119710837-bfd7fc00-be56-11eb-876f-4a3efcc6b714.png)

![Screenshot 2021-05-26 18 21 34](https://user-images.githubusercontent.com/72761634/119710860-c797a080-be56-11eb-8af6-8cd17c3d69d1.png)

![Screenshot 2021-05-26 18 21 42](https://user-images.githubusercontent.com/72761634/119710923-d716e980-be56-11eb-83f9-143d2f895c81.png)

-- images removed by team --

![Screenshot 2021-05-26 18 54 07](https://user-images.githubusercontent.com/72761634/119710981-e6963280-be56-11eb-92ee-68c703911788.png)

![Screenshot 2021-05-26 18 55 41](https://user-images.githubusercontent.com/72761634/119711001-ea29b980-be56-11eb-94c0-03760bf5dbfd.png)

![Screenshot 2021-05-26 19 04 35](https://user-images.githubusercontent.com/72761634/119711010-ec8c1380-be56-11eb-8a94-64d6ef97a68b.png)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks great Nuno, nice job and you were SO CLOSE with the swag quiz. Here's your badge https://api.badgr.io/public/assertions/aibmmDUOSWuOcZwXa27GzQ?identity__email=nfelicio%40gmail.com

**Comment by nfelicio1976** [comment]
Thank you,

Cumprimentos,
Nuno Felício.


David Jones-Gilardi ***@***.***> escreveu no dia quinta,
27/05/2021 à(s) 15:19:
