### ISSUE TITLE
[HW] Samer Rihawi

### ISSUE THREAD

**Issue by srihawi** [datastaxdevs/workshop-social-media-tiktok#130]
**Name:** Samer Rihawi
**Email:** srihawi84@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/samerrihawi/

Attach the homework step I screenshots below:
-----------------------------------------

![screenshot1](https://user-images.githubusercontent.com/12184277/125824361-7f63c272-d6fb-4d28-89fd-c591ad073fba.JPG)
![screenshot2](https://user-images.githubusercontent.com/12184277/125824365-1f48890c-42cc-4745-9e28-0dcfcf636601.JPG)
![screenshot3](https://user-images.githubusercontent.com/12184277/125824366-2bb4a10e-8d39-4edb-b058-6a5484a7dbca.JPG)
![screenshot4](https://user-images.githubusercontent.com/12184277/125824372-063fe3af-2d0f-4754-8f03-0a3468c0582a.JPG)

  
Attach the homework step II screenshots below:
-----------------------------------------

![screenshot5](https://user-images.githubusercontent.com/12184277/125824423-ab5d924e-5dce-454e-9b00-df8950b1e865.JPG)
![screenshot6](https://user-images.githubusercontent.com/12184277/125824430-b20c098e-1c59-4b4a-adcf-0ed834189c05.JPG)

**Comment by HadesArchitect** [comment]
Hey **Samer Rihawi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OOp_FgvlQniyGOuCEUYiWA
