### ISSUE TITLE
[HW] <Hiba Imam>

### ISSUE THREAD

**Issue by hibaimam** [datastaxdevs/workshop-social-media-tiktok#131]
**Name:** Hiba Imam
**Email:** hibaimam@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/hibaimam/>

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1662" alt="Screen Shot 2021-07-15 at 12 00 41 PM" src="https://user-images.githubusercontent.com/61816458/125824972-6dc9d7a9-6e31-4b43-9d19-99d3e3316054.png">
<img width="1662" alt="Screen Shot 2021-07-15 at 12 01 01 PM" src="https://user-images.githubusercontent.com/61816458/125824982-efa65bbc-9c66-4ab8-bfef-e84acaf74a84.png">
<img width="1662" alt="Screen Shot 2021-07-15 at 12 01 19 PM" src="https://user-images.githubusercontent.com/61816458/125824990-277c63bb-a286-4697-ab02-d2f186c46ce8.png">
<img width="1662" alt="Screen Shot 2021-07-15 at 12 05 02 PM" src="https://user-images.githubusercontent.com/61816458/125824994-b925cd21-5ce4-40b3-a769-c6517a70fb02.png">
<img width="1578" alt="Screen Shot 2021-07-15 at 12 29 08 PM" src="https://user-images.githubusercontent.com/61816458/125825003-7ab58be6-374b-44a8-8f21-1fc5cf7086b3.png">

  
Attach the homework step II screenshots below:
-----------------------------------------

<img width="1578" alt="Screen Shot 2021-07-15 at 12 31 07 PM" src="https://user-images.githubusercontent.com/61816458/125825022-792fae44-1f86-495f-b054-715a5bfd2c6f.png">
<img width="1578" alt="Screen Shot 2021-07-15 at 12 31 00 PM" src="https://user-images.githubusercontent.com/61816458/125825030-a5d9c394-0ece-4e4b-95af-18aed11b16a2.png">
<img width="1578" alt="Screen Shot 2021-07-15 at 12 30 34 PM" src="https://user-images.githubusercontent.com/61816458/125825034-59950cb7-510d-4f03-b921-1449d9727a3a.png">
<img width="1578" alt="Screen Shot 2021-07-15 at 12 29 08 PM" src="https://user-images.githubusercontent.com/61816458/125825131-3f4641cc-201a-4e53-b388-50e123478d18.png">

**Comment by HadesArchitect** [comment]
Hey **Hiba Imam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/k2rsrjoeQQS28NoXAMTdfw
