### ISSUE TITLE
[HW] YongenChen

### ISSUE THREAD

**Issue by YongenChen** [datastaxdevs/workshop-social-media-tiktok#132]
**Name:** Yongen Chen
**Email:** rvvne@yahoo.com
**Linkedin Profile:** https://www.linkedin.com/in/yongenchen/

https://inspiring-kirch-cdf31b.netlify.app
This is my deployed netlify site!

<img width="890" alt="Screen Shot 2021-07-15 at 9 43 01 AM" src="https://user-images.githubusercontent.com/40329645/125826840-aae50549-8c1b-4405-a6a4-c3d848e5db7d.png">
<img width="988" alt="Screen Shot 2021-07-15 at 9 43 13 AM" src="https://user-images.githubusercontent.com/40329645/125826848-787bb71b-71bd-4880-a7da-0de1cea48890.png">
<img width="808" alt="Screen Shot 2021-07-15 at 9 43 42 AM" src="https://user-images.githubusercontent.com/40329645/125826852-233bd551-6b2f-4015-92bf-6baa528f30b7.png">

**Comment by HadesArchitect** [comment]
Hey **Yongen Chen**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0yo2fPsNQne00DVYSuF6UQ
