### ISSUE TITLE
[HW] James Fong

### ISSUE THREAD

**Issue by SomethingFish** [datastaxdevs/workshop-social-media-tiktok#133]
**Name:** James Fong Ka Chun
**Email:** S10205104@connect.np.edu.sg
**Linkedin Profile:** https://www.linkedin.com/in/james-fong-5a06b11a8/

Didn't take screenshots while I was doing the steps, but here are a few related screenshots and the link to the website.

Building and opening the site
![image](https://user-images.githubusercontent.com/73157400/125829016-15ec27c4-ff08-4992-bebb-f877b617e22f.png)
![image](https://user-images.githubusercontent.com/73157400/125829091-c6954487-ac9c-47a1-8b91-1744e43f7182.png)

Link to website:
https://naughty-engelbart-d83553.netlify.app

**Comment by HadesArchitect** [comment]
Hey **James Fong Ka Chun**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/N8tJjQHETzeAZ1On9jMO2A
