### ISSUE TITLE
[HW] <TIKTOK CLONE>

### ISSUE THREAD

**Issue by jckzacharski** [datastaxdevs/workshop-social-media-tiktok#134]
**Name:** Jacek Zacharski
**Email:** jckzacharski@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jacek-zacharski-b82387b/

Attach the homework step I screenshots below:
-----------------------------------------
https://eager-liskov-886145.netlify.app/#/
<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/85837883/125829025-b1e1ed8b-25e7-4a4c-9b3b-023c7e2ad0cc.png)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/85837883/125829475-a2c0083a-976d-4aae-b60f-6a2f9b3d8d44.png)

**Comment by jckzacharski** [comment]
Thanks for turtorials :)
Jacek

**Comment by HadesArchitect** [comment]
Hey **Jacek Zacharski**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/i4sWXb8IQk2aoAYD2aQ3nQ
