### ISSUE TITLE
[HW] Paulina Frolovaitė

### ISSUE THREAD

**Issue by rinadango** [datastaxdevs/workshop-social-media-tiktok#136]
**Name:** Paulina Frolovaitė
**Email:** pfrolovaite@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/paulina-frolovait%C4%97-6b3171216/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/35428039/125828156-c206bb0c-e120-4990-b587-473ff2a05101.png)
![image](https://user-images.githubusercontent.com/35428039/125828285-072bc54b-3c64-4ec5-bbf5-db33702ceecd.png)
![image](https://user-images.githubusercontent.com/35428039/125830664-10e49827-3f47-4aba-86fc-cb2e21ed612d.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/35428039/125829946-2742c2ac-2199-40ee-b18c-0a6143db9b20.png)
![image](https://user-images.githubusercontent.com/35428039/125829960-7d2187b4-c0d7-4556-bf18-9c86adc495c7.png)
![image](https://user-images.githubusercontent.com/35428039/125830303-b1a22314-142b-40eb-a1ff-bd886556f423.png)

**Comment by SonicDMG** [comment]
Hi Paulina, this looks good, but your email is not complete. Can you please provide that so we can give you a badge?

**Comment by rinadango** [comment]
> Hi Paulina, this looks good, but your email is not complete. Can you please provide that so we can give you a badge?

Oh sorry. It's pfrolovaite@gmail.com

**Comment by HadesArchitect** [comment]
Hey **Paulina Frolovaitė**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/BFy5HcgBTc2tfHDNCmbN9w
