### ISSUE TITLE
[HW] PepeAlex

### ISSUE THREAD

**Issue by PepeAlex** [datastaxdevs/workshop-social-media-tiktok#137]
**Name:** Alexander Pepe
**Email:** it.alexpepe@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------
![first](https://user-images.githubusercontent.com/47187507/125830748-bbac53e4-1b48-44ee-b426-79d1f5fd0ffa.png)
![second](https://user-images.githubusercontent.com/47187507/125830771-f6ec3334-faaa-4971-bb63-597390912f95.png)
![third](https://user-images.githubusercontent.com/47187507/125830785-30d33625-37a9-4afa-b420-07925ba02f53.png)
![fourth](https://user-images.githubusercontent.com/47187507/125830796-a10226f6-b7a5-492c-a40c-ee8f131d0f2d.png)
![fifth](https://user-images.githubusercontent.com/47187507/125830801-9adaad42-27e7-4a28-abb3-64bad105fc3f.png)
https://boring-mccarthy-48f321.netlify.app/#/
<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Awesome! Thanks Alex!

**Comment by HadesArchitect** [comment]
Hey **Alexander Pepe**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/OWjFVU8JR2iplGFFkkfdxQ
