### ISSUE TITLE
[HW]  YESHVI GUPTA

### ISSUE THREAD

**Issue by yeshu10** [datastaxdevs/workshop-social-media-tiktok#138]
**Name:** YESHVI GUPTA
**Email:** yeshvigupta10@gmail.com
**Linkedin Profile:** linkedin.com/in/yeshvi-gupta

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step I
![Screenshot (492)](https://user-images.githubusercontent.com/86351169/125831783-4f988cda-8ea2-4269-bbbb-755c683e17b5.png)
![Screenshot (496)](https://user-images.githubusercontent.com/86351169/125831799-590bb6b4-e309-4d11-b89d-e549c6ed06ba.png)
I screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **YESHVI GUPTA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ehr-gxhRQwmFi5i4kQax6Q
