### ISSUE TITLE
[HW] Saurabh Malviya

### ISSUE THREAD

**Issue by MalviyaSaurabh** [datastaxdevs/workshop-social-media-tiktok#139]
**Name:** Saurabh Malviya
**Email:** malviya.saurabh4u@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/saurabh-malviya-34763616/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/45642123/125834281-770acc58-c711-4dcd-8a3a-b9286f3dec55.png)
![image](https://user-images.githubusercontent.com/45642123/125834334-0e4a2949-0340-4082-8195-c816c321b190.png)
![image](https://user-images.githubusercontent.com/45642123/125834350-7851817e-87b5-41a6-bb82-80225972852c.png)
![image](https://user-images.githubusercontent.com/45642123/125834366-435e17fc-26ff-420d-a7b5-37ddd27421d8.png)
![image](https://user-images.githubusercontent.com/45642123/125834381-93243493-d845-4b40-b51d-a7c854c5f398.png)
![image](https://user-images.githubusercontent.com/45642123/125834399-d4f44017-8b6b-47f8-9187-e6cc2a708dd2.png)
![image](https://user-images.githubusercontent.com/45642123/125834437-fdbe0083-31fe-426e-8a89-4e960ab5269e.png)
![image](https://user-images.githubusercontent.com/45642123/125834409-00c8927c-d672-4990-bb89-42b8d6c09842.png)
Adding a content from Ania's tutorial
![image](https://user-images.githubusercontent.com/45642123/125834505-ffc6eefb-b32a-49f1-a51b-caf3b899ecdc.png)
![image](https://user-images.githubusercontent.com/45642123/125834518-dc7520f2-5d6a-4b81-9c35-30076481e38e.png)
![image](https://user-images.githubusercontent.com/45642123/125834615-e5a5aa85-6f8a-4123-846a-f5eca0f30834.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/45642123/125834281-770acc58-c711-4dcd-8a3a-b9286f3dec55.png)

**Comment by RyanWelford** [comment]
Awesome job, Saurabh! Thanks!

**Comment by HadesArchitect** [comment]
Hey **Saurabh Malviya**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/IxAeMH-MRPuB_6s1iGnAag
