### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by sree-lakshmi-p** [datastaxdevs/workshop-social-media-tiktok#14]
**Name:** Sreelakshmi Ramchandran
**Email:** sreepillai98@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sreelakshmi-ramchandran/
Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot from 2021-05-26 23-36-28](https://user-images.githubusercontent.com/60955122/119711317-05a7bb00-be7d-11eb-8bae-004cc39da8bd.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

-- images removed by team --

**Comment by RyanWelford** [comment]
Looks good, Sreelakshmi! Thanks for joining us!

**Comment by SonicDMG** [comment]
Awesome job, here's your badge -> https://api.badgr.io/public/assertions/bsIYPDSHTJux0gaDJKngHg?identity__email=sreepillai98%40gmail.com
