### ISSUE TITLE
[HW] Shivateja Burle

### ISSUE THREAD

**Issue by shivatejaburle** [datastaxdevs/workshop-social-media-tiktok#140]
**Name:** Shivateja Burle
**Email:** shivateja.burle@hotmail.com
**Linkedin Profile:** [View](https://www.linkedin.com/in/shivatejaburle/)

Attach the homework step I screenshots below:
-----------------------------------------
### Database Created:
![image](https://user-images.githubusercontent.com/38591257/125835571-b8fd9c1a-a704-4873-bde4-01c2a120a729.png)

### TikTok Clone in my git:
![image](https://user-images.githubusercontent.com/38591257/125833380-9667db3e-946a-48fe-b89e-5824670906b4.png)

### Site Deployed to Netlify:
![image](https://user-images.githubusercontent.com/38591257/125833566-fc9d3d5b-8a18-4cd3-b26c-1d277d4328ce.png)

### Authorization Granted:
![image](https://user-images.githubusercontent.com/38591257/125834924-9111760a-2fe2-42eb-af47-1d91853c27d4.png)

### In Gitpod Sample Browser:
![image](https://user-images.githubusercontent.com/38591257/125835040-1c34d1cc-5e04-4bee-ab7f-167a502bd134.png)

### My TikTok Site is Live now (in browser):
![image](https://user-images.githubusercontent.com/38591257/125833425-b0251e50-dc8b-4b3c-b7e1-be7937e3a8e5.png)

### Humming Bird Video Uploaded:
![image](https://user-images.githubusercontent.com/38591257/125837083-99322509-5a5d-4459-b925-a7886c9b2ff5.png)

### Humming Bird Video Posted:
![image](https://user-images.githubusercontent.com/38591257/125838258-904a8cee-412f-48d3-9350-ea5aa40f3f31.png)

**Comment by RyanWelford** [comment]
Woot woot! Great work, Shivateja! FYI,  I had to remove one image that had your token in it. I'd recommend deleting the token in your "Token Management" settings in Astra.

**Comment by HadesArchitect** [comment]
Hey **Shivateja Burle**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WgMNvJ9pT_aJyN2McPehLg
