### ISSUE TITLE
[HW] Aparna Mookerjee

### ISSUE THREAD

**Issue by aparnarepo** [datastaxdevs/workshop-social-media-tiktok#141]
**Name:** Aparna Mookerjee
**Email:** aparna.mookerjee@gmail.com

Attach the homework step I screenshots below:
-----------------------------------------

![tiktok_clone](https://user-images.githubusercontent.com/61774409/125835744-e2850b99-e500-49ee-9c54-02ea50dc353e.jpg)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Awesome work, Aparna!

**Comment by HadesArchitect** [comment]
Hey **Aparna Mookerjee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/I22gjtCkRn6eTnIdcyv-RA
