### ISSUE TITLE
[HW] Yash Kumar Hemnani

### ISSUE THREAD

**Issue by yashhemnani** [datastaxdevs/workshop-social-media-tiktok#143]
**Name:** Yash Kumar Hemnani
**Email:** yashhemnani0@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/yashhemnani/>

Attach the homework step I screenshots below:
Created Astra DB Database 
-----------------------------------------

![image](https://user-images.githubusercontent.com/22657887/125839339-68177c80-3607-46a2-881a-679e2b779f7f.png)  

Attach the homework step II screenshots below:
Successfully Caught up with Netlify

![image](https://user-images.githubusercontent.com/22657887/125839581-eabbbf2b-7013-4a74-a0e5-e068bec2cf7b.png)

-----------------------------------------
Successfully Deployed App Using GitPod

![image](https://user-images.githubusercontent.com/22657887/125839798-a26a9f59-0e4d-4021-a9b0-557a8e30f997.png)

Successfully launched the tiktok clone

![image](https://user-images.githubusercontent.com/22657887/125839864-b4c2f8b1-68ac-483b-aeb7-a771fc45c741.png)

**Comment by RyanWelford** [comment]
Nice! Thanks Yash!

**Comment by yashhemnani** [comment]
Hi @RyanWelford, Will I Get the Badge?

**Comment by HadesArchitect** [comment]
Hey **Yash Kumar Hemnani**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/HVOSa12cRUijGK7xmxP_rA

**Comment by SonicDMG** [comment]
There were some special chars in your email getting in the way. I removed those. Your badge is posted above.
