### ISSUE TITLE
[HW] Rebecca Lui

### ISSUE THREAD

**Issue by reblui** [datastaxdevs/workshop-social-media-tiktok#144]
**Name:** Rebecca Lui
**Email:** reblui@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/lui-rebecca/

Attach the homework step I screenshots below:
-----------------------------------------

![tiktok](https://user-images.githubusercontent.com/43976859/125841951-08b9bcdf-5b02-4a69-b571-bdf8758fe7d9.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<>

**Comment by RyanWelford** [comment]
Looks like you were able to deploy successfully! Thanks Rebecca!

**Comment by HadesArchitect** [comment]
Hey **Rebecca Lui**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZpaFV5uzTzyyT5LNGjiKLw
