### ISSUE TITLE
[HW] Garv Anand

### ISSUE THREAD

**Issue by kritika11111** [datastaxdevs/workshop-social-media-tiktok#145]
**Name:** Garv Anand
**Email:** garvanand03@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/garv-anand-476358217

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/87203104/125850828-f408be7c-3a18-48d9-9123-012fde4f2835.png)
![image](https://user-images.githubusercontent.com/87203104/125850905-50564c68-7c15-4e31-b04c-795ff66aaafd.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/87203104/125851254-82b0a71c-b778-49f4-83b1-a1463f742ea8.png)

**Comment by RyanWelford** [comment]
Thanks Garv! Were you able to deploy to Netlify? We'd like to see a successful deploy, or a link to the URL.

**Comment by kritika11111** [comment]
![image](https://user-images.githubusercontent.com/87203104/125867298-7f21679a-0b10-43e9-b11a-069b5c603e15.png)

**Comment by kritika11111** [comment]
![image](https://user-images.githubusercontent.com/87203104/125867420-405d54df-ae64-41d9-829e-4a988f27f6ae.png)

**Comment by kritika11111** [comment]
Yes i was able to deploy the netlify

**Comment by SonicDMG** [comment]
Ok, checked your netlify site and it looks good. Thank you for following up.

**Comment by HadesArchitect** [comment]
Hey **Garv Anand**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/q5EEb8B2QPa0HDqjCTpp6g
