### ISSUE TITLE
[HW] Divya Shah

### ISSUE THREAD

**Issue by D-HackCoder** [datastaxdevs/workshop-social-media-tiktok#146]
**Name:** Divya Shah
**Email:** divyashah00068@gmail.com
**Linkedin Profile:** https://bit.ly/DivyLinkedIn

Attach the homework step I screenshots below:
-----------------------------------------
![Stargate Tik-Tok App - Google Chrome 16-07-2021 01_30_09](https://user-images.githubusercontent.com/57376086/125851549-bce00eac-40a8-41e2-96ed-a02958b55b85.png)
![Stargate Tik-Tok App - Google Chrome 16-07-2021 01_31_21](https://user-images.githubusercontent.com/57376086/125851580-41dabb01-be7a-4ee9-8d63-f0cac5e9ff8b.png)
![Swagger UI - Google Chrome 16-07-2021 01_36_29_LI](https://user-images.githubusercontent.com/57376086/125851740-93070499-2fbb-495b-9ca7-c22698a6c822.jpg)
![Swagger UI - Google Chrome 16-07-2021 01_36_34_LI](https://user-images.githubusercontent.com/57376086/125851748-3fdda347-4ddb-4a32-a02d-25db124dcaa7.jpg)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Swagger UI - Google Chrome 16-07-2021 01_36_10_LI](https://user-images.githubusercontent.com/57376086/125851767-04e6cdb3-b3b0-4d85-9f5e-8f649a33b1f9.jpg)
![Swagger UI - Google Chrome 16-07-2021 01_36_20_LI](https://user-images.githubusercontent.com/57376086/125851779-40005353-fbfd-43a5-86a3-ba3ec76e4c19.jpg)
![Swagger UI - Google Chrome 16-07-2021 01_37_30](https://user-images.githubusercontent.com/57376086/125851793-50cea86e-2413-495e-b695-54296ef10bb7.png)
![Swagger UI - Google Chrome 16-07-2021 01_37_42](https://user-images.githubusercontent.com/57376086/125851803-acac25b9-3a5d-4792-ae49-8425c6a7e748.png)

**Comment by RyanWelford** [comment]
Great job, Divya! Thanks for joining us!

**Comment by HadesArchitect** [comment]
Hey **Divya Shah**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/CaWQ5XvsThmml-c94eSXfg
