### ISSUE TITLE
[HW] Saakshi

### ISSUE THREAD

**Issue by SaakshiSuresh** [datastaxdevs/workshop-social-media-tiktok#147]
**Name:** Saakshi Suresh
**Email:** saakshisuresh11@gmail.com
**Linkedin Profile:** www.linkedin.com/in/saakshi-suresh

Attach the homework step I screenshots below:
-----------------------------------------

![tiktokclone1](https://user-images.githubusercontent.com/74911931/125852983-9715c690-0ae8-481a-a05c-9a8dca75a98b.jpg)
![tiktokclone2](https://user-images.githubusercontent.com/74911931/125852998-8192a5ec-62cd-4a72-b80f-719371df7bfe.jpg)
![tiktokclone3](https://user-images.githubusercontent.com/74911931/125853009-45ddad86-d068-4e11-9229-1101802c61f9.jpg)

  
Attach the homework step II screenshots below:
-----------------------------------------

![tiktokclone4](https://user-images.githubusercontent.com/74911931/125853036-2872d9c6-144d-45db-ba00-3f37d1cdcd43.jpg)
![tiktokclone5](https://user-images.githubusercontent.com/74911931/125853053-1da1bdf7-f81d-4dbd-b032-790a8652e5cb.jpg)
![tiktokclone6](https://user-images.githubusercontent.com/74911931/125853074-a6f2bbb4-8ff7-4423-891b-a2313c1bdea4.jpg)

**Comment by RyanWelford** [comment]
Awesome! Thanks Saakshi!

**Comment by HadesArchitect** [comment]
Hey **Saakshi Suresh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/f2cGcFNZRB2C49CcScH6EQ
