### ISSUE TITLE
[HW] Piotr Wlazeł

### ISSUE THREAD

**Issue by Nieokorzesany** [datastaxdevs/workshop-social-media-tiktok#148]
**Name:** Piotr Wlazeł
**Email:** pancu1222@gmail.com
**Linkedin Profile:** https://adoring-blackwell-23a5ce.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------

![tiktok1](https://user-images.githubusercontent.com/38163577/125866473-c398ec73-8871-44c4-b519-8b6be002bb1a.png)
![tiktok2](https://user-images.githubusercontent.com/38163577/125866476-4713392c-0390-4bf6-969e-1266a7a15e4a.png)
![tiktok3](https://user-images.githubusercontent.com/38163577/125866479-cfffc47a-1e74-4859-b431-5227faa33531.png)
![tiktok4](https://user-images.githubusercontent.com/38163577/125866481-82243ba0-1e98-4166-98e3-b30857f9c0f1.png)
![tiktok5](https://user-images.githubusercontent.com/38163577/125866482-c295f718-a5ad-4af7-a5c1-1c5c9fc77b0c.png)
![tiktok6](https://user-images.githubusercontent.com/38163577/125866484-f51571d4-5f8e-49a5-9cfc-99fcf1d3e467.png)

  
https://adoring-blackwell-23a5ce.netlify.app/#/

**Comment by HadesArchitect** [comment]
Hey **Piotr Wlazeł**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ovTO3A6yQGKLyCML3pM_5g
