### ISSUE TITLE
[HW] ANKIT PATEL

### ISSUE THREAD

**Issue by akipatel** [datastaxdevs/workshop-social-media-tiktok#149]
**Name:** ANKIT PATEL
**Email:** vagita89@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ankit-patel-86233024/

Attach the homework steps screenshots below:
-----------------------------------------------------
![screen1](https://user-images.githubusercontent.com/1726002/125883871-92370684-da22-4cd0-82e3-d679c03a667e.PNG)
![screen2](https://user-images.githubusercontent.com/1726002/125883889-21d4fc69-89ab-4c49-8cb0-3f3c46b242b8.PNG)
![screen3](https://user-images.githubusercontent.com/1726002/125883897-d5a04430-cc02-49c9-8fbe-b44c9a79ce19.PNG)
![screen4](https://user-images.githubusercontent.com/1726002/125883904-cefe7a63-df59-4676-8e5d-c4a5535f6354.PNG)
![screen5](https://user-images.githubusercontent.com/1726002/125883917-232dccf3-010d-4412-ad34-d333393a1e7c.PNG)
![screen6](https://user-images.githubusercontent.com/1726002/125883924-f6a8855e-70a6-474a-9ccf-41d0cb0f53f2.PNG)

**Comment by RyanWelford** [comment]
Nice job, Ankit! Thanks!

**Comment by HadesArchitect** [comment]
Hey **ANKIT PATEL**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/57VbOZgUTAeGELmbJ6GARA
