### ISSUE TITLE
[HW] <TikTok Clone>

### ISSUE THREAD

**Issue by IshaMeera** [datastaxdevs/workshop-social-media-tiktok#151]
**Name:** Isha Raju
**Email:** ishmeera27@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/isha-meera-a858431b7>

Attach the homework step I screenshots below:
-----------------------------------------

<
![image](https://user-images.githubusercontent.com/72744901/125912665-877d7b6e-634c-4b05-a96b-d93412fee9d1.png)
>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Isha Raju**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1jrX1H04TIKnbKe8oY4stQ
