### ISSUE TITLE
[HW] Dovile Perednyte

### ISSUE THREAD

**Issue by dovii** [datastaxdevs/workshop-social-media-tiktok#153]
**Name:** Dovile Perednyte
**Email:** d.perednyte@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/dovile-perednyte-65641b17a/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot_9](https://user-images.githubusercontent.com/43847677/125926953-25497ea8-0266-43a3-8958-88712072a8f2.png)

![Screenshot_10](https://user-images.githubusercontent.com/43847677/125926970-a98f9d1c-9c84-47dc-ab7b-54ccb2d17a81.png)

![Screenshot_9a](https://user-images.githubusercontent.com/43847677/125927040-136d9ecd-5688-4028-96fe-1050f136e16b.png)

![Screenshot_11](https://user-images.githubusercontent.com/43847677/125927084-f71794c9-b88c-442c-9f57-23b148ff8967.png)

**Comment by RyanWelford** [comment]
Looking good! Thanks Dovile!

**Comment by HadesArchitect** [comment]
Hey **Dovile Perednyte**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VJGoijLMQHWW1mQWiW2g7g
