### ISSUE TITLE
[HW] Clare Ellis-Goss

### ISSUE THREAD

**Issue by cveg** [datastaxdevs/workshop-social-media-tiktok#156]
**Name:** Clare Ellis-Goss
**Email:** clarellis@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/clare-ellis-goss-6a2ab24/

Attach the homework step I screenshots below:
-----------------------------------------

![tiktok-database-astraDB](https://user-images.githubusercontent.com/87193022/125957511-b9f844e1-c0ee-45a4-9d40-dcb160568563.PNG)

![netlify-depolyed](https://user-images.githubusercontent.com/87193022/125957458-ee6c6154-eb00-4abd-9b17-f47eac478bec.PNG)

![netlify-deployed-2](https://user-images.githubusercontent.com/87193022/125957472-c4a20afa-4161-481a-a56f-7b8ccd60cd06.PNG)

![tiktok-app](https://user-images.githubusercontent.com/87193022/125957506-e9289116-9646-4087-af7a-5fcd3f832d04.png)

-----------------------------------------  
Unfortunately I ran out of time to complete the homework step II app, but I have saved Ania's video and will be watching it & following her instructions as soon as I can (I have a 1 year old so have very minimal spare time...)
-----------------------------------------

**Comment by RyanWelford** [comment]
Awesome job Clare! No worries on part 2, it is an optional (but useful) portion.

**Comment by HadesArchitect** [comment]
Hey **Clare Ellis**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/VXq6fZS8QsiTF6DJIL7wMg
