### ISSUE TITLE
[HW] Garv Anand

### ISSUE THREAD

**Issue by kritika11111** [datastaxdevs/workshop-social-media-tiktok#157]
**Name:** Garv Anand
**Email:** garvanand03@gmail.com
**Linkedin Profile:** http://www.linkedin.com/in/garv-anand-476358217

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/87203104/125970645-1300bde1-2016-486b-96d2-05f3c0244522.png)
![image](https://user-images.githubusercontent.com/87203104/125970698-c90784ad-9965-4e5b-b39e-9ac7bdc511ae.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/87203104/125970753-7ad06fc5-6ad1-400a-9a1a-28e5fa900396.png)
![image](https://user-images.githubusercontent.com/87203104/125970818-16038ac7-3d42-4b4e-bc16-e884ccedfdcd.png)
![image](https://user-images.githubusercontent.com/87203104/125970865-5fd5b3e5-6558-4a56-a4ea-221d9aa6ff2e.png)

**Comment by HadesArchitect** [comment]
Hey **Garv Anand**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4sHB2MZhQj2Zc_iGXtXHUw
