### ISSUE TITLE
[HW] <AYESHA HANNURE>

### ISSUE THREAD

**Issue by AYESHAHANNURE25** [datastaxdevs/workshop-social-media-tiktok#158]
**Name:** AYESHA HANNURE
**Email:** ayeshahannure.ah@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/ayesha-hannure-7b3205201/>

Attach the homework step I screenshots below:
-----------------------------------------

<
![db](https://user-images.githubusercontent.com/70697521/126099254-61da0032-0e27-4a32-9b7d-28a346e944cb.JPG)
![git](https://user-images.githubusercontent.com/70697521/126099281-5bdb8d02-75a0-49cb-928c-4add7f787383.JPG)
![NETLIFY](https://user-images.githubusercontent.com/70697521/126099308-1544bebe-9ee9-453a-8696-477c894a4266.JPG)
![pro](https://user-images.githubusercontent.com/70697521/126099315-7022381a-36b6-4751-ad1b-b9befa50bc77.JPG)
![SITE](https://user-images.githubusercontent.com/70697521/126099345-017418a2-b812-4dc7-85b1-ec4d6a617f18.JPG)
![CONNECT](https://user-images.githubusercontent.com/70697521/126099349-df9aff0d-1641-4c7d-9582-f645afc2b2a7.JPG)
![S10](https://user-images.githubusercontent.com/70697521/126099363-c4195359-9744-4f9a-989f-f4ec4cada49c.JPG)
![LINK](https://user-images.githubusercontent.com/70697521/126099383-da2556c8-e7cf-492b-9b2d-d65768bd1c07.JPG)

>
  
Attach the homework step II screenshots below:
-----------------------------------------

< I am start working with the Ania Video , I will send Screen shot of that soon thank you for the Video it was very helpful  >

**Comment by SonicDMG** [comment]
> I am start working with the Ania Video , I will send Screen shot of that soon thank you for the Video it was very helpful 
That's great, would love to see it

**Comment by SonicDMG** [comment]
Hi Ayesha, looks like you have the local environment working just fine. Nice! When I checked your deployed site at https://tender-darwin-796422.netlify.app I just get the blank TikTok page which makes me wonder if your env vars were not injected into netlify. I suggest you repeat the steps from step 9 https://github.com/datastaxdevs/appdev-week2-tiktok#9-connect-netlify-to-your-site and see if you can get that working. Please provide a screen or the link to your deployed site with the videos loaded.

**Comment by AYESHAHANNURE25** [comment]
![db](https://user-images.githubusercontent.com/70697521/126138979-7c92fd76-f1f5-4ccd-a08e-1761a8bf2702.JPG)
![git](https://user-images.githubusercontent.com/70697521/126139006-1e92a771-7e96-4f17-9b24-d968a71e9f9c.JPG)
![CONNECT](https://user-images.githubusercontent.com/70697521/126139030-c2429940-f1d9-4abb-a1b0-9fd273f644aa.JPG)
![NETLIFY](https://user-images.githubusercontent.com/70697521/126139037-75a3d146-dd01-4438-959a-d80fe8a76e3b.JPG)
![S10](https://user-images.githubusercontent.com/70697521/126139102-7ec0ee37-290e-4e6f-ba0a-9e10a1ddff8e.JPG)
![SITE](https://user-images.githubusercontent.com/70697521/126139116-534e1f5d-a21e-4b9c-8d5e-8e2fc7d7ae24.JPG)
![LINK](https://user-images.githubusercontent.com/70697521/126139143-75e69459-891a-4621-ad83-c38949991569.JPG)
![git](https://user-images.githubusercontent.com/70697521/126139176-50c1bf6c-fe21-496d-b91a-a6c60d427f16.JPG)

**Comment by SonicDMG** [comment]
Nice job Ayesha, thanks for following up.

**Comment by HadesArchitect** [comment]
Hey **AYESHA HANNURE**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KGc40QpvRjaAx2XmbpjxIQ
