### ISSUE TITLE
[HW] NAMRATHA SAMBARAPU

### ISSUE THREAD

**Issue by Namratha490** [datastaxdevs/workshop-social-media-tiktok#159]
**Name:** Namratha Sambarapu
**Email:** namrathaolivia@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/namratha-sambarapu-8ab6281a3/>

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/68885903/125971483-d2bcc15f-b746-4f04-bb51-036ade7b91ce.png)
![image](https://user-images.githubusercontent.com/68885903/125971652-ebbb2a96-4ae4-4b69-a8b1-d50cb9ba3fed.png)
![image](https://user-images.githubusercontent.com/68885903/125971900-22b72e64-fbb6-4dec-946b-a4d9fbddeb2b.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/68885903/125973473-a7ee54a4-31b3-454d-9eef-dd5171d4d861.png)
![image](https://user-images.githubusercontent.com/68885903/125974102-761dbcb0-9429-4cad-8f51-64877eb9c6dd.png)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Great job, Namratha! Just an FYI, I had to remove one image as it contained your Astra token. I recommend deleting your token for security.

**Comment by HadesArchitect** [comment]
Hey **Namratha Sambarapu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/2Cwxi5IpRk-zKARJnpFijw
