### ISSUE TITLE
[HW] Faiz Azhar

### ISSUE THREAD

**Issue by gabanz** [datastaxdevs/workshop-social-media-tiktok#162]
**Name:** Faiz Azhar
**Email:** gabanz@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/faizazhar/

Attach the homework step I screenshots below:
-----------------------------------------

My Astra database:
<img width="1670" alt="Screenshot 2021-07-16 at 11 32 27 PM" src="https://user-images.githubusercontent.com/4620813/125973693-903cd539-4a97-444f-8a8a-ef62da8f64dc.png">

My Netlify account:
<img width="1339" alt="Screenshot 2021-07-16 at 11 32 45 PM" src="https://user-images.githubusercontent.com/4620813/125973610-effb5a17-fd82-49e9-a683-c37ba25a3a56.png">

My Tiktok clone app:
<img width="1089" alt="Screenshot 2021-07-16 at 11 31 01 PM" src="https://user-images.githubusercontent.com/4620813/125973639-eb2b8a98-c5c5-4b3f-a918-5c1ed679908d.png">
  
Attach the homework step II screenshots below:
-----------------------------------------

Haven't finished yet... I'm trying to experiment deploying the JAMstack frontend to Cloudflare Pages instead of Netlify and using Cloudflare Workers instead of Netlify Functions to interact with Astra.

<img width="1106" alt="Screenshot 2021-07-17 at 2 07 25 AM" src="https://user-images.githubusercontent.com/4620813/125990657-e956d046-0ceb-4bf6-947b-3b38611d6b8a.png">

**Comment by RyanWelford** [comment]
Awesome! Nice job! Love that you're experimenting with new technologies. Let us know how it goes!

**Comment by HadesArchitect** [comment]
Hey **Faiz Azhar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/43mNVDhfSc6igcFrg2MoEQ
