### ISSUE TITLE
[HW] K S A R AMBEDKAR

### ISSUE THREAD

**Issue by ambedkar1985** [datastaxdevs/workshop-social-media-tiktok#163]
**Name:** K S A R AMBEDKAR
**Email:** ambedkar1985@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/k-s-a-r-ambedkar-50b12088/

Attach the homework steps screenshots below:
[HW Assign. of my own TIKTOK clone using Javascript.pdf](https://github.com/datastaxdevs/appdev-week2-tiktok/files/6832855/HW.Assign.of.my.own.TIKTOK.clone.using.Javascript.pdf)

**Comment by HadesArchitect** [comment]
Hey **K S A R AMBEDKAR**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/iRazFPX0Q_Sp3TGugI9c9A
