### ISSUE TITLE
[HW] Selim Emre Genel

### ISSUE THREAD

**Issue by segenel** [datastaxdevs/workshop-social-media-tiktok#166]
**Name:** Selim Emre Genel
**Email:** segenel02@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/selim-emre-genel-562673213

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/86852701/126014670-741893ad-2746-4b63-88a0-0e5db0b63aa5.png)
![image](https://user-images.githubusercontent.com/86852701/126014703-c84a7331-75bc-4774-8c21-85f89b2f8f6f.png)
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/86852701/126014835-b8381dd8-e796-42ec-bdc4-ea551ccd7a08.png)
![image](https://user-images.githubusercontent.com/86852701/126014964-a6b088f6-841c-4b61-8280-0e59e2abe7af.png)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge - and see you on the next episode this week!

**Comment by HadesArchitect** [comment]
Hey **Selim Emre Genel**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SvCxQjQIR_6Nfm16_DIM6g
