### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by ansah4525** [datastaxdevs/workshop-social-media-tiktok#167]
**Name:** Ansah Juned Siddiqui
**Email:** siddiquiansah@gmail.com
**Linkedin Profile:** Ansah siddiqui

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
![image](https://user-images.githubusercontent.com/77540884/126016803-b73c50ff-1a5b-4c59-a741-787b01988ded.png)
![image](https://user-images.githubusercontent.com/77540884/126016825-8e0d4dd8-f157-437c-b525-727b0f0b2df8.png)
![image](https://user-images.githubusercontent.com/77540884/126016844-a1649bc9-5b19-43e6-8d0a-e8f9fcb96b04.png)
![image](https://user-images.githubusercontent.com/77540884/126016860-3163062c-bb5c-4ca2-ad31-edb0e5931b8a.png)
![image](https://user-images.githubusercontent.com/77540884/126016866-ff4d48e7-bf99-4989-9207-aa96b364bdac.png)
![image](https://user-images.githubusercontent.com/77540884/126016881-5f7b7625-33d0-4529-96c6-9482b327467c.png)
![image](https://user-images.githubusercontent.com/77540884/126016903-4d880890-3b03-44d5-a538-f141235340ea.png)
![image](https://user-images.githubusercontent.com/77540884/126016977-2072b5a7-2727-4f15-b9de-c0aaecc7ef79.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Hello! Please take care of NEVER uploading your Astra DB token (or any other secret) publicly to Github. We edited the above description, taking out reference to a couple of screenshots, but you should go to your Astra dashboard and revoke the token immediately, creating another one (and adjusting the app accordingly if you want).
The most important screenshot was also missing, and that would be of the working deployed application at https://boring-wiles-2a163e.netlify.app/#/ - we could check that it is working anyway.
So: congratulations! The app is running in production and you deserve your badge! See you on the next episode!

**Comment by HadesArchitect** [comment]
Hey **Ansah Juned Siddiqui**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UqQLvsf4QNOw7P8KHHPrEw
