### ISSUE TITLE
[HW] Anjali Anna Peter

### ISSUE THREAD

**Issue by AnjaliAnna** [datastaxdevs/workshop-social-media-tiktok#168]
**Name:** Anjali Anna Peter
**Email:** anjaliannapeter4@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anjaliannapeter/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/57408523/126027522-96fefbef-47e9-4079-a9bc-9e9b791dddcb.png)
![image](https://user-images.githubusercontent.com/57408523/126027532-ad6637a5-d3af-4aa3-9cfc-1b686f6e1f44.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Well done! Enjoy your badge and see you this week for the third episode in the series!

**Comment by HadesArchitect** [comment]
Hey **Anjali Anna Peter**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SVprnstnTrexcfCcejIBKQ
