### ISSUE TITLE
[HW] Umang Dakh

### ISSUE THREAD

**Issue by Denny-UD** [datastaxdevs/workshop-social-media-tiktok#169]
**Name:** Umang Dakh
**Email:** umangdakh@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/umang-dakh/

Attach the homework step I screenshots below:
-----------------------------------------
https://goofy-panini-700875.netlify.app/#/
![Screenshot (140)](https://user-images.githubusercontent.com/77261658/126031379-204ecc4c-7c63-4259-9dd0-a3d10c8d5984.png)
![Screenshot (141)](https://user-images.githubusercontent.com/77261658/126031388-3f3ace7e-07bb-4811-8721-4f0d3f7ce307.png)
![Screenshot (142)](https://user-images.githubusercontent.com/77261658/126031390-af70010b-c6b4-426b-b5f1-868958a8940e.png)
![Screenshot (143)](https://user-images.githubusercontent.com/77261658/126031396-6aed5f46-b14c-446c-b2cd-9d9ef4073f5f.png)
![Screenshot (144)](https://user-images.githubusercontent.com/77261658/126031407-9b9e244d-88f6-47d2-a097-6706b31cad62.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (145)](https://user-images.githubusercontent.com/77261658/126031418-d9c1fe5d-de2a-401d-b9bd-d8ab96217a1a.png)
![Screenshot (146)](https://user-images.githubusercontent.com/77261658/126031422-02abcda2-dedb-4c87-a126-f88ceb02726f.png)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **Umang Dakh**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JaS8XhesTtyHibkqv2Ye8g
