### ISSUE TITLE
[HW] Mayank Pandit

### ISSUE THREAD

**Issue by mayankpandit00** [datastaxdevs/workshop-social-media-tiktok#17]
**Name:** Mayank Pandit
**Email:** panditmayank2207@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/mayank-pandit-3b9624211/

Attach the homework step I screenshots below:
-----------------------------------------

![Tik-Tok-Clone-HW](https://user-images.githubusercontent.com/83175648/119732764-3e07c300-be96-11eb-8ca7-bb4ec88a0ab3.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you got it set deployed successfully! Thanks Mayank!

**Comment by SonicDMG** [comment]
And here's your badge. Thank you again for joining us. https://api.badgr.io/public/assertions/YeWfqbXRQoeQAeJsEcIkfQ?identity__email=panditmayank2207%40gmail.com
