### ISSUE TITLE
[HW] PARIDHI CHOKHANI

### ISSUE THREAD

**Issue by Pari04** [datastaxdevs/workshop-social-media-tiktok#170]
**Name:** Paridhi Chokhani
**Email:** paridhichokhani09@gmail.com
**Linkedin Profile:** linkedin.com/in/paridhichokhani

Attach the homework step I screenshots below:
-----------------------------------------

![clone2](https://user-images.githubusercontent.com/48173195/126031419-a3e8e7e5-a33f-475d-ae55-ebd23c63f3cd.png)!
[local](https://user-images.githubusercontent.com/48173195/126031435-0693edeb-fe9b-4713-a5ea-fb4a04ea5ed4.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![LOCAL1](https://user-images.githubusercontent.com/48173195/126031439-157966fe-f406-45ad-b0d1-fa040d257571.png)

![local2](https://user-images.githubusercontent.com/48173195/126031440-afae5e75-79b8-47fb-9635-c120dc523fa9.png)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **Paridhi Chokhani**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/13vjTxoZRuCVcwVoJlHHzA
