### ISSUE TITLE
[HW] <NAME>jitendra yadav

### ISSUE THREAD

**Issue by jitendra2002** [datastaxdevs/workshop-social-media-tiktok#171]
**Name:** Jitendra Yadav
**Email:** itendrayadav012002@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by jitendra2002** [comment]
sir, I
![Screenshot (266)](https://user-images.githubusercontent.com/83636887/126033486-8ba132bf-2088-4b7c-9be1-5ecd3e870609.png)
![Screenshot (267)](https://user-images.githubusercontent.com/83636887/126033489-772c532e-cdbc-4030-9dfd-49927d9098a7.png)
![Screenshot (268)](https://user-images.githubusercontent.com/83636887/126033492-e6ce24da-c815-47b4-8224-5836edf057fc.png)
![Screenshot (262)](https://user-images.githubusercontent.com/83636887/126033505-46ac4555-054e-44b2-82b2-f16ef56a3716.png)
![Screenshot (263)](https://user-images.githubusercontent.com/83636887/126033507-9e33f721-b44c-426d-9552-054518a59ffb.png)
![Screenshot (264)](https://user-images.githubusercontent.com/83636887/126033508-900a5b27-5014-4f0c-8425-0d077df3b796.png)
![Screenshot (265)](https://user-images.githubusercontent.com/83636887/126033509-b78338dc-0f59-424e-96fe-db367aa4cf4c.png)
![Screenshot (259)](https://user-images.githubusercontent.com/83636887/126033518-d6ec0578-b916-4b72-a05f-73d5257bdb72.png)
![Screenshot (260)](https://user-images.githubusercontent.com/83636887/126033519-4a6a60df-d0ac-4c2a-a98b-7320005d0e65.png)
![Screenshot (261)](https://user-images.githubusercontent.com/83636887/126033522-09630ff3-673a-4560-9c71-8d09ad186cf4.png)
 have completed my homework
[](URL) 


t
![Screenshot (269)](https://user-images.githubusercontent.com/83636887/126033545-3b468712-6405-4547-9ce4-df8964a3caec.png)



thank you

**Comment by SonicDMG** [comment]
Hi there. You did the homework correctly and earned your badge, but we can't issue it without your name and email. Feel free to reach out to me directly if you are not comfortable with posting those here.

**Comment by jitendra2002** [comment]
Sir my name is jitendra yadav (#171)

And my email address is this
***@***.***

**Comment by jitendra2002** [comment]
<#171 my name is jitendra yadav and my email address is this itendrayadav012002@gmail.com>

**Comment by HadesArchitect** [comment]
Hey **Jitendra Yadav**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KL23KkxwRyaFcRlpSMzmiw

**Comment by jitendra2002** [comment]
Thank you so much. Sir
