### ISSUE TITLE
[Astra DB TikTok Clone] <SABUJ GOLUI>

### ISSUE THREAD

**Issue by SabujGolui** [datastaxdevs/workshop-social-media-tiktok#172]
**Name:** Sabuj Golui
**Email:** www.sabujgolui@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/sabuj-golui-215941201/>

Attach the homework step I screenshots below:
-----------------------------------------

<![2021-07-15 (1)](https://user-images.githubusercontent.com/83773953/126038299-aa3a628c-4017-499f-8479-497ac57d8c2c.png)>
<![2021-07-17](https://user-images.githubusercontent.com/83773953/126038310-a0365316-d388-47db-8ed9-b5818de1df08.png)>
<![2021-07-17 (3)](https://user-images.githubusercontent.com/83773953/126038316-9dfd270c-5f95-44be-bfb6-2f22446ec4e8.png)>
  
Attach the homework step II screenshots below:
-----------------------------------------

<
![2021-07-17 (2)](https://user-images.githubusercontent.com/83773953/126038346-d0553048-d823-42e9-9939-a818e85a0e76.png)
>
<
![2021-07-17 (1)](https://user-images.githubusercontent.com/83773953/126038371-7d0c9f25-6224-486d-bdaf-b8831f8ec018.png)
>

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **Sabuj Golui**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/De1mnwc5Q0yQfjWregTaXA

**Comment by SabujGolui** [comment]
sir, i have already completed my 3 projects
1. todolist.
2. tiktok clone.
3. netflix clone.
am I eligible for the Golden badge?
& how I can own my Golden badge?
