### ISSUE TITLE
[appdev-week2-tiktok Home work] <Building TikTok Clone> by: Nidhi Mathur

### ISSUE THREAD

**Issue by Sunidhimathur** [datastaxdevs/workshop-social-media-tiktok#173]
**Name:** Nidhi Mathur
**Email:** nidhiskr2014@gmail.com
**LinkedIn Profile:** https://www.linkedin.com/in/nidhi-mathur-9093681ab/

Attaching the homework screenshots  of step I &  step II below:
----------------------------------------- 

![1](https://user-images.githubusercontent.com/66857025/126041649-d8340776-92d5-4a12-807b-66ed50ed7f98.png)

![2](https://user-images.githubusercontent.com/66857025/126041653-ca80014f-156c-47ac-94d8-e60bcba8b6fa.png)

![3](https://user-images.githubusercontent.com/66857025/126041657-092611f9-9917-491e-94f8-f0694274e1ae.png)

![4](https://user-images.githubusercontent.com/66857025/126041658-e71003c8-5454-425e-90d7-5ce9545cdbc6.png)

![5](https://user-images.githubusercontent.com/66857025/126041660-8d7d5c8b-940c-42a6-8a9e-3e012eed5ddb.png)

![6](https://user-images.githubusercontent.com/66857025/126041665-18ab947f-0bcd-46fd-8c2a-c0f9e1733d5f.png)

![7](https://user-images.githubusercontent.com/66857025/126041670-1c9511c0-5739-4208-a76a-d7dba2fcfc29.png)

![8](https://user-images.githubusercontent.com/66857025/126041674-2c731af6-134a-445d-bb02-bf364844c94f.png)

![9](https://user-images.githubusercontent.com/66857025/126041678-875cea46-996f-401f-84a7-b574b04c03b3.png)

![10](https://user-images.githubusercontent.com/66857025/126041683-6267d5db-fff8-4b00-82d4-c8ca8bc73d6c.png)

![11](https://user-images.githubusercontent.com/66857025/126041687-ee403d21-a03a-4daa-9b9b-d7cba72bf827.png)

![12](https://user-images.githubusercontent.com/66857025/126041688-ddd8fffa-6555-4465-b48f-b702ecd428ed.jpg)

![13](https://user-images.githubusercontent.com/66857025/126041689-178f24c8-7572-4ac2-b04c-07239b00b5f3.jpg)

![15](https://user-images.githubusercontent.com/66857025/126041698-9c851160-5996-4bf8-a832-69df3aa7afb8.png)

![16](https://user-images.githubusercontent.com/66857025/126041699-ea753ab3-f6b2-4d07-8ecc-05b14d33f6f7.png)

![17](https://user-images.githubusercontent.com/66857025/126041701-38e655d5-a35c-49e7-85fe-69560ff67432.png)

![18](https://user-images.githubusercontent.com/66857025/126041702-9228b719-1edc-4e63-be4b-656d56970581.png)

**Comment by hemidactylus** [comment]
Well done, enjoy your badge!
(for convenience you could have added a screenshot or a link to the final deployed running app e.g. https://friendly-boyd-336487.netlify.app/#/ )
See you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **Nidhi Mathur**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pymGdAqRQt2Hsru-NTjgzg
