### ISSUE TITLE
[HW] Cira Foster

### ISSUE THREAD

**Issue by cirmar** [datastaxdevs/workshop-social-media-tiktok#174]
**Name:** Cira Foster
**Email:** cfoster32@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/cfoster32/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot 2021-07-14 213545](https://user-images.githubusercontent.com/10169348/126052104-b457a79f-86a0-4f3e-bd3f-af3131f21a47.png)

![README-md-workshop-astra-tik-tok-Gitpod-Code](https://user-images.githubusercontent.com/10169348/126052099-53a082bf-76df-415f-b310-dd063733ea53.png)

![netlify-working-url](https://user-images.githubusercontent.com/10169348/126052110-6cc5a834-976e-4fb6-86bb-bd9a078c5112.png)

![list-collections](https://user-images.githubusercontent.com/10169348/126052115-82065618-6695-4e93-823b-0a3adc820c1d.png)

![search-documents-in-collection](https://user-images.githubusercontent.com/10169348/126052116-d6622619-2535-4463-9775-859817781155.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Well done, congratulations! Enjoy your badge and see you on the next episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **Cira Foster**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/vyn5jmaPRXGCkN2445EMsA

**Comment by cirmar** [comment]
Thanks, learning a lot!
