### ISSUE TITLE
[HW] Abhay Khosla

### ISSUE THREAD

**Issue by Abhay2412** [datastaxdevs/workshop-social-media-tiktok#176]
**Name:** Abhay Khosla
**Email:** abhaykhosla0@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abhaykhosla/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

**1. Login or Register to Astra DB and create database**

Screenshot of the Astra DB created:
![AstraDB screenshot](https://user-images.githubusercontent.com/57297897/126046247-09f619b2-d856-4224-98f9-f7fdd8ac1720.png)

**2. Deploy to Netlify**
Screenshot of successfully deploying in Netlify:
![Netlify Creation](https://user-images.githubusercontent.com/57297897/126046538-cd3c84f2-97d8-42b4-be44-6875e94fe1c3.png)

**4. Launch GitPod IDE**
Screenshot of the remote command being run:
![GitPod remote command](https://user-images.githubusercontent.com/57297897/126046825-18c7b8d6-fd5f-4e69-a0ff-fdbdec5015d6.png)

**5. Install the Netlify CLI (Command Line Interface)**

Screenshot of the Netlify command running:
![Netlify command running](https://user-images.githubusercontent.com/57297897/126047000-50a8a881-3aa4-49a1-9ffe-f96a3f1f9f1f.png)

**7. Configure and connect database**

Skipped the Step #6 screenshot due to showing the token for security reasons. 
Screenshot of the Astra setup command:
![Command of Astra setup](https://user-images.githubusercontent.com/57297897/126052999-7fe44b3a-90f0-4dbe-954b-570601667828.png)

**8. Launch your app**
Screenshot of the Clone TikTok App running locally:
![Launch App Screen](https://user-images.githubusercontent.com/57297897/126053033-0e727a01-16ba-4342-a104-c079f55c5d59.png)

**10. Deploy to production**
Screenshot of Deployed TikTok Clone:
![Sucessful Deployed](https://user-images.githubusercontent.com/57297897/126054071-236e0b3c-9f78-4774-9875-90a5e79e5b6d.png)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
Screenshot of 200 Response:
![200 Response](https://user-images.githubusercontent.com/57297897/126054331-36181c06-c512-4bda-85ac-0a89ebd4edbb.png)

Screenshot of the functions in Netlify:
![Functions](https://user-images.githubusercontent.com/57297897/126054341-272ea889-c2bd-4f92-a112-609ac06ada68.png)

Screenshot of an additional video on the TikTok Clone Giannis Video:
![Giannis Video](https://user-images.githubusercontent.com/57297897/126054432-76148d69-4ed5-4949-b703-9043dad8a43c.png)

**Comment by hemidactylus** [comment]
Hello! Congratulations, well done: enjoy your badge and see you on the next episode this week!

**Comment by HadesArchitect** [comment]
Hey **Abhay Khosla**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/wOEiFH2iSh-mTzb773WJYQ
