### ISSUE TITLE
[HW] <Anni Huang>

### ISSUE THREAD

**Issue by anni-huang** [datastaxdevs/workshop-social-media-tiktok#177]
**Name:** Anni Huang
**Email:** anni.huany@gmail.com
**Linkedin Profile:** https://www.linkedin.com/huanganni/

Please see attached:
[HW2 TikTok Clone.pdf](https://github.com/datastaxdevs/appdev-week2-tiktok/files/6835622/HW2.TikTok.Clone.pdf)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **Anni Huang**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/jIu_vPpgSDa2nL8E3aqk8A
