### ISSUE TITLE
[HW] A B Ganapathy

### ISSUE THREAD

**Issue by AHayBagPant** [datastaxdevs/workshop-social-media-tiktok#178]
**Name:** A B Ganapathy
**Email:** abganapathy.rvim22@gmail.com
**Linkedin Profile:** linkedin.com/in/ganapathy-a-b-897757205/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (439)](https://user-images.githubusercontent.com/87089035/125832012-545b5330-d023-43b8-99ad-00e4e1ba2813.png)
![Screenshot (440)](https://user-images.githubusercontent.com/87089035/125832020-dfe2d4a9-7140-4df0-b007-20323e2085f4.png)
![Screenshot (441)](https://user-images.githubusercontent.com/87089035/125832028-7106483c-d879-4732-8d0d-c9f79a474167.png)
![Screenshot (442)](https://user-images.githubusercontent.com/87089035/125835664-1e5a1a88-cb33-4d16-922a-c38b6163fa83.png)

**Comment by hemidactylus** [comment]
Hello! Well done, enjoy your badge! And join us for the next episode of the series this weelk!

**Comment by HadesArchitect** [comment]
Hey **A B Ganapathy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8ihiPAEMSriGVMj7_NBqGA
