### ISSUE TITLE
[HW] Adarsh Chakraborty

### ISSUE THREAD

**Issue by adarsh-chakraborty** [datastaxdevs/workshop-social-media-tiktok#179]
**Name:** Adarsh Chakraborty
**Email:** adarshchak108@gmail.com
**Linkedin Profile:** www.linkedin.com/in/adarsh-chakraborty

Attach the homework step I screenshots below:
-----------------------------------------
### 1. Created a Netlify site from the repository.
![Screenshot_1](https://user-images.githubusercontent.com/35111001/126061679-c9a94d49-8f4d-46f0-beed-cf9b47d8d0ec.png)

### 2. Created an Astra DB with the name ticktok_workshop_db and tiktok_keyspace
![Screenshot_2](https://user-images.githubusercontent.com/35111001/126061680-0a325c50-262d-4610-9e22-53f4c9d504f1.png)

### 3. I decided to work locally and not use gitpod so i cloned the repo to my local machine.
![Screenshot_3](https://user-images.githubusercontent.com/35111001/126061681-29e0d713-0535-4d65-b808-fa5bd4ce352c.png)

### 4. After downloading all dependencies, Installing Netlify CLI.
![Screenshot_4](https://user-images.githubusercontent.com/35111001/126061683-1bb5ff76-6845-4fd4-bd49-a097550a948e.png)

### 5. The command to create env file didn't work because i have latest version of node, I had to do it on gitpod and then I copied the env file data to my project.
![Screenshot_5](https://user-images.githubusercontent.com/35111001/126061684-f9c089f3-0115-4c84-a847-49f42f8726b5.png)

### 6. Starting Development server by netlify dev
![Screenshot_6](https://user-images.githubusercontent.com/35111001/126061686-2fe44154-c26c-429f-8ffb-6cc568d571b6.png)

### 7. Importing updated env file to netlify. 
![Screenshot_7](https://user-images.githubusercontent.com/35111001/126061687-82c778d3-62b7-4d65-a235-b4fea34b8500.png)

### 8. netlify build
![Screenshot_8](https://user-images.githubusercontent.com/35111001/126061688-42b7d727-b8cc-46ff-afaf-e0feb4fa54c5.png)
![Screenshot_9](https://user-images.githubusercontent.com/35111001/126061689-6a457ad0-8db9-4a4d-a062-eed9e627b5a4.png)

### 10. Deploying to netlify.
![Screenshot_10](https://user-images.githubusercontent.com/35111001/126061691-ef53fc49-08aa-49a2-8e86-a6c42d99ebe9.png)

### 11. Result
![Screenshot_11](https://user-images.githubusercontent.com/35111001/126061692-f93a2d12-f450-468e-974d-6aaf6abc838f.png)

I have also added 1 more user in addData file as you can see in the above screenshot.
Project is live at: [https://zealous-swartz-1932e0.netlify.app](https://zealous-swartz-1932e0.netlify.app)

Thanks

**Comment by hemidactylus** [comment]
Congratulations, well done (and special appreciation for adding a new user)! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **Adarsh Chakraborty**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ecblxGyeRf6QUqoLRlT6NA
