### ISSUE TITLE
[HW] Aditi Anup

### ISSUE THREAD

**Issue by AditiAnup** [datastaxdevs/workshop-social-media-tiktok#18]
**Name:** Aditi Anup
**Email:** aditianup242@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/aditi-anup-47a142161/

https://hopeful-dubinsky-5c0634.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/37284834/119766521-cb690880-bed2-11eb-84be-39b3a0fde970.png)
  
Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --

![image](https://user-images.githubusercontent.com/37284834/119766588-edfb2180-bed2-11eb-86b4-5a2c598188ad.png)

![image](https://user-images.githubusercontent.com/37284834/119766840-5c3fe400-bed3-11eb-8af1-300056aa5fb7.png)

![image](https://user-images.githubusercontent.com/37284834/119766870-6c57c380-bed3-11eb-8a3b-fcea36cb1255.png)

**Comment by RyanWelford** [comment]
Awesome job Aditi!

**Comment by SonicDMG** [comment]
Awesome, thank you again for joining us. Here you go. https://api.badgr.io/public/assertions/_ocxFpzWSw-Xln4zCthZnQ?identity__email=aditianup242%40gmail.com
