### ISSUE TITLE
[HW] Riya Roshan

### ISSUE THREAD

**Issue by riyaroshan** [datastaxdevs/workshop-social-media-tiktok#180]
**Name:** Riya Roshan
**Email:** riyaroshan1212@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/riya-roshan-2464661b2/

Attach the homework step I screenshots below:
-----------------------------------------
My Astra database:
![image1](https://user-images.githubusercontent.com/65805909/126062428-ef650604-1b57-45a2-b751-3bea35375d83.jpg)

My Netlify account:
![image2](https://user-images.githubusercontent.com/65805909/126062492-ad5e9991-9896-425f-ab01-9976ce206c8a.jpg)

The Tiktok Clone App:
![image3](https://user-images.githubusercontent.com/65805909/126062499-70a0bfd8-e114-4d1e-88b0-0d23f75aacbd.jpg)
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/65805909/126062653-7ca66842-1825-43d9-aade-a7e9e7c685fa.png)

![image](https://user-images.githubusercontent.com/65805909/126062847-246f5b90-9d98-4a3e-bc53-ff114cffbe9f.png)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by hemidactylus** [comment]
WARNING: the fourth screenshot displays your Astra DB token for all to see. Please revoke it and generate a new one as soon as possible (adjusting the application if you want to).

**Comment by HadesArchitect** [comment]
Hey **Riya Roshan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZCAGDZfZTv-5NTpiAWC5og
