### ISSUE TITLE
[HW] <Rimon>

### ISSUE THREAD

**Issue by Rimon99** [datastaxdevs/workshop-social-media-tiktok#181]
**Name:** Rimon
**Email:** rimondas292@gmail.com

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
![1](https://user-images.githubusercontent.com/86638868/126069989-44c1423b-e9cb-47ee-9b43-7e7922ab306f.jpg)
![2](https://user-images.githubusercontent.com/86638868/126069999-90784603-d872-4360-b5bb-3555d9dc64e3.jpg)

**Comment by hemidactylus** [comment]
Hi, well done! Enjoy your badge and see you on the third episode of the series this week!
p.s. Spirited Away is my favorite by Miyazaki.

**Comment by Rimon99** [comment]
Hi i think the badge is not yet issued as i could not find the link nor is it showing in my badgr account.
p.s. Spirited away and grave of the fireflies are my favourite too :D

**Comment by HadesArchitect** [comment]
Hey **Rimon**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-L4NcDFsS7KxE1sicQ6LMA
