### ISSUE TITLE
[HW] Maxim Suslov

### ISSUE THREAD

**Issue by maxx27** [datastaxdevs/workshop-social-media-tiktok#185]
**Name:** Maxim Suslov
**Email:** suslov.mn@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/msuslov/

Attach the homework step I screenshots below:
-----------------------------------------

Netlify App:
https://app.netlify.com/sites/agitated-roentgen-64b269/
![image](https://user-images.githubusercontent.com/5478638/126082636-e2e218fb-ba47-4e2c-8668-ecf5e60c30f0.png)

Working App:
![image](https://user-images.githubusercontent.com/5478638/126082642-5c00788e-37e8-4e19-adbf-e91cfbdf9b37.png)

Working locally:
![image](https://user-images.githubusercontent.com/5478638/126082657-c1752acd-f97e-4738-8fb3-9f5d76ff1d46.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

In progress. I will provide more info later due to a lack of time.

**Comment by hemidactylus** [comment]
You got your Tiktok clone running on Netlify so your homework is already OK. But please, go ahead with the video by Ania so you will learn the most - especially about how React applications work! Let us know and see you for the third episode this week!

**Comment by HadesArchitect** [comment]
Hey **Maxim Suslov**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QCX6aQEgRua_ISVMQiyoRg
