### ISSUE TITLE
[HW] <Jonathan Duarte Martinez>

### ISSUE THREAD

**Issue by JDRXcr** [datastaxdevs/workshop-social-media-tiktok#188]
**Name:** Jonathan Duarte Martínez
**Email:** jj.duartem@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jonathan-duarte-mart%C3%ADnez-229138203/
Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Homework3](https://user-images.githubusercontent.com/2062278/126009089-44296cd6-12f7-44de-b336-085dba42287e.JPG)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Homework4](https://user-images.githubusercontent.com/2062278/126150431-c1b9baaf-a384-407a-a287-97d5208885c3.JPG)

**Comment by hemidactylus** [comment]
You have done well and you Tiktok clone is running in GitPod.
But now you should deploy it to production on Netlify, as described starting from Step 9 here: https://github.com/datastaxdevs/appdev-week2-tiktok#9-connect-netlify-to-your-site .
Please complete the exercise and re-submit with a screenshot of the Netlify application running, and good luck!

**Comment by HadesArchitect** [comment]
Hey **Jonathan Duarte Martínez**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ZKgwz-Z9TpCuj3NWqtUDhw

**Comment by SonicDMG** [comment]
I see the tiktok app deployed per the netlify link. Thanks Jonathan.
