### ISSUE TITLE
[HW] P A Marshal

### ISSUE THREAD

**Issue by MarshalAmbu12** [datastaxdevs/workshop-social-media-tiktok#189]
**Name:** P A Marshal
**Email:** marshalrockzz9326@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/p-a-marshal-bb86521b9/

Attach the homework step I screenshots below:
-----------------------------------------

Here's my screenshots:

![Screenshot 1](https://user-images.githubusercontent.com/57985234/126155756-ddca07e4-eb86-47fe-8552-071ef1f14d38.png)
![Screenshot 2](https://user-images.githubusercontent.com/57985234/126155780-c298d3ca-21cb-4b1e-a787-0677be062cda.png)
![Screenshot 3](https://user-images.githubusercontent.com/57985234/126155794-4a720ca1-791d-4a8f-879d-7fc8bf567d40.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

Here's my screenshots:

![Screenshot 4](https://user-images.githubusercontent.com/57985234/126157943-d77cb0b9-9c9c-4203-aea0-4797e2b14fe7.png)
![Screenshot 5](https://user-images.githubusercontent.com/57985234/126157960-f937ce06-e9a6-47bc-a585-c4019ee8a809.png)

My App:

![Screenshot 3](https://user-images.githubusercontent.com/57985234/126158100-bd630d69-3513-4b93-bf84-494e19132c18.png)

**Comment by hemidactylus** [comment]
Congratulations, well done! Enjoy your badge and see you on the next episode, this week!

**Comment by HadesArchitect** [comment]
Hey **P A Marshal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/SyDPzOIxS-a3a1BifYR1sw
