### ISSUE TITLE
[HW] Ravi Beniwal

### ISSUE THREAD

**Issue by codewithbenny** [datastaxdevs/workshop-social-media-tiktok#19]
**Name:** Ravi Beniwal
**Email:** ravi.beniwal_cs20@gla.ac.in
**Linkedin Profile:** www.linkedin.com/in/ravi-beniwal-a7bb55198

Attach the homework All steps  screenshots below:
--------------------------
-- images removed by team --
![Screenshot (19)](https://user-images.githubusercontent.com/64968577/119776179-3d951980-bee2-11eb-9812-7d50937a9248.png)
-- images removed by team --
![Screenshot (21)](https://user-images.githubusercontent.com/64968577/119776182-3e2db000-bee2-11eb-8621-85e37eab889d.png)

---------------

<SCREENSHOTS>
  

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Well done Ravi!

**Comment by SonicDMG** [comment]
Great job and thank you again for joining us. Here you go -> https://api.badgr.io/public/assertions/hgoRAb7BSYGAAx5hbSU0dA?identity__email=ravi.beniwal_cs20%40gla.ac.in
