### ISSUE TITLE
[HW] <Farha Parveen Padiyathu Puthenkattil Fazal>

### ISSUE THREAD

**Issue by FarhaParveen919** [datastaxdevs/workshop-social-media-tiktok#191]
**Name:** Farha Parveen Padiyathu Puthenkattil Fazal
**Email:** farhaparveen919@gmail.com
**Linkedin Profile:** www.linkedin.com/in/farhaparveenpf

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
![step1](https://user-images.githubusercontent.com/56920928/126179798-bc3065e7-7dad-454f-b5d7-82c03719425b.jpeg)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREEN
![deployed](https://user-images.githubusercontent.com/56920928/126183025-31503798-3cdb-4366-88ce-bb2d444532f6.jpeg)

![stargate_Tik-Tok](https://user-images.githubusercontent.com/56920928/126179369-df43007b-e42a-4aef-9462-737f5286ede6.jpeg)
SHOTS>

**Comment by HadesArchitect** [comment]
Hey **Farha Parveen Padiyathu Puthenkattil Fazal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/QhaGhU1xQBuo9flptsZm7Q
