### ISSUE TITLE
[HW] Tep Yith

### ISSUE THREAD

**Issue by tep-y** [datastaxdevs/workshop-social-media-tiktok#192]
**Name:** Tep Yith
**Email:** tep.yith@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tep-y/

Attach the homework step I screenshots below:
-----------------------------------------

AstraDB
<img width="1076" alt="01_astraDB" src="https://user-images.githubusercontent.com/72581899/126187557-502f40e0-41f1-46bc-bd25-00319c994d2f.png">

Netlify
<img width="1237" alt="02_deployToNetlify_github" src="https://user-images.githubusercontent.com/72581899/126187613-b22f6cfb-3cad-4339-b84c-95f658543ef3.png">

Personal GitHub repo
<img width="1021" alt="03_lauchGitPodIDE_ownrepo" src="https://user-images.githubusercontent.com/72581899/126187716-751d5c52-5ca2-463a-ae67-6f82d46d839a.png">

Database Token
<img width="1420" alt="04_databaseToken" src="https://user-images.githubusercontent.com/72581899/126187761-1136d74e-dccd-4273-8f6a-216df7111d72.png">

Deploy
<img width="1438" alt="05_deployToNetlify" src="https://user-images.githubusercontent.com/72581899/126187820-c8dbea7d-bcff-41be-bc7a-23520033d89d.png">
  
Attach the homework step II screenshots below:
-----------------------------------------

**Comment by HadesArchitect** [comment]
Hey **Tep Yith**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/UvQ3jgQ9RYO2juCsJodMQw
