### ISSUE TITLE
[HW] Victor Montilla

### ISSUE THREAD

**Issue by victor5516** [datastaxdevs/workshop-social-media-tiktok#196]
**Name:** Victor Montilla
**Email:** victor5516@gmail.com
**Linkedin Profile:** www.linkedin.com/in/victorm1811

SITE
https://affectionate-cori-b7a712.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------

![deploysuccess](https://user-images.githubusercontent.com/26474025/126258083-8918cf46-98d0-4b65-af27-ee213e880d50.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![finalTik](https://user-images.githubusercontent.com/26474025/126258117-2745eb68-5e5b-4b61-aa1c-2e57e72ef369.png)
![Tick-tock_deployed](https://user-images.githubusercontent.com/26474025/126258185-349ffcbe-aef7-4057-bc4e-b063517d0d29.png)

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Hello, Victor, well done! Appreciate the customised post - it shows you played a bit with the application/database!
Enjoy your well-deserved badge and see you for the third episode of the series!

**Comment by HadesArchitect** [comment]
Hey **Victor Montilla**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/XGJaCGCEQG6GrgaHJNxtiw
