### ISSUE TITLE
[HW] <Balaji M>

### ISSUE THREAD

**Issue by bxlxji** [datastaxdevs/workshop-social-media-tiktok#197]
**Name:** Balaji M
**Email:** balajimurugan9@hotmail.com
**Linkedin Profile:** https://www.linkedin.com/in/balaji-m-975694207/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="959" alt="app1" src="https://user-images.githubusercontent.com/79824566/126281546-e01387a6-e552-46ee-80bb-2d73b997b203.PNG">

  
Attach the homework step II screenshots below:
-----------------------------------------

<none>

**Comment by hemidactylus** [comment]
Well done! Enjoy your badge and see you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **Balaji M**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/P4sR_KlZQo2JjIM6oLtlrA
