### ISSUE TITLE
[HW] Jimit Kishor Mehta

### ISSUE THREAD

**Issue by JimitMehta18** [datastaxdevs/workshop-social-media-tiktok#198]
**Name:** Jimit Kishor Mehta
**Email:** jimitmehta34@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/jimitmehta16/

Attach the homework step I screenshots below:
-----------------------------------------

STEP 1.2
![image](https://user-images.githubusercontent.com/60439568/126264377-25c819d1-cbac-40e7-b2e8-51fc54bfe952.png)

STEP 1.3
![image](https://user-images.githubusercontent.com/60439568/126264400-4f3fad24-2ed8-4c21-aaa9-1d9126f18c27.png)

STEP 1.4
![image](https://user-images.githubusercontent.com/60439568/126264425-75a66dfc-ab47-4cff-ba09-31321eea5bee.png)

STEP 1.5
 ![image](https://user-images.githubusercontent.com/60439568/126264731-2d4b466a-7dd6-44de-b3f6-5d271b09d293.png)

STEP 1.7
![image](https://user-images.githubusercontent.com/60439568/126264769-2d99df50-d00b-4d58-9350-62cc0e620bf5.png)

STEP 1.8
![image](https://user-images.githubusercontent.com/60439568/126264788-3bcb20d3-578f-4aef-9ff4-12be376f6d74.png)

STEP 1.9
![image](https://user-images.githubusercontent.com/60439568/126264802-3b666997-36c5-44be-99b4-e2d07f9cdc59.png)

STEP 1.10
![image](https://user-images.githubusercontent.com/60439568/126264813-4db2937f-d04e-4e9b-af4f-86d467d86192.png)
-----------------------------------------
![image](https://user-images.githubusercontent.com/60439568/126264861-63ca15ee-8a3b-420a-ad69-b3a63cba9e8e.png)
-----------------------------------------

Attach the homework step II screenshots below:
-----------------------------------------
WORKING ON IT
<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Well done! Enjoy your badge and see you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **Jimit Kishor Mehta**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4NYttlUZTH2Hni87tIswFQ

**Comment by JimitMehta18** [comment]
Thank you!!
