### ISSUE TITLE
[HW] TANVI UMESH MEHTA

### ISSUE THREAD

**Issue by Tanvi10072000** [datastaxdevs/workshop-social-media-tiktok#199]
**Name:** TANVI UMESH MEHTA
**Email:** tanvimehta1007@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tanvi-mehta-157b141b7/

Attach the homework step I screenshots below:
-----------------------------------------

STEP 1.2 :
![image](https://user-images.githubusercontent.com/67104536/126288713-50cbe724-fe5f-4566-b897-9b3c1f16a674.png)

STEP 1.3 :
![image](https://user-images.githubusercontent.com/67104536/126288993-602842f3-81a4-476a-bf6b-0b2a06616769.png)

STEP 1.4 :
![image](https://user-images.githubusercontent.com/67104536/126289082-40f54888-a9ca-46a5-8cb5-47e191baf3e8.png)

STEP 1.5 :
![image](https://user-images.githubusercontent.com/67104536/126289121-28185efc-aa94-4030-9ac0-de5bd9a8422a.png)

STEP 1.7 :
![image](https://user-images.githubusercontent.com/67104536/126289162-09010bb9-b7ea-479f-ab1b-90c5e44c537f.png)

STEP 1.8 :
![image](https://user-images.githubusercontent.com/67104536/126289183-3c3aefce-6416-45b8-a925-6467e80ed919.png)

STEP 1.9 :
![image](https://user-images.githubusercontent.com/67104536/126289217-1b71cc7e-4292-46b0-b10b-f3417f580769.png)

STEP 1.10 :
![image](https://user-images.githubusercontent.com/67104536/126290147-6795de29-920a-408c-a8b4-07f1808f274d.png)

![image](https://user-images.githubusercontent.com/67104536/126289607-540b78de-b42f-4fbc-8f7b-a2da074f7d42.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

WORKING ON IT!

**Comment by hemidactylus** [comment]
Well done! Enjoy your badge and see you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **TANVI UMESH MEHTA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/B20fjrykRGSGTdb3AgEAMg

**Comment by Tanvi10072000** [comment]
Heyy !! Thank you so much for the badge ..
