### ISSUE TITLE
[HW] <ANUPAMA>

### ISSUE THREAD

**Issue by Anu2022** [datastaxdevs/workshop-social-media-tiktok#200]
**Name:** ANUPAMA
**Email:** anusree0122@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anupama-pachila-5848b1195/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![1](https://user-images.githubusercontent.com/87195044/126298306-da2dd655-bd3e-4482-aa91-7ab678faca01.PNG)
![2](https://user-images.githubusercontent.com/87195044/126298354-ce73729f-f792-4663-aa2e-bdcb482f530e.PNG)
![5](https://user-images.githubusercontent.com/87195044/126298481-f88f501c-3146-436b-b8af-ffcff2a1f5e6.PNG)
![Capture1](https://user-images.githubusercontent.com/87195044/126298503-63af18c5-440b-4e0c-ad29-f029348331f4.PNG)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Well done!
But *warning* you left a couple screenshots with your token in plain sight - I removed them from here, but strongly suggest you revoke the current token from your Astra DB dashboard and generate a new one (updating the Tiktok clone as you see fit).

Enjoy your badge and see you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **ANUPAMA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4O8vwMofRbqOR0nk9k-Nhw
