### ISSUE TITLE
[HW] Khushi Goyal

### ISSUE THREAD

**Issue by KhushiGoyal123** [datastaxdevs/workshop-social-media-tiktok#201]
**Name:** Khushi Goyal
**Email:** khushi030201goyal@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/khushi-goyal-644030211/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/83352983/126321663-5eaa5587-1f1f-45e4-bf8c-9942850a888f.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/83352983/126321784-6cd31e73-8e16-4e9e-9971-654b5c15dbe8.png)

<SCREENSHOTS>

**Comment by hemidactylus** [comment]
Well done! Enjoy your badge and see you on the third episode of the series this week!

**Comment by HadesArchitect** [comment]
Hey **Khushi Goyal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4gjD50XQROCddZFdgk00RQ
