### ISSUE TITLE
[HW] <Salaimuniselvam>

### ISSUE THREAD

**Issue by Salaimuniselvam** [datastaxdevs/workshop-social-media-tiktok#202]
**Name:**  salaimuniselvam
**Email:**  salaimuniselvam7@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/salai-muni-selvam-b7aaa71b4/
netlify-prod-link : https://agitated-shaw-cb7d03.netlify.app

![screenshot (1)](https://user-images.githubusercontent.com/84083924/126325234-598fb872-2dc5-423d-b8f9-01460fa65a29.jpg)

![Screenshot (113)](https://user-images.githubusercontent.com/84083924/126325445-cd089175-f8e9-47e3-bcca-4ce4f8513229.png)

![Screenshot (110)](https://user-images.githubusercontent.com/84083924/126325672-5f8982a8-25bd-4d2f-8e7c-4f6c38e64715.png)

![Screenshot (109)](https://user-images.githubusercontent.com/84083924/126325823-e87ccb29-e4b9-455c-8910-65c764eb941f.png)

**Comment by HadesArchitect** [comment]
Hey **salaimuniselvam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/6XqPK75vQrmXYKZcTD6KRw
