### ISSUE TITLE
[HW] Ankit Rajput

### ISSUE THREAD

**Issue by ankit49** [datastaxdevs/workshop-social-media-tiktok#203]
**Name:** Ankit Rajput
**Email:** ankitrajput1902@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ankit-rajput-365b5b199/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot from 2021-07-20 21-10-46](https://user-images.githubusercontent.com/38065713/126353972-c665e32c-a90b-4015-96c3-1b44228ee67f.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

Working on It

**Comment by HadesArchitect** [comment]
Hey **Ankit Rajput**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/pRgGAItVSUaVPblaNUS0bA
