### ISSUE TITLE
[HW] Sohini Mukhopadhyay

### ISSUE THREAD

**Issue by Shirozuma** [datastaxdevs/workshop-social-media-tiktok#204]
**Name:** Sohini Mukhopadhyay
**Email:** sohini.kharghar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sohini-mukhopadhyay-88009b170/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (568)](https://user-images.githubusercontent.com/43903292/126378446-ff89b3c8-4ce1-4944-b0ed-e064314fa363.png)

![Screenshot (569)](https://user-images.githubusercontent.com/43903292/126378475-b8f7ad9f-a63d-4b35-a658-c0127a597fc3.png)

![Screenshot (570)](https://user-images.githubusercontent.com/43903292/126378511-a70e9582-3d1f-4b45-9cec-6eb0c9fffe65.png)

**Comment by HadesArchitect** [comment]
Hey **Sohini Mukhopadhyay**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/bRCXtqYqToaycW9Pxaospw
