### ISSUE TITLE
[HW] Kinga Baryczka

### ISSUE THREAD

**Issue by dazaiii** [datastaxdevs/workshop-social-media-tiktok#205]
**Name:** Kinga Baryczka
**Email:** kin.baryczka@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kinga-baryczka-6621a520b/

Attach the homework step I screenshots below:
-----------------------------------------
![Zrzut ekranu 2021-07-20 202055](https://user-images.githubusercontent.com/58816347/126378648-e7d340a4-0c2b-4b79-a1ea-e33dd7a2e754.png)

![Zrzut ekranu 2021-07-20 202654](https://user-images.githubusercontent.com/58816347/126378666-a9b11721-79ef-4706-8c90-ba3ba5b95a46.png)

![Zrzut ekranu 2021-07-20 204250](https://user-images.githubusercontent.com/58816347/126378708-225172a6-f071-4d75-8bfd-6079dd543973.png)
  
Attach the homework step II screenshots below:
-----------------------------------------
![Zrzut ekranu 2021-07-20 203956](https://user-images.githubusercontent.com/58816347/126378737-cb11fa74-cc31-4d2a-bab1-87971112e878.png)

![Zrzut ekranu 2021-07-20 204029](https://user-images.githubusercontent.com/58816347/126378747-f598dfbb-e2d5-47d5-adfd-cabdebd67de6.png)

**Comment by HadesArchitect** [comment]
Hey **Kinga Baryczka**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ASdufoiASXaJ0UwJf-KUgw
