### ISSUE TITLE
[HW] ALEX JACKSON

### ISSUE THREAD

**Issue by AlexJackson01** [datastaxdevs/workshop-social-media-tiktok#206]
**Name:** Alex Jackson
**Email:** ajjackson22@gmail.com
**Linkedin Profile:** 

Attach the homework step I screenshots below:
-----------------------------------------

I built the app and edited it myself with Ania first and then deployed it using your step I instructions:

![Tik-tok-clone](https://user-images.githubusercontent.com/75219313/126383212-882b46df-d533-4813-a57f-ade3f8adc49e.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

See above

**Comment by HadesArchitect** [comment]
Hey **Alex Jackson**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/TqvtjjbkR26Ebk3_g3t5pQ
