### ISSUE TITLE
[HW] Ilona Kovalova

### ISSUE THREAD

**Issue by iloncka** [datastaxdevs/workshop-social-media-tiktok#208]
**Name:** Ilona Kovalova
**Email:**  iloncka@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ilona-kovalova/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot - 14 07 2021 , 19_19_29](https://user-images.githubusercontent.com/12134003/126382936-d1d8970a-e995-46f9-8b51-1ed3161d1da9.png)

![Screenshot - 14 07 2021 , 19_18_46](https://user-images.githubusercontent.com/12134003/126382996-3c801c41-eff1-4ec1-9079-baaee67d8651.png)

![Screenshot - 14 07 2021 , 20_14_21](https://user-images.githubusercontent.com/12134003/126383179-caae7b23-0e01-4c8c-9768-c039a3f052c9.png)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

![Screenshot - 20 07 2021 , 22_37_29](https://user-images.githubusercontent.com/12134003/126387361-5ba270cd-8ba8-423d-b069-837d7be6faa1.png)

![Screenshot - 20 07 2021 , 22_49_29](https://user-images.githubusercontent.com/12134003/126387370-8e19ec77-dec4-455b-adbc-02edf53cd6b8.png)

![Screenshot - 20 07 2021 , 22_54_50](https://user-images.githubusercontent.com/12134003/126387376-442b0fa9-5857-4d58-911d-ead6af02209a.png)

**Comment by HadesArchitect** [comment]
Hey **Ilona Kovalova**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/3EMVGcQ_RYmg4zVXGf_1zw
