### ISSUE TITLE
[HW] <Supriya>

### ISSUE THREAD

**Issue by Supriya648** [datastaxdevs/workshop-social-media-tiktok#209]
**Name:** Supriya Ramaswamy
**Email:** supriya24r@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/supriya-ramaswamyr>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![part1a tiktok](https://user-images.githubusercontent.com/61849924/126392519-43e89fc7-2b2f-4296-87a6-0e4b5243be59.jpg)
![part1b tiktok](https://user-images.githubusercontent.com/61849924/126392523-47ded129-aeaa-46fc-8e92-28d4034c494a.jpg)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

 ![Part2 a](https://user-images.githubusercontent.com/61849924/126392317-8cf141c8-4dde-4492-adbe-cadc8aee9b69.JPG)

![Part2 b](https://user-images.githubusercontent.com/61849924/126392321-860ee2cf-388d-4f49-8f3e-a104e0298fb2.JPG)

**Comment by HadesArchitect** [comment]
Hey **Supriya Ramaswamy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/yTpaClZyQIW9MgnBrl6nZg
