### ISSUE TITLE
[HW] Rajas Pofalkar

### ISSUE THREAD

**Issue by rajas2512** [datastaxdevs/workshop-social-media-tiktok#21]
**Name:** Rajas Pofalkar
**Email:** rajas.pofalkar@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rajas-pofalkar-23b104200/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot 2021-05-27 131527](https://user-images.githubusercontent.com/81470116/119787122-818e1b80-beee-11eb-9210-9307e4d6b820.png)

**Comment by RyanWelford** [comment]
Looks like you successfully deployed the app! Thanks Rajas!

**Comment by SonicDMG** [comment]
And here's your badge. Thank you again for coming to the workshop. https://api.badgr.io/public/assertions/QbC8YQHBS_GmBISuwgzZOg?identity__email=rajas.pofalkar%40gmail.com
