### ISSUE TITLE
[HW] Tyler Nguyen

### ISSUE THREAD

**Issue by Tylerflx** [datastaxdevs/workshop-social-media-tiktok#210]
**Name:** Tyler Nguyen
**Email:** Tylernguyen33325@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tylernguyen0727/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1421" alt="Screen Shot 2021-07-20 at 4 32 10 PM" src="https://user-images.githubusercontent.com/32749190/126395464-43fcf69c-a071-4412-b111-0bf74fe0f354.png">

<img width="1419" alt="Screen Shot 2021-07-20 at 4 42 33 PM" src="https://user-images.githubusercontent.com/32749190/126395511-dbce3540-2025-43ab-9ace-2b7b81ea5278.png">
  
Attach the homework step II screenshots below:
-----------------------------------------

-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **Tyler Nguyen**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/45ViSD9pRnSqUzXlXj_oHw

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because they contained your Astra token. Please delete your current token from the Astra UI to ensure we don't have any security issues.

**Comment by Tylerflx** [comment]
> Also, I had to remove some of your images because they contained your Astra token. Please delete your current token from the Astra UI to ensure we don't have any security issues.

Sure, thanks!
