### ISSUE TITLE
[HW] Beta Lin

### ISSUE THREAD

**Issue by linbeta** [datastaxdevs/workshop-social-media-tiktok#211]
**Name:** Beta Lin
**Email:** sb2828sb@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/beta-lin-b14020139/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/60283086/126432492-ac22700b-7179-4eb2-aeb6-35a81ef46220.png)

![image](https://user-images.githubusercontent.com/60283086/126432876-ca227c8d-d8ce-4bc4-a30a-0b8280139014.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/60283086/126433461-dda9478c-8b91-4170-b76a-8b2d9c361138.png)

**Comment by HadesArchitect** [comment]
Hey **Beta Lin**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/gUZ5BhAoQh6FVG7_E10TeA
