### ISSUE TITLE
[HW] Tan Shao Yun

### ISSUE THREAD

**Issue by shaocloud** [datastaxdevs/workshop-social-media-tiktok#212]
**Name:** Tan Shao Yun
**Email:** shao.cloud@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tanshaoyun/

Attach the homework step I screenshots below:
-----------------------------------------
![ss_1](https://user-images.githubusercontent.com/14543156/126436751-a7145540-7cca-4208-a73a-a9e4fc884b9c.png)

(step 2 was taking some time so here's step 1 only :( )

**Comment by HadesArchitect** [comment]
Hey **Tan Shao Yun**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/r-BOkdTNSLGjQblWP98Vsw
