### ISSUE TITLE
[HW] Assignment 2 - TikTok Clone

### ISSUE THREAD

**Issue by brucew2099** [datastaxdevs/workshop-social-media-tiktok#213]
**Name:** Alan Kwok
**Email:** alankwok1@gmail.com
**Linkedin Profile:* https://www.linkedin.com/in/alan-k-0593a0109/

Attach the homework step I screenshots below:
-----------------------------------------

![Assign_2_TikTok_App_UI](https://user-images.githubusercontent.com/14793800/126435900-d2d03faf-d525-4913-af3d-547f69c96f55.png)

![Assign_2_TikTok_App_Post](https://user-images.githubusercontent.com/14793800/126435874-5df8e4d9-d183-4fde-a9e2-4c1a01362e6e.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Assign_2_TikTok_App_Swagger_Edit_1](https://user-images.githubusercontent.com/14793800/126436648-2adf2dfb-3f63-49c4-9f58-3b6486babb4c.png)

![Assign_2_TikTok_App_Swagger_Edit_2](https://user-images.githubusercontent.com/14793800/126436827-99f60d3b-8182-4d1b-a1c5-56e36af45d9e.png)

![Assign_2_TikTok_App_Swagger_Edit_3](https://user-images.githubusercontent.com/14793800/126435970-e095f2c6-028f-49c1-b1dc-417de83fa075.png)

Extra Credit:
-----------------------------------------

![Assign_2_TikTok_App_Extra](https://user-images.githubusercontent.com/14793800/126436008-f0fd1026-d729-496c-bd89-26999db354c9.png)

Website URL:       https://angry-shannon-cd7588.netlify.app

**Comment by HadesArchitect** [comment]
Hey **Alan Kwok**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/EUN-kTCmTtyQDby3eKp0hQ
