### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by roeldcrodua** [datastaxdevs/workshop-social-media-tiktok#214]
**Name:** Roel Crodua
**Email:** roel.crodua@yahoo.com
**Linkedin Profile:** <https://www.linkedin.com/in/roeldcrodua/

Attach the homework step I screenshots below:
-----------------------------------------

![Capture7](https://user-images.githubusercontent.com/65931708/126439302-00fe6dae-8e8e-4d62-b811-e7e9e72ee084.JPG)
>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Roel Crodua**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/5RdNIB60TceH_cups7FqVw
