### ISSUE TITLE
[HW] Fayiz Asd

### ISSUE THREAD

**Issue by fayzasd** [datastaxdevs/workshop-social-media-tiktok#215]
**Name:** Fayiz Asad
**Email:** fayizasad@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/fayizasad/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/26874300/126460111-20a578bd-4fda-40f1-bbb0-2a38468b983e.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **Fayiz Asad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/R8EJnEZBTQyVYp8clPa5YA

**Comment by SonicDMG** [comment]
Also, I had to remove some images because they contained your Astra token. Please delete your token from the Astra UI so we don't have any security issues. Thank you.

**Comment by fayzasd** [comment]
Hi,

Thank you for the badge and about the token, I've deleted and reinitialized it from the UI as well.
