### ISSUE TITLE
[HW] Felipe Rojas

### ISSUE THREAD

**Issue by chekobil** [datastaxdevs/workshop-social-media-tiktok#216]
**Name:** Felipe Rojas
**Email:** felipe.arg@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/felipe-arg/

### working on Gitpod with "netlify dev"
<img width="1174" alt="Captura de pantalla 2021-07-21 a las 11 41 59" src="https://user-images.githubusercontent.com/484052/126469354-a18214db-c112-4110-9583-87c805e5795b.png">

### working on [Netlify](https://affectionate-feynman-3fc1a9.netlify.app/#/)
<img width="1174" alt="Captura de pantalla 2021-07-21 a las 11 26 45" src="https://user-images.githubusercontent.com/484052/126469445-93d4cc58-9afd-47f9-a77c-f97d6449afa3.png">

**Comment by HadesArchitect** [comment]
Hey **Felipe Rojas**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DW56-16XRM2mg6oU-abtEg
