### ISSUE TITLE
[HW] Jacosta von Achten

### ISSUE THREAD

**Issue by Nethcanov** [datastaxdevs/workshop-social-media-tiktok#217]
**Name:** Jacosta von Achten
**Email:** nethcanov@yahoo.co.uk
**Linkedin Profile:** https://www.linkedin.com/in/jacosta-v-4962261a1/

Attach the homework step I screenshots below:
-----------------------------------------
![Screen Shot 2021-07-15 at 08 19 57](https://user-images.githubusercontent.com/67161645/126484676-44ae70e1-8ebf-483e-9813-f9c4240cc265.png)
![Screen Shot 2021-07-21 at 09 06 32](https://user-images.githubusercontent.com/67161645/126484714-6765d2c5-d698-4551-a86e-250aea855de6.png)
![Screen Shot 2021-07-21 at 09 16 17](https://user-images.githubusercontent.com/67161645/126484726-1f96572a-1b3f-4e17-aa55-967b96a09d96.png)
![Screen Shot 2021-07-21 at 09 17 06](https://user-images.githubusercontent.com/67161645/126484732-63bcd6b3-4e9d-4d4c-adb5-5d8c8fb8d61e.png)
![Screen Shot 2021-07-21 at 11 50 47](https://user-images.githubusercontent.com/67161645/126484742-e2e87bf3-3813-4094-b1de-971015ed16f1.png)
![Screen Shot 2021-07-21 at 12 41 53](https://user-images.githubusercontent.com/67161645/126484833-801127ed-6dfc-462d-b245-0d9cc737cbe3.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screen Shot 2021-07-21 at 12 25 49](https://user-images.githubusercontent.com/67161645/126484756-717aa76e-0cc7-4a24-a8fc-8a9df768a39b.png)
![Screen Shot 2021-07-21 at 12 33 16](https://user-images.githubusercontent.com/67161645/126484795-df4ff52d-1eef-485c-a69e-27bc0ad1cf82.png)
![Screen Shot 2021-07-21 at 12 37 46](https://user-images.githubusercontent.com/67161645/126484819-26035fe3-7aa7-4d17-b9a2-1412679b4b0a.png)

**Comment by Nethcanov** [comment]
I haven't had time to follow Ania's tutorial but would love to do this in the future.

**Comment by SonicDMG** [comment]
Hi Jacosta. I see your local TikTok app is working, but when I checked the instance deployed up on netlify I just get a blank page with the TikTok header. That is usually do the env vars not being configured properly. Please provide a screen of the working app deployed up on netlify. Thank you. :)
