### ISSUE TITLE
[HW] Paul McNally

### ISSUE THREAD

**Issue by pmctrek** [datastaxdevs/workshop-social-media-tiktok#218]
**Name:** Paul McNally
**Email:** pmctrek@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/paul-mc-nally/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1712" alt="Pmctrek_Gitpod_2021-07-21 02-19-35" src="https://user-images.githubusercontent.com/33106760/126456085-f80a98f3-bb00-4912-8a8d-ee9429f598d8.png">

  
Attach the homework step II screenshots below:
-----------------------------------------

<img width="1419" alt="pmctrek_Swagger_2021-07-21 02-37-11" src="https://user-images.githubusercontent.com/33106760/126458583-57288a54-e35e-4218-b23b-528e015e9044.png">

**Comment by HadesArchitect** [comment]
Hey **Paul McNally**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/bCKCNrC2SkO73QB-4wnIFQ
