### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by SamDaQueen** [datastaxdevs/workshop-social-media-tiktok#22]
**Name:** Samreen Reyaz A.
**Email:** samreenreyaz@outlook.com
**Linkedin Profile:** https://www.linkedin.com/in/samreen-reyaz/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![WebsiteDepoyed](https://user-images.githubusercontent.com/37181109/119792587-6ffb4280-bef3-11eb-8ac6-dab20e7c675a.png)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you were successful in deploying the app, thanks Samreen!

**Comment by SonicDMG** [comment]
Here's your badge. Thank you again for joining us. https://api.badgr.io/public/assertions/vgIKi_XHT-inHelrZ2cHQA?identity__email=samreenreyaz%40outlook.com

**Comment by SamDaQueen** [comment]
Thank you for the amazing session!

--

Thanks and regards,

Samreen Reyaz

Phone: +91-99200-12297

LinkedIn: linkedin.com/in/samreen-reyaz/<http://linkedin.com/in/samreen-reyaz/>

________________________________
