### ISSUE TITLE
[HW] KRITI NAINWAL

### ISSUE THREAD

**Issue by Kriti954** [datastaxdevs/workshop-social-media-tiktok#220]
**Name:** Kriti Nainwal
**Email:** kriti.nainwal@gmail.com
**Linkedin Profile:** www.linkedin.com/in/kriti-n-878152217

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![deploy](https://user-images.githubusercontent.com/77835386/126494045-e3ea81e4-4c52-4f51-8590-a1b92ea17cbd.PNG)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **Kriti Nainwal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KY4gp1VgRbOSq5lsJmbb0Q

**Comment by SonicDMG** [comment]
Also, I had to remove some images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues. :)
