### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by louhenheimo** [datastaxdevs/workshop-social-media-tiktok#221]
**Name:** Petri Louhenheimo
**Email:** petril@iki.fi
**Linkedin Profile:** https://www.linkedin.com/in/louhenheimo/

Attach the homework step I screenshots below:
-----------------------------------------

![W2-1-Inked7RTbNQEfB0_LI](https://user-images.githubusercontent.com/1541962/126498728-95ae4c5c-2bfa-467b-b3b5-135b4c07d0bc.jpg)
![w2-2-Inked6K1zfxsi1I_LI](https://user-images.githubusercontent.com/1541962/126498762-70d43a0d-0f83-4c08-a154-4ed6c7a9a20a.jpg)
![W2-3-InkedX08OxfArKm_LI](https://user-images.githubusercontent.com/1541962/126498774-9dcbc906-9773-4eb6-bfc1-13081d968eb0.jpg)
![W2-4-InkedQ6j0CWYln2_LI](https://user-images.githubusercontent.com/1541962/126498795-b1cad4e9-9872-463c-91c7-fa24ddb2991f.jpg)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Petri Louhenheimo**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/doflnXBHTCWWfUQrCwrCjQ
