### ISSUE TITLE
[HW] Ste Bat

### ISSUE THREAD

**Issue by stebat69** [datastaxdevs/workshop-social-media-tiktok#223]
**Name:** ste bat
**Email:** xyy669@gmail.com
**Linkedin Profile:** linkedin.com/in/stefano-battistella-54229a217

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/29290360/126506411-5c6148c5-06bd-4ee8-b572-452a9363e2ca.png)
![image](https://user-images.githubusercontent.com/29290360/126506542-27ababe5-ffa0-430c-9341-4bb70d33aad2.png)
![image](https://user-images.githubusercontent.com/29290360/126506628-95d88ed5-9f07-4a88-8026-4adcd71920bf.png)
![image](https://user-images.githubusercontent.com/29290360/126506774-c0bb97b5-26dd-438b-ad31-676d6d3eb831.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **ste bat**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8rAKh2SsSAuUA16aZxlPIQ
