### ISSUE TITLE
[HW-2 : Tik Tok clone in React] Dinesh G 

### ISSUE THREAD

**Issue by greatdinesh** [datastaxdevs/workshop-social-media-tiktok#224]
Name: Dinesh Gnanamurthy
Email: dinesh.g@outlook.com
Linkedin Profile: www.linkedin.com/in/dinesh-g-software-engineer 

Attach the homework step I screenshots below:
-----------------------------------------

![1](https://user-images.githubusercontent.com/43313555/126507349-f58ff0bb-203e-4612-a516-928d34b37032.jpg)

![2](https://user-images.githubusercontent.com/43313555/126507389-f591b21b-a7c9-4e39-90ea-3a4e7d8edf1b.jpg)

Attach the homework step II screenshots below:
-----------------------------------------

![4](https://user-images.githubusercontent.com/43313555/126507514-3d9b3cc2-bb64-4105-a700-f7172059f7e6.jpg)

![3](https://user-images.githubusercontent.com/43313555/126507466-c5306bb7-3f6e-43d0-9cbb-252f1d51e2e6.jpg)

![5](https://user-images.githubusercontent.com/43313555/126507764-00e7a22e-868e-4bfe-aad2-686cee6a12d8.jpg)

**Comment by HadesArchitect** [comment]
Hey **Dinesh Gnanamurthy**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/w28_y_GEQL6k9tIbjRmfTA
