### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by KyronFeast** [datastaxdevs/workshop-social-media-tiktok#225]
**Name:** Thomas J. Short
**Email:** thomasshort1984@gmail.com
**Linkedin Profile:** <www.linkedin.com/in/thomas-james-short>

I will do better to follow the screen snips alongside the steps. I have followed Ania's video but I am afraid it is not complete but I have sent what I have. If you have any suggestions to improve my format please let me know. 

Thanks,
 Thomas J. Short

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![Step1_create_astradb](https://user-images.githubusercontent.com/42007448/126530642-8a73d8bc-9faa-4034-9d6d-6e8fffbe09c2.PNG)
![generated_token](https://user-images.githubusercontent.com/42007448/126530792-b03e7f2f-e9e7-4e4d-b2c2-6ced8b37a5e3.PNG)
![step3_acess_repository](https://user-images.githubusercontent.com/42007448/126530864-6f2155cc-281a-4001-8f55-19e305e65048.PNG)
![generated_token](https://user-images.githubusercontent.com/42007448/126530885-93643755-b36a-4f43-b87b-60aaf8bd75bf.PNG)
![step5_Gitpod](https://user-images.githubusercontent.com/42007448/126530900-521962ca-c50b-4409-93b3-fcb4b0302131.PNG)
![deployment_proof](https://user-images.githubusercontent.com/42007448/126530920-db541414-ce64-4832-907b-7e1871a7bf63.PNG)
![Working_Site](https://user-images.githubusercontent.com/42007448/126530928-f271ac11-2e98-4758-8d26-4e7fa4bf5318.PNG)
![deploy_to_netlify](https://user-images.githubusercontent.com/42007448/126530946-99a85f63-de60-4fa7-804b-5357a6f11a1f.PNG)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
![1_AddData](https://user-images.githubusercontent.com/42007448/126530999-dfbb2fa7-7332-4104-8b60-c4dc78660c9d.PNG)

![image](https://user-images.githubusercontent.com/42007448/126531240-d0cdd6ed-9cda-47bf-9d85-9cb2b2fc05ce.png)
![Capture](https://user-images.githubusercontent.com/42007448/126531704-b9aa7fcb-310c-4faa-ae87-e1f5f33213bc.PNG)
![Capture2](https://user-images.githubusercontent.com/42007448/126531715-33a4e5c9-39cf-405a-9ee5-2bd67fbdd7df.PNG)
![Capture3](https://user-images.githubusercontent.com/42007448/126531726-493fbcdd-6694-49c2-9c10-50a25ea6bcea.PNG)

**Comment by SonicDMG** [comment]
You did great. Nice job on getting into the Ania video. It definitely ups the coding level, but fun to go for it.

**Comment by HadesArchitect** [comment]
Hey **Thomas J. Short**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aM2UyVK0T-68ykHZ-sRbDw
