### ISSUE TITLE
[HW] Daniel Molina

### ISSUE THREAD

**Issue by Molina-Daniel** [datastaxdevs/workshop-social-media-tiktok#227]
**Name:** Daniel Molina
**Email:** dmolcap@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/daniel-molina-developer/

Attach the homework step I screenshots below:
-----------------------------------------
Login or Register to Astra DB and create database

![1  Login or Register to Astra DB and create database](https://user-images.githubusercontent.com/46754672/126533549-942d0011-0221-4247-ab23-f4ce46a91798.JPG)

Deploy to Netlify

![2  Deploy to Netlify](https://user-images.githubusercontent.com/46754672/126533630-21f94c73-f38c-4697-a601-7e281d23acab.JPG)

Access YOUR GitHub repository

![3  Access YOUR GitHub repository](https://user-images.githubusercontent.com/46754672/126533645-d09f097f-6a05-4b4d-8851-31b15d6d8fc3.JPG)

Launch GitPod IDE

![4  Launch GitPod IDE](https://user-images.githubusercontent.com/46754672/126533656-ca25732c-d500-499f-a218-dcbe6e3d4560.JPG)

Launch your app

![8  Launch your app](https://user-images.githubusercontent.com/46754672/126533665-d85bf780-acd4-440c-bcd4-f1ca975d7e79.JPG)

Deploy to production

![10  Deploy to production](https://user-images.githubusercontent.com/46754672/126533697-c08eb0f4-b7c9-48f9-88e5-a09def811d84.JPG)

Deploy to production 2

![10  Deploy to production 2](https://user-images.githubusercontent.com/46754672/126533682-b5fab42b-8026-44d5-a361-a560dc8b197e.JPG)

  
Attach the homework step II screenshots below:
-----------------------------------------

Connecting the Database

![11  Connecting the Database](https://user-images.githubusercontent.com/46754672/126533720-9e52d048-5c70-444f-bc48-ee1af069a657.JPG)

Document API

![11  Document API](https://user-images.githubusercontent.com/46754672/126533733-bd46e88f-f1e2-4e79-bc36-30e568ada29f.JPG)

Serverless configuration

![15  Serverless configuration](https://user-images.githubusercontent.com/46754672/126533758-5f2978a8-5532-4944-92b9-e4d36d1536a8.JPG)

Serverless configuration 2

![15  Serverless configuration 2](https://user-images.githubusercontent.com/46754672/126533745-44fc40e7-980a-48d6-bf02-835b3baa1509.JPG)

I had no time to create the app myself with the Ania video but I will do it for sure, it's super interesting!!
Thank you for the hard work guys!

**Comment by HadesArchitect** [comment]
Hey **Daniel Molina**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/kWM_01c8Q6O0avVUCqQfDg

**Comment by SonicDMG** [comment]
Nice documentation as well. :D
