### ISSUE TITLE
[HW] TikTok Clone

### ISSUE THREAD

**Issue by NAMANBHATEJA57** [datastaxdevs/workshop-social-media-tiktok#228]
**Name:** NAMAN BHATEJA
**Email:** namanbhatejawork@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/naman-bhateja-018392171/

screenshots:-
![1](https://user-images.githubusercontent.com/67056038/126540666-3fa4ddc5-ac56-401d-b9c5-51c0f2a68521.JPG)
![3](https://user-images.githubusercontent.com/67056038/126540529-cead4631-5c55-4f14-a9cf-f0854bca3a90.JPG)
![4](https://user-images.githubusercontent.com/67056038/126540532-52fd0d63-e8e5-4a68-bfd8-7e50719114df.JPG)
![5](https://user-images.githubusercontent.com/67056038/126540534-5e337dc0-f230-45c6-b7af-7d33a99fc7eb.JPG)
![6](https://user-images.githubusercontent.com/67056038/126540546-583f01fa-ef92-400c-ae5f-dac9a531bc3f.JPG)
![7](https://user-images.githubusercontent.com/67056038/126540548-1679ce4e-03e1-404b-bde1-d08e336015cf.JPG)
![8](https://user-images.githubusercontent.com/67056038/126540551-688de31e-7b38-47f0-8c17-35ce66c8d526.JPG)
![9](https://user-images.githubusercontent.com/67056038/126540555-bf08abe0-b03c-4e48-89c7-a2da8c8c8372.JPG)
![10](https://user-images.githubusercontent.com/67056038/126540559-e983a1bc-5ae5-435a-a1f8-2acbb4d941f8.JPG)
![11](https://user-images.githubusercontent.com/67056038/126540561-025aa01f-8a2f-4a4b-a2bf-d15b57e7c560.JPG)
![12](https://user-images.githubusercontent.com/67056038/126540564-0e21ffd5-bafc-4a23-81f3-f73e71712894.JPG)

**Comment by HadesArchitect** [comment]
Hey **NAMAN BHATEJA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/PCc1nyuiRO6GO4n6piE8Jg
