### ISSUE TITLE
[HW] Kumari Anushka

### ISSUE THREAD

**Issue by anuxoxo** [datastaxdevs/workshop-social-media-tiktok#229]
**Name:** Kumari Anushka
**Email:** anushka.ak14@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kumari-anushka-1410/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="960" alt="1" src="https://user-images.githubusercontent.com/63368506/126544096-1ac7dba1-cbe7-4604-94cb-660ac44eebb9.png">
<img width="960" alt="3" src="https://user-images.githubusercontent.com/63368506/126544119-f26907df-2845-4bfc-b8a9-df488af54c23.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/63368506/126544153-3c3ebe20-07e8-4e8f-94f2-958bd4f1bb03.png">

  
Attach the homework step II screenshots below:
-----------------------------------------

<img width="955" alt="anu" src="https://user-images.githubusercontent.com/63368506/126547562-941a0803-1dcc-4aab-9a5f-68565c912348.png">

**Comment by HadesArchitect** [comment]
Hey **Kumari Anushka**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/c1iqvQnnS3ezvkY6xm9YbA
