### ISSUE TITLE
[HW] <FARSANA>

### ISSUE THREAD

**Issue by Farz10** [datastaxdevs/workshop-social-media-tiktok#23]
**Name:** <FARSANA>
**Email:** <farzsadath8@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/farsana098/>

Attach the homework step I screenshots below:
-----------------------------------------
-- images removed by team --

![Screenshot (5)](https://user-images.githubusercontent.com/57973664/119792622-77225080-bef3-11eb-845e-0d930b443d4d.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot (18)](https://user-images.githubusercontent.com/57973664/119793554-53133f00-bef4-11eb-888b-6660f306c6e2.png)

-- images removed by team --

**Comment by RyanWelford** [comment]
Farsana, were you able to deploy on Netlify? I don't see a screenshot of the Netlify site.

**Comment by SonicDMG** [comment]
Actually, @RyanWelford, I see the netlify version deployed above embedded in GitPod.

**Comment by SonicDMG** [comment]
Nice job Farsana, here's your badge. https://api.badgr.io/public/assertions/ywnnL92PQgOFdeskXm2SWA?identity__email=farzsadath8%40gmail.com

**Comment by Farzana10** [comment]
Thank you

I apologise for not being able to reply to your previous email
