### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by NancyJaneBullis** [datastaxdevs/workshop-social-media-tiktok#231]
**Name:** Nancy Bullis
**Email:** nancybullis3@gmail.com
**Linkedin Profile:** www.linkedin.com/in/nancyjanebullis

Attach the homework step I screenshots below:
-----------------------------------------
Week 2

![image](https://user-images.githubusercontent.com/83715570/126580482-21987cbd-53b6-48c4-94bf-4c5b82fa8d61.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

Screenshot of Tutorial to follow when complete - project currently in progress

**Comment by HadesArchitect** [comment]
Hey **Nancy Bullis**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Sauv9wYSQG6Qwtm_08Bc0w
