### ISSUE TITLE
[HW] Mohd Azmil Azan Jani

### ISSUE THREAD

**Issue by mohdazmilazanjani** [datastaxdevs/workshop-social-media-tiktok#232]
Name: Mohammad Azmil Bin Azan Jani
Email: mohdazmil.azanjani@gmail.com
Linkedin Profile: www.linkedin.com/in/mohammad-azmil-azan-jani-87a14aa4

AstraDB & Netlify Configuration
![image](https://user-images.githubusercontent.com/20120094/126606409-a1618e0b-d566-4b68-b5e0-614f33eee736.png)

Tik Tok Clone - Netlify    https://roundcircle.netlify.app/#/
![image](https://user-images.githubusercontent.com/20120094/126606631-38dc87a2-e6fb-49ab-83dd-7e9ad74aa9a0.png)
![image](https://user-images.githubusercontent.com/20120094/126606720-cdbb1046-cd83-47ca-9f9f-6975cc302e6e.png)

**Comment by HadesArchitect** [comment]
Hey **Mohammad Azmil Bin Azan Jani**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WOhYps13S9avC8X8JKg9WQ
