### ISSUE TITLE
[HW] Jacosta von Achten

### ISSUE THREAD

**Issue by Nethcanov** [datastaxdevs/workshop-social-media-tiktok#233]
**Name:** Jacosta von Achten
**Email:** nethcanov@yahoo.co.uk
**Linkedin Profile:** https://www.linkedin.com/in/jacosta-v-4962261a1/

Attach the homework step I screenshots below:
-----------------------------------------

![Screen Shot 2021-07-15 at 08 19 57](https://user-images.githubusercontent.com/67161645/126613644-f6cb55b7-5fca-4ec0-85ed-9588c354ff38.png)
![Screen Shot 2021-07-21 at 09 06 32](https://user-images.githubusercontent.com/67161645/126613667-7d7f0ae5-fba0-4b92-8ea2-7da07fe71d1e.png)
![Screen Shot 2021-07-21 at 09 16 17](https://user-images.githubusercontent.com/67161645/126613691-51a489de-3503-4b23-965c-cd85d7539283.png)
![Screen Shot 2021-07-21 at 09 17 06](https://user-images.githubusercontent.com/67161645/126613704-39f36a3d-0eb6-4dcd-9b42-032a21ad3cdc.png)
![Screen Shot 2021-07-21 at 11 50 47](https://user-images.githubusercontent.com/67161645/126613715-ecf24023-06b5-43c1-b910-44b5efb87172.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screen Shot 2021-07-21 at 12 25 49](https://user-images.githubusercontent.com/67161645/126613728-b1ce2d4d-0a47-44d7-a7e2-25c4686861a6.png)
![Screen Shot 2021-07-21 at 12 33 16](https://user-images.githubusercontent.com/67161645/126613758-5b68fc67-ed30-42d9-a654-35b940b363d6.png)
![Screen Shot 2021-07-21 at 12 37 46](https://user-images.githubusercontent.com/67161645/126613792-a827bbd3-a786-491e-8e14-77f1a59fcf94.png)
![Screen Shot 2021-07-21 at 12 59 46](https://user-images.githubusercontent.com/67161645/126613848-81ba6813-5c66-4015-b263-79d4af4f19de.png)
![Screen Shot 2021-07-22 at 09 45 29](https://user-images.githubusercontent.com/67161645/126613866-0a1d9c23-a8ff-4c3a-ad75-01a891042b4b.png)
![Screen Shot 2021-07-22 at 09 48 27](https://user-images.githubusercontent.com/67161645/126613877-6aeab8a8-1e8f-4b8f-835f-9ba15cf26db1.png)
![Screen Shot 2021-07-22 at 09 50 35](https://user-images.githubusercontent.com/67161645/126613891-29e02b80-4178-4961-9df6-251dbea1f567.png)

**Comment by HadesArchitect** [comment]
Hey **Jacosta von Achten**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/LIFVBEhIRjOgj_CdDXth_Q
