### ISSUE TITLE
[HW] Devansh

### ISSUE THREAD

**Issue by Ghost1129** [datastaxdevs/workshop-social-media-tiktok#234]
Name: Devansh Lodhi
Email: Devansh1129@outlook.com
Linkedin Profile: https://www.linkedin.com/in/devansh-l-6911bbaa/

<SCREENSHOTS>
  
<img width="1280" alt="s1" src="https://user-images.githubusercontent.com/67116890/126617991-8ec69337-61fd-49f4-9c11-ecb2a9e22137.png">
<img width="1280" alt="s2" src="https://user-images.githubusercontent.com/67116890/126618012-c868f421-5fc2-42af-8748-d31f9a2d18f9.png">
<img width="1264" alt="s3" src="https://user-images.githubusercontent.com/67116890/126618022-6a456b16-93c9-417b-a7e7-d4ca44018879.png">
<img width="1269" alt="s4" src="https://user-images.githubusercontent.com/67116890/126618030-7cf1264a-818e-400b-967a-dcdf7109cc9a.png">

**Comment by HadesArchitect** [comment]
Hey **Devansh Lodhi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/bIq9m8K1TqWFFaneJ49xjQ
