### ISSUE TITLE
[HW] Nupur Neogi

### ISSUE THREAD

**Issue by nupurndas** [datastaxdevs/workshop-social-media-tiktok#235]
**Name:** Nupur Neogi
**Email:** nupur_n_das@yahoo.co.in
**Linkedin Profile:** www.linkedin.com/in/nupur-d-3222a78

![1](https://user-images.githubusercontent.com/40590262/126617907-302ae931-61af-46b2-a6ce-ffb05f9d864c.png)
![2a](https://user-images.githubusercontent.com/40590262/126617912-7d0cc385-833f-474c-976f-ae965b2c8410.png)
![build complete](https://user-images.githubusercontent.com/40590262/126618051-36371320-4b89-4db1-8497-d44be43faa33.png)
![netlifly cli](https://user-images.githubusercontent.com/40590262/126618083-7cf7897d-2a04-4a90-913a-16f516d2d4f2.png)
![token generation](https://user-images.githubusercontent.com/40590262/126618139-9bbae58e-a6c9-4949-8215-26febbf0d0cd.png)
![netlifly link](https://user-images.githubusercontent.com/40590262/126618186-513e5a18-f887-4fc9-b781-8913ed65826a.png)
![netlifly logged in 9 step](https://user-images.githubusercontent.com/40590262/126618197-3a3b844e-d455-4a96-b8d0-f694e914a65b.png)
![netlifly token last steps](https://user-images.githubusercontent.com/40590262/126618254-6e14d712-2488-4d37-89b7-c43cd4a1c630.png)
![site deploy in progress](https://user-images.githubusercontent.com/40590262/126618264-2b6845d3-cbfd-49e2-b2a4-f14815d2d24f.png)
![site deployed](https://user-images.githubusercontent.com/40590262/126618267-5cdd864b-7a53-4043-a6fe-e5bdbcaf2e0a.png)
![last page](https://user-images.githubusercontent.com/40590262/126618294-2c19a896-3967-4aa0-bef9-2b27db640522.png)

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Nupur Neogi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1IYkkztpTEGa5PziK1MDmA
