### ISSUE TITLE
[HW] Rebecca Zee

### ISSUE THREAD

**Issue by rebeccazee** [datastaxdevs/workshop-social-media-tiktok#237]
**Name:** Rebecca Zee
**Email:** ryz283@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rebecca-zee-677761117/

Attach the homework step I screenshots below:
-----------------------------------------

![Part 1 Step 1 - AstraDBCreation](https://user-images.githubusercontent.com/24459985/126594692-737af1d3-e7da-4dfb-806d-a4363545f5a8.png)
![Part 1 Step 2 - DeployToNetlify](https://user-images.githubusercontent.com/24459985/126594693-fdabd9a2-d0a4-4640-86a6-cd30df144178.png)
![Part 1 Step 3 - GithubRepositoryAccess](https://user-images.githubusercontent.com/24459985/126594694-2cd1a555-d812-478a-98de-ae64ae9c6be3.png)
![Part 1 Step 8 - AppLauch](https://user-images.githubusercontent.com/24459985/126594695-9bbcb05f-8864-4f1b-b737-41aa7ab0ed5d.png)
![Part 1 Step 10 - DeployedNetlifyApp](https://user-images.githubusercontent.com/24459985/126594697-6cbd6c46-a226-4346-b70c-a006ba699f9f.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

![Part 2 Step 11 - SwaggerUI - Get](https://user-images.githubusercontent.com/24459985/126594766-f3f74e50-edd0-409d-b9cc-614895a07f27.png)
![Part 2 Step 14 - SwaggerUI - Find](https://user-images.githubusercontent.com/24459985/126594767-a1c181d2-4782-4cd1-b3b7-691661b72d3d.png)

**Comment by HadesArchitect** [comment]
Hey **Rebecca Zee**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KHP-FgCwTv2Psb1cPKMB-Q
