### ISSUE TITLE
[HW] <Jack Praveen Raj Ilango>

### ISSUE THREAD

**Issue by jackpraveenraj** [datastaxdevs/workshop-social-media-tiktok#239]
**Name:** <Jack Praveen Raj Ilango>Jack Praveen Raj Ilango
**Email:** jackpraveenraj.work@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/jack-praveen-raj-ilango/>

<SCREENSHOTS>

  ![SS1](https://user-images.githubusercontent.com/74396218/126673365-6aaf92d7-275f-4ee2-bc24-36d5f529d7fc.PNG)
![SS2](https://user-images.githubusercontent.com/74396218/126673373-dc550749-157d-4d65-b081-5352bd7a0556.PNG)
![SS3](https://user-images.githubusercontent.com/74396218/126673377-4e1f20c3-0ef9-4b35-9edb-b5d0dd5e8b48.PNG)
![SS4](https://user-images.githubusercontent.com/74396218/126673379-e1e76d73-1bf8-42f1-95e6-8c3a06ccd145.PNG)

**Comment by HadesArchitect** [comment]
Hey **Jack Praveen Raj Ilango**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/Z6KP8cuFShGrmwEKv0_6WQ
