### ISSUE TITLE
[HW] NBAMj

### ISSUE THREAD

**Issue by NBAMj** [datastaxdevs/workshop-social-media-tiktok#24]
**Name:** NBAMj
**Email:** ***@gmail.com
**Linkedin Profile:** 

Attach the homework step I screenshots below:
-----------------------------------------

* Deployed and running from `production` env:
![Screenshot 2021-05-27 112539](https://user-images.githubusercontent.com/3479105/119792524-6ddab900-bede-11eb-8434-c7e5b359e056.png)
-- images removed by team --

  
Attach the homework step II screenshots below:
-----------------------------------------
* Connect to `collection` api to get the collections created in the db. Use the required `token` and the namespace specified in the lab in order to validate against the API.
-- images removed by team --

* Result returned from the backend
-- images removed by team --

* Searching for a document in a collection:
-- images removed by team --

**Comment by RyanWelford** [comment]
Awesome! Thanks for the well documented results, Mujib!

**Comment by SonicDMG** [comment]
Yes, agreed, thanks for your submission. Here's your badge -> https://api.badgr.io/public/assertions/oa9hsxB-RY22l4w_p88m4w?identity__email=mujib.bahadiri%40gmail.com

**Comment by NBAMj** [comment]
Thanks guys for the well organized workshop 👍
