### ISSUE TITLE
[HW] Rounak Tadvi

### ISSUE THREAD

**Issue by RounakTadvi** [datastaxdevs/workshop-social-media-tiktok#240]
**Name:** Rounak Tadvi
**Email:** rounaktadvi786@gmail.com
**Linkedin Profile:** www.linkedin.com/in/rounaktadvi

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot 2021-07-23 at 2 56 04 PM](https://user-images.githubusercontent.com/38634459/126781558-9be8bcb5-14c3-41a3-9bfa-c2ef340b04e1.png)
![Screenshot 2021-07-23 at 5 44 06 PM](https://user-images.githubusercontent.com/38634459/126781570-aa923644-7818-4a2b-818d-2b5280a648a5.png)
![Screenshot 2021-07-23 at 5 51 31 PM](https://user-images.githubusercontent.com/38634459/126781574-b7e4dc0f-4a9b-473a-acf0-edeeb4a97f9a.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot 2021-07-23 at 5 57 33 PM](https://user-images.githubusercontent.com/38634459/126781608-22f394d3-06dd-4a41-b43e-7b3ffc8ccdab.png)
![Screenshot 2021-07-23 at 5 52 14 PM](https://user-images.githubusercontent.com/38634459/126781614-0ad4cb27-d52f-4550-93f1-5c1d8ce44606.png)

**Comment by HadesArchitect** [comment]
Hey **Rounak Tadvi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/0smUHnbtRGiAGNFPCjxIUA
