### ISSUE TITLE
[HW] AASHRITH SHANKAR J

### ISSUE THREAD

**Issue by Aashriths** [datastaxdevs/workshop-social-media-tiktok#241]
**Name:** J.Aashrith Shankar
**Email:** aashriths007@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------
[1627055681503.pdf](https://github.com/datastaxdevs/appdev-week2-tiktok/files/6869919/1627055681503.pdf)
![screenshot](https://user-images.githubusercontent.com/87776104/126809781-1c389e9b-db4f-4580-999b-05ac17e25330.png)

Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **J.Aashrith Shankar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4s39mGxHTGmWNOpPCl3aDA

**Comment by SonicDMG** [comment]
Also, I removed your 2.pdf because it contained some images with your Astra token. Please delete your token via the Astra UI to ensure no security issues.

**Comment by Aashriths** [comment]
Can u evaluate my week 1 activity. I submitted 2 days back.
