### ISSUE TITLE
[HW] S PADMANABAN

### ISSUE THREAD

**Issue by S-PADMANABAN-2001** [datastaxdevs/workshop-social-media-tiktok#242]
**Name:** S PADMANABAN
**Email:** sivapadmanaban2001@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/padmanaban-s-0211021b4/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot 2021-07-23 at 8 36 45 PM](https://user-images.githubusercontent.com/78414781/126817551-fa664390-eff4-4c5e-a3b3-a528113a2447.png)

https://user-images.githubusercontent.com/78414781/126817579-b03cb65e-2cd2-4c9f-ac21-b662714cb0b2.mov

**Comment by HadesArchitect** [comment]
Hey **S PADMANABAN**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1bKtLrA3QPmwWUvv75xrSw
