### ISSUE TITLE
[HW] Chris Armitage

### ISSUE THREAD

**Issue by chrisarmitage** [datastaxdevs/workshop-social-media-tiktok#245]
Name: Chris Armitage
Email: datastax@pieman.me.uk
Linkedin Profile: https://www.linkedin.com/in/chrisarmitage/

Attach the homework step I screenshots below:
-----------------------------------------

Running app: https://agitated-swartz-df40bd.netlify.app/#/

![W2 - DB entry](https://user-images.githubusercontent.com/195563/126861301-43f8b006-4fb3-4310-939e-a1bbacdd3ab4.JPG)
![W2 - Gitpod](https://user-images.githubusercontent.com/195563/126861363-ba611c24-3a50-40fc-a9b6-f7f9381bf410.JPG)
![W2 - Running app](https://user-images.githubusercontent.com/195563/126861373-5589fc76-5527-46b5-818a-707b8ceaf26e.JPG)

  
Attach the homework step II screenshots below:
-----------------------------------------

Still being worked through

**Comment by HadesArchitect** [comment]
Hey **Chris Armitage**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/B4FrABqAQtu-RP0ZXUD0vA
