### ISSUE TITLE
[tik tok clone app] swati gour

### ISSUE THREAD

**Issue by swatigour2000** [datastaxdevs/workshop-social-media-tiktok#246]
**Name:** swati gour
**Email:** gourdswati@gmail.com
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (11)](https://user-images.githubusercontent.com/72186365/126871502-90845316-2816-4143-9cb4-20f4b48360fc.png)
![Screenshot (12)](https://user-images.githubusercontent.com/72186365/126871523-3484c02f-473b-4d72-bc26-8681d92e21c1.png)
![Screenshot (13)](https://user-images.githubusercontent.com/72186365/126871543-efe5d4ed-ed47-4e2e-b83a-b90856f5992a.png)
![Screenshot (14)](https://user-images.githubusercontent.com/72186365/126871556-486f46dd-0627-439a-82e7-38db00858495.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (15)](https://user-images.githubusercontent.com/72186365/126871569-d1b9825c-a408-42db-92e6-4311643613dd.png)
![Screenshot (16)](https://user-images.githubusercontent.com/72186365/126871571-ce1fa484-0ffc-42c5-b63c-b7442adac748.png)
![Screenshot (17)](https://user-images.githubusercontent.com/72186365/126871585-034b9432-0d71-4a95-9094-85030bfb72e3.png)
![Screenshot (18)](https://user-images.githubusercontent.com/72186365/126871597-b95c1930-f8cc-4089-a81f-453a7a6225b8.png)

**Comment by HadesArchitect** [comment]
Hey **swati gour**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/eUdTgJITR-GFf5vjHHgwqQ
