### ISSUE TITLE
[TikTok Clone Workshop] <Bibhushan Karki>

### ISSUE THREAD

**Issue by BibhushanKarki** [datastaxdevs/workshop-social-media-tiktok#247]
**Name:** Bibhushan Karki
**Email:** bibhushan.karki11@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/bibhushan-karki-3184b013a/>
**Netlify Url:** <https://bibs-tiktok-clone.netlify.app/#/>

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (29)](https://user-images.githubusercontent.com/24572691/126877259-5bf0c412-9e17-4869-9e5b-f951ec4ddf69.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot (30)](https://user-images.githubusercontent.com/24572691/126877264-723ed11b-1235-477d-b159-1e14e16c7d0e.png)

-- image removed by team --

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Bibhushan Karki**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1jPkNl9RQ2aziupWp_tA3A

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.
