### ISSUE TITLE
[HW] Gökcan Çantalı

### ISSUE THREAD

**Issue by gokcantali** [datastaxdevs/workshop-social-media-tiktok#248]
**Name:** Gökcan Çantalı
**Email:** gokcantali@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/g%C3%B6kcan-%C3%A7antal%C4%B1-aa31319a/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot from 2021-07-24 16-59-17](https://user-images.githubusercontent.com/11981221/126882427-a7e3e62a-3192-40de-83a0-84c27a5d867d.png)

![Screenshot from 2021-07-24 17-01-03](https://user-images.githubusercontent.com/11981221/126882433-dfe657e7-a07f-4c31-af27-dd8cfdffe340.png)

![Screenshot from 2021-07-24 17-00-32](https://user-images.githubusercontent.com/11981221/126882438-0a6cdfb3-ae34-4302-bb8c-ca4bbeb1eb7f.png)

Attach the homework step II screenshots below:
-----------------------------------------
From Ania's Tutorial:

![Screenshot from 2021-07-24 22-05-24](https://user-images.githubusercontent.com/11981221/126882442-823ae54c-a499-41da-ac94-430e6bbc492a.png)

![Screenshot from 2021-07-25 01-21-59](https://user-images.githubusercontent.com/11981221/126882447-bd491c23-b2ee-4867-802d-bf0006f3cb05.png)

**Comment by HadesArchitect** [comment]
Hey **Gökcan Çantalı**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WCz4WGRHQ3-LydjYorh6jg
