### ISSUE TITLE
[HW] Joel Wenger

### ISSUE THREAD

**Issue by Oakman771** [datastaxdevs/workshop-social-media-tiktok#249]
**Name:** Joel Wenger
**Email:** snickersinderhose@gmail.com

Attach the homework step I screenshots below:
-----------------------------------------

![GitPodSC](https://user-images.githubusercontent.com/87374294/126901839-cf18ac29-33b0-4729-84bb-32a6764111fb.png)
![NetlifySC](https://user-images.githubusercontent.com/87374294/126901844-bb11b9fc-93e4-44a5-87ab-123e338b6af5.png)
![TikTokSC](https://user-images.githubusercontent.com/87374294/126901846-6fbba44c-6a16-4552-a739-4a1db0c33393.png)
![DBSC](https://user-images.githubusercontent.com/87374294/126901848-6f245a8c-8304-4519-b6bd-f939e6fae35f.png)

**Comment by HadesArchitect** [comment]
Hey **Joel Wenger**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DhrgEmVVRs-J4aGX2co1_Q
