### ISSUE TITLE
[HW] <Prathmesh Wavhal>

### ISSUE THREAD

**Issue by BlurryfaceP1** [datastaxdevs/workshop-social-media-tiktok#25]
**Name:** <Prathmesh Wavhal>
**Email:** <prathmeshwavhal@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/prathmesh-wavhal-39586319b/
![TIKTOK CLONE SS4](https://user-images.githubusercontent.com/23097791/119798339-adae9a00-bef8-11eb-950d-0b6f05460b77.png)
![TIKTOK CLONE SS](https://user-images.githubusercontent.com/23097791/119798340-aedfc700-bef8-11eb-8c71-32ea2b4ff9e0.png)
![TIKTOK CLONE SS1](https://user-images.githubusercontent.com/23097791/119798342-af785d80-bef8-11eb-8290-b98c467c499e.png)
![TIKTOK CLONE SS2](https://user-images.githubusercontent.com/23097791/119798343-af785d80-bef8-11eb-8dd0-176b3bd1738e.png)
-- images removed by team --

>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by BlurryfaceP1** [comment]
Not sure why name wouldn't show up, anyway it's Prathmesh Wavhal! Thank you

**Comment by RyanWelford** [comment]
Well done, Prathmesh! And thank you for the kind feedback!

**Comment by SonicDMG** [comment]
Thanks for posting your name as well. Good job and here's your badge -> https://api.badgr.io/public/assertions/HSXn5D4MQwiEsXHB1IWnmQ?identity__email=prathmeshwavhal%40gmail.com
