### ISSUE TITLE
[HW] Udiesha gautam

### ISSUE THREAD

**Issue by Udiesha** [datastaxdevs/workshop-social-media-tiktok#250]
![Screenshot (142)](https://user-images.githubusercontent.com/87614825/126902306-fafdc4aa-d78f-4c96-8e79-57e2a238d302.png)
Name:Udiesha gautam
Email:1112noni@gmail.com
Linkedin Profile:https://www.linkedin.com/in/udiesha-gautam-988908210

Attach the homework step I screenshots below:
![Screenshot (141)](https://user-images.githubusercontent.com/87614825/126901881-21a7fe32-d142-4681-a4d6-f9aabf4dc165.png)

-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot (138)](https://user-images.githubusercontent.com/87614825/126902170-7b1329ce-7c07-41e5-9d9d-8bba1f68bff5.png)
!
-- images removed by team --
![Screenshot (134)](https://user-images.githubusercontent.com/87614825/126902498-01c7a8a0-e913-4f1d-b859-2131facbb2e0.png)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Udiesha gautam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/04bZXw80RauACd258Y-Y1w

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.
