### ISSUE TITLE
[HW] Adesh Bhosale

### ISSUE THREAD

**Issue by adeshbx2** [datastaxdevs/workshop-social-media-tiktok#251]
**Name:** Adesh Bhosale
**Email:** adeshbx3@gmail.com / adeshbx2@gmail.com
**Linkedin Profile:** www.linkedin.com/in/adesh-bhosale-b0b344140

Attach the homework step I screenshots below:
-----------------------------------------

![Tiktok_astrdb_creation](https://user-images.githubusercontent.com/87820481/126903248-83845fec-d0bf-4f10-9003-eab0f4000772.PNG)
![deploy_netlify_tiktok](https://user-images.githubusercontent.com/87820481/126903265-8cf1d6e2-ec74-4fe2-8ac1-03cb75b4555c.PNG)
![dep_tik](https://user-images.githubusercontent.com/87820481/126903273-dc6d0021-67a1-4088-a0d7-cbbcf3505f8c.PNG)
![push_in_own_directory](https://user-images.githubusercontent.com/87820481/126903280-442ee7a4-4a4c-4ba6-91a2-ea9eea489a2f.PNG)
![Setting_up_gitpod](https://user-images.githubusercontent.com/87820481/126903285-0c76f431-d4f4-4706-ae01-c488ff4ab360.PNG)
![Setting_token_in_gitpod](https://user-images.githubusercontent.com/87820481/126903293-7f049cea-4987-4a09-be6f-dde21a83e213.PNG)
![token_generation_astradb](https://user-images.githubusercontent.com/87820481/126903332-6179ebef-6ae7-4517-a567-545ae90bb9f0.PNG)
![deployed_tiktok](https://user-images.githubusercontent.com/87820481/126903340-f3115532-8eab-4eb3-ae2e-7f0e0d69e833.PNG)
![final_deployed_tiktok_app](https://user-images.githubusercontent.com/87820481/126903344-413fd108-099a-406b-83ba-2f44f2aa09c7.PNG)

  
Attach the homework step II screenshots below:
-----------------------------------------
-- image removed by team --

Thank you for the amazing Session lot to learn in these session please try to do more session in future also,
thanks a lot @DatastaxDevelopers @Datastaxdevs

**Comment by HadesArchitect** [comment]
Hey **Adesh Bhosale**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_KKftbQWS8CqUznwWhm43w

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by SonicDMG** [comment]
> Thank you for the amazing Session lot to learn in these session please try to do more session in future also,
> thanks a lot @DatastaxDevelopers @datastaxdevs
Thank you very much for the kind words. We will definitely have more sessions coming in the future. Anything in particular you are interested in seeing?
