### ISSUE TITLE
[HW] GHANISHTHA UPADHYAY

### ISSUE THREAD

**Issue by GHANISHTHA0511** [datastaxdevs/workshop-social-media-tiktok#252]
Name: Ghanishtha Upadhyay
Email: ghanishthaupadhyaya@gmail.com
Linkedin Profile:https://www.linkedin.com/in/ghanishtha-upadhyay-723b301b8/
![Screenshot (17)](https://user-images.githubusercontent.com/85752905/126907148-25b83457-8d93-439b-8f21-2c27b3598e22.png)
![Screenshot (18)](https://user-images.githubusercontent.com/85752905/126907151-9e3aa74b-63ec-4997-87a2-4b81856db559.png)
![Screenshot (19)](https://user-images.githubusercontent.com/85752905/126907152-318b849b-f105-49a0-a29d-d4a05843fce7.png)
![Screenshot (20)](https://user-images.githubusercontent.com/85752905/126907153-f786a82a-64f7-4e01-b43c-e34e69927e02.png)
![Screenshot (21)](https://user-images.githubusercontent.com/85752905/126907154-2f3af3f2-93d7-448e-af20-9a5f35373eb5.png)

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Ghanishtha Upadhyay**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sPf70LZoTii6_sRSVkD2eQ
