### ISSUE TITLE
[HW] Sathasivam Rajagopal

### ISSUE THREAD

**Issue by rsatha** [datastaxdevs/workshop-social-media-tiktok#253]
**Name:** Sathasivam Rajagopal
**Email:**  r_satha@yahoo.co.in
**Linkedin Profile:** https://www.linkedin.com/in/satha-sivam-rajagopal-aba6031/

Attach the homework step I screenshots below:
-----------------------------------------
![tik-tok1](https://user-images.githubusercontent.com/44652050/126909443-80ca3446-4998-44bd-83ef-68407f325083.JPG)
![tik-tok2](https://user-images.githubusercontent.com/44652050/126909445-e46e1771-49ce-48a8-87ff-7771f5366053.jpg)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --
![netlify-post](https://user-images.githubusercontent.com/44652050/126909470-770b8a63-7b1c-4ea9-8dd5-f6351e39944f.JPG)
![netlify-post1](https://user-images.githubusercontent.com/44652050/126909473-1af5e31c-18d4-43a2-8083-6e110c704a62.JPG)

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Sathasivam Rajagopal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/1EiT_tmBTs6Ws9oLsWCqcQ

**Comment by SonicDMG** [comment]
Also, I had to remove some of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by rsatha** [comment]
Thanks for your update. will correct my mistake next time. can you please share the homework link for netflix . i missed the link for it .

    On Monday, July 26, 2021, 07:24:29 PM GMT+5:30, David Jones-Gilardi ***@***.***> wrote:  
 
 


Also, I had to remove some of your images because they contained your Astra token. Please delete your token from the Astra UI so there are no security issues.

**Comment by SonicDMG** [comment]
Of course, here is the repo for the netflix workshop https://github.com/datastaxdevs/appdev-week3-graphql#homework
