### ISSUE TITLE
[HW] <Xinyu Su>

### ISSUE THREAD

**Issue by xs419** [datastaxdevs/workshop-social-media-tiktok#254]
**Name:** Xinyu Su
**Email:** xs419@ic.ac.uk
**Linkedin Profile:** <https://www.linkedin.com/in/xinyu-su-414a451b2/>

Attach the homework step I screenshots below:
-----------------------------------------
<img width="1365" alt="Screenshot 2021-07-23 at 15 57 27" src="https://user-images.githubusercontent.com/74822534/127020623-16618c97-9c84-4b4e-90aa-9c52167e5114.png">
<img width="1274" alt="Screenshot 2021-07-23 at 16 10 55" src="https://user-images.githubusercontent.com/74822534/127020639-1dc86958-6a5d-4041-8c97-822f0d8a6499.png">
<img width="1358" alt="Screenshot 2021-07-23 at 16 12 30" src="https://user-images.githubusercontent.com/74822534/127020643-99ae8eb2-b7eb-406e-b392-bd3f73071bea.png">

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
-- image removed by team --

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Xinyu Su**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/DcR89rMcRLmK3OZGsKz8Cg

**Comment by SonicDMG** [comment]
Also, I had to remove one of your images because it contained your Astra token. Please delete your token via the Astra UI to ensure there are no security issues.
