### ISSUE TITLE
[HW] Dhruv Bejugam

### ISSUE THREAD

**Issue by dhruvsbe** [datastaxdevs/workshop-social-media-tiktok#255]
**Name:** Dhruv Bejugam
**Email:** dsbawesome@gmail.com
**Linkedin Profile:** www.linkedin.com/in/dhruv-bejugam-b6b425215

Attach the homework step I screenshots below:
-----------------------------------------
<img width="1680" alt="Screen Shot 2021-07-26 at 6 09 01 PM" src="https://user-images.githubusercontent.com/73863691/127065637-ec3714f0-4008-4dd5-9fc4-8c8b504fe92e.png">
<img width="1680" alt="Screen Shot 2021-07-26 at 6 07 11 PM" src="https://user-images.githubusercontent.com/73863691/127065654-3c8a81b8-0f38-4404-8f6e-89e3d3bfabfb.png">
<img width="1680" alt="Screen Shot 2021-07-26 at 6 07 49 PM" src="https://user-images.githubusercontent.com/73863691/127065645-a01f1f88-42a2-4e03-8d5a-9ce9a7f9c877.png">
<img width="1334" alt="Screen Shot 2021-07-26 at 6 08 19 PM" src="https://user-images.githubusercontent.com/73863691/127065643-1ed70b91-ea88-4fcb-8bb9-afc641db3830.png">

**Comment by HadesArchitect** [comment]
Hey **Dhruv Bejugam**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/FCsGwE6fRNu5XvAvPkweaA
