### ISSUE TITLE
[HW] Hanna Porada

### ISSUE THREAD

**Issue by HPorada** [datastaxdevs/workshop-social-media-tiktok#256]
**Name:** Hanna Porada
**Email:** hmporada@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/hanna-porada/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/75125104/127147690-4d5453d4-37f0-47a6-8ed2-fa0bf7d35dbc.png)

![image](https://user-images.githubusercontent.com/75125104/127151120-feea51c3-7d74-4c98-96b7-4371040dafe6.png)

![image](https://user-images.githubusercontent.com/75125104/127158512-c9c9d4f1-2fb4-4fed-a552-c4a37708ec03.png)

![image](https://user-images.githubusercontent.com/75125104/127160780-41e4bfa2-bd20-4732-95a1-007285627e26.png)

![image](https://user-images.githubusercontent.com/75125104/127160023-6c0fc873-ed73-4244-a9c3-03c8aaea8201.png)

![image](https://user-images.githubusercontent.com/75125104/127160475-88dfde72-1675-41f8-9162-7a12e8ad392f.png)

Attach the homework step II screenshots below:
-----------------------------------------

**Comment by HadesArchitect** [comment]
Hey **Hanna Porada**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MWC8_looQBezoFkEYuHEJQ
