### ISSUE TITLE
[HW] Sumedh Badnore

### ISSUE THREAD

**Issue by sumedhbadnore** [datastaxdevs/workshop-social-media-tiktok#258]
**Name:** Sumedh Badnore
**Email:** sumedhbadnore2801@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sumedh-badnore-a372341b9/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (432)](https://user-images.githubusercontent.com/66485793/127700489-73733a23-ed60-41dd-99cf-3dd80109a71b.png)

![Screenshot (433)](https://user-images.githubusercontent.com/66485793/127700502-47cf320b-8406-48c6-9cf7-3ff77432d2b2.png)

![Screenshot (431)](https://user-images.githubusercontent.com/66485793/127700516-c96264ce-0f5e-4f4f-bb5e-b3cfa16be4ad.png)

![Screenshot (434)](https://user-images.githubusercontent.com/66485793/127700522-d4b55945-feb7-4638-be43-36fc62dc00d4.png)

Attach the homework step II screenshots below:
-----------------------------------------

**Comment by RyanWelford** [comment]
Thanks, Sumedh! I had to remove one of your images as it contained you Astra token, it would be a good idea to delete your token in the Astra dashboard.

**Comment by HadesArchitect** [comment]
Hey **Sumedh Badnore**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/aMsDEaO_RTuYeFcHzpuRQA
