### ISSUE TITLE
[HW] <CHUBA>

### ISSUE THREAD

**Issue by chubalemba** [datastaxdevs/workshop-social-media-tiktok#26]
**Name:** <Chuba>
**Email:** <enigma6991@protonmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/chuba-lemba-078930143
![Screenshot (48)](https://user-images.githubusercontent.com/26831351/119798584-e77fa080-bef8-11eb-8e9c-39b1e85ee931.png)
>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you were able to successfully deploy the app, Chuba! Well done!

**Comment by SonicDMG** [comment]
Awesome Chuba, here you go. https://api.badgr.io/public/assertions/UJR2kvngR0SaDHDxizlq9w?identity__email=enigma6991%40protonmail.com
