### ISSUE TITLE
[HW] Ajay Karan

### ISSUE THREAD

**Issue by makmaniac** [datastaxdevs/workshop-social-media-tiktok#260]
**Name:** Ajay Karan
**Email:** makmaniac@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ajay-karan-web-developer/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![DataStax_Homework-Week 2](https://user-images.githubusercontent.com/41997590/127749294-471d5924-e6a9-4045-8e95-c447aa66c33d.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

![error](https://user-images.githubusercontent.com/41997590/127749345-920333cb-2bee-4817-9a75-f45c0f37c480.png)

**Comment by RyanWelford** [comment]
Thanks, Ajay. Not sure where the error is coming from, but it looks like you were able to deploy to netlify successfully.

**Comment by HadesArchitect** [comment]
Hey **Ajay Karan**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/MS0IdUH7QMq_jge0YcEUjA
