### ISSUE TITLE
[Week 2 HW] <TikTok Clone Ghazwa>

### ISSUE THREAD

**Issue by GhazwaQ** [datastaxdevs/workshop-social-media-tiktok#261]
**Name:** Ghazwa
**Email:** Alqahtani.xii@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/ghazwa-q>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (48)](https://user-images.githubusercontent.com/53545055/127750790-d779d8df-9dc5-4013-802e-1349442c43f9.png)

![Screenshot (49)](https://user-images.githubusercontent.com/53545055/127750797-30c5cd20-1e91-4c92-b2ec-445cf96d2669.png)

![Screenshot (55)](https://user-images.githubusercontent.com/53545055/127750800-aebdcbb8-23ec-4d88-aac7-95450762a007.png)

![Screenshot (56)_LI](https://user-images.githubusercontent.com/53545055/127750803-6e28e5aa-e528-4cb6-929a-feaf3fce7cf2.jpg)

![Screenshot (57)](https://user-images.githubusercontent.com/53545055/127750808-eb156040-3280-4942-8318-cb955e435757.png)

![Screenshot (58)](https://user-images.githubusercontent.com/53545055/127750810-96dea511-c0d4-4b11-abbb-d43db5c059be.png)

![Screenshot (59)](https://user-images.githubusercontent.com/53545055/127750814-7c0fc299-40ea-4b36-b1f8-5d0f37c42f4b.png)

![Screenshot (60)](https://user-images.githubusercontent.com/53545055/127750817-37db0473-ffb6-4848-a679-6f20aa476b9e.png)

![Screenshot (61)](https://user-images.githubusercontent.com/53545055/127750822-06130e86-67e2-43ac-bccd-e86820ed2878.png)

![Screenshot (62)_LI](https://user-images.githubusercontent.com/53545055/127750824-10e80ce3-3f8e-4dd6-bd81-6e42a443580c.jpg)

![Screenshot (63)_LI](https://user-images.githubusercontent.com/53545055/127750833-8ee6ac2e-4e9c-4ca5-8a91-cd1112150bbb.jpg)

![Screenshot (64)](https://user-images.githubusercontent.com/53545055/127750840-844a0450-adcf-4a03-a85b-05427940e4a5.png)

![Screenshot (65)](https://user-images.githubusercontent.com/53545055/127750844-2058fda8-4dad-4fdc-afb5-48c4fb661c42.png)

![Screenshot (66)](https://user-images.githubusercontent.com/53545055/127750846-99cf77ae-8bc5-4f1f-8839-c087b1cf7d23.png)

![Screenshot (67)](https://user-images.githubusercontent.com/53545055/127750847-16d92c42-6f8e-4863-ad5a-583403a96c37.png)

![Screenshot (68)](https://user-images.githubusercontent.com/53545055/127750854-75c22fda-239c-4154-ac86-6f636dc2a35d.png)

![Screenshot (69)](https://user-images.githubusercontent.com/53545055/127750857-6182ae7b-f94d-4eb8-893c-898f75243d2f.png)

![Screenshot (70)_LI](https://user-images.githubusercontent.com/53545055/127750860-c36a78f6-c8f0-446a-a156-e72e44bcf3b7.jpg)

**Comment by HadesArchitect** [comment]
Hey **Ghazwa**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/K1ElsZoQT6Wk46lYMt8mQQ
