### ISSUE TITLE
[HW] ABINASH

### ISSUE THREAD

**Issue by abinashsahoo** [datastaxdevs/workshop-social-media-tiktok#262]
**Name:** ABINASH SAHOO
**Email:** abinash.sahoo@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/abinashsahoo/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/6990736/127784959-03c97b5e-39c8-489c-917a-e6083f63430e.png)
![image](https://user-images.githubusercontent.com/6990736/127784998-6d55e6ad-c3f1-4614-bc5e-4e678e87c492.png)

https://clever-wozniak-e94c53.netlify.app/#/
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks, Abinash!

**Comment by HadesArchitect** [comment]
Hey **ABINASH SAHOO**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/CYtnhUdaS_2R3BGWZq51uQ
