### ISSUE TITLE
[HW] Saira Chaudhry

### ISSUE THREAD

**Issue by sidevgmb** [datastaxdevs/workshop-social-media-tiktok#264]
**Name:** Saira Chaudhry
**Email:** sidevgmb@gmail.com
**Linkedin Profile:** linkedin.com/in/saira-chaudhry-a467861a

Attach the homework step I screenshots below:
-----------------------------------------

![001](https://user-images.githubusercontent.com/78731146/128776795-60f2f0f8-e5ec-4279-9fb9-726185247a7b.PNG)

  
Attach the homework step II screenshots below:
-----------------------------------------

![002](https://user-images.githubusercontent.com/78731146/128776914-204481cd-d27d-465c-9c7f-c2f3e987d9b1.PNG)

![003](https://user-images.githubusercontent.com/78731146/128776997-ff21aa51-58cd-4f46-88d0-f2341ca8c279.PNG)

**Comment by RyanWelford** [comment]
Awesome, Saira! Well done!
