### ISSUE TITLE
[HW] NGUYEN THE ANH

### ISSUE THREAD

**Issue by anhnt4288** [datastaxdevs/workshop-social-media-tiktok#267]
**Name:** NGUYEN THE ANH
**Email:** anh.nt4288@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/anh-nguy%E1%BB%85n-98b70794/

Attach the homework step I screenshots below:
-----------------------------------------
<img width="1412" alt="tiktok-2" src="https://user-images.githubusercontent.com/13186215/131207433-fcf0dc74-02f0-40a0-9eab-5968f474d740.png">
<img width="1437" alt="tiktok-3" src="https://user-images.githubusercontent.com/13186215/131207434-b948aced-df62-489e-b382-0368c0795cb8.png">

  
Attach the homework step II screenshots below:
-----------------------------------------
<img width="1428" alt="tiktok-1" src="https://user-images.githubusercontent.com/13186215/131207439-c3aa6c5a-b2ed-4965-9e23-b88dc4ad921f.png">

**Comment by HadesArchitect** [comment]
Hey **NGUYEN THE ANH**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/-byiuTxSQcKEMo_znQM_gw
