### ISSUE TITLE
[HW] Veronica Smigielski

### ISSUE THREAD

**Issue by VSmigielski** [datastaxdevs/workshop-social-media-tiktok#268]
**Name:** Veronica Smigielski
**Email:** veronicasmigielski@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/veronica-smigielski-b85025174/

Attach the homework step I screenshots below:
-----------------------------------------
Adding screen shots wasn't showing anything so I uploaded them to here.
<SCREENSHOTS>
https://ibb.co/hLqWgDs
![tiktokclone-part2](https://user-images.githubusercontent.com/66082052/131233270-97749bed-b452-4176-a45b-e292cdc60152.png)
https://epic-cori-0397b4.netlify.app/

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
https://ibb.co/TWwvV40

![image](https://user-images.githubusercontent.com/66082052/131233288-60ca0488-3496-4989-b602-6d74aafe8872.png)

https://cocky-clarke-8e0e17.netlify.app/#/

**Comment by HadesArchitect** [comment]
Hey **Veronica Smigielski**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/r2M1-fnDQmKTqFgzknbj-Q
