### ISSUE TITLE
tikotok HW Kalpan Bhalsod

### ISSUE THREAD

**Issue by kalmax** [datastaxdevs/workshop-social-media-tiktok#269]
**Name:** Kalpan Bhalsod
**Email:** bhalsod.kalpan@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kalpanbhalsod/
<img width="1073" alt="Screenshot 2021-08-30 at 4 12 26 AM" src="https://user-images.githubusercontent.com/351424/131268197-b0b9c23f-e4ab-4515-b7e1-1a2227bec301.png">
<img width="1435" alt="Screenshot 2021-08-30 at 4 18 00 AM" src="https://user-images.githubusercontent.com/351424/131268202-96acc2ed-cbe8-470c-98f7-c8980d5d85fc.png">
<img width="1435" alt="Screenshot 2021-08-30 at 4 21 39 AM" src="https://user-images.githubusercontent.com/351424/131268213-ee151e1f-abaf-4665-9b1e-eff7de3cedf5.png">
<img width="1435" alt="Screenshot 2021-08-30 at 4 22 59 AM" src="https://user-images.githubusercontent.com/351424/131268216-e7a5b36a-cd50-4a54-b42d-f580921b58a2.png">
-- image removed by team --
<img width="1435" alt="Screenshot 2021-08-30 at 4 31 37 AM" src="https://user-images.githubusercontent.com/351424/131268226-bf18a7b3-3f62-4989-804b-a67dfcfa6682.png">

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Kalpan Bhalsod**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/8TMnx64DTP-NxSiemLufjQ

**Comment by SonicDMG** [comment]
Also, I had to removed one of your images because it contained your Astra token. Please delete your token from the Astra UI to ensure there are no security issues.
