### ISSUE TITLE
[HW] Paschalis Tolios

### ISSUE THREAD

**Issue by paschalistol** [datastaxdevs/workshop-social-media-tiktok#27]
**Name:** Paschalis Tolios
**Email:** tolios54@gmail.com
**Linkedin Profile:** www.linkedin.com/in/paschalistol/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --

**Comment by RyanWelford** [comment]
Something happened with the embedded images, but it looks like you were able to deploy. Thanks Paschalis!

**Comment by SonicDMG** [comment]
Thank you so much Paschalis, here you go -> https://api.badgr.io/public/assertions/j1wks-0iTCaR9UEvG-W6aA?identity__email=tolios54%40gmail.com
