### ISSUE TITLE
[HW] <Solomon Yu>

### ISSUE THREAD

**Issue by sqr00t** [datastaxdevs/workshop-social-media-tiktok#270]
**Name:** Solomon Yu
**Email:** solomon.sj.yu@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/solomonsjyu/>

Attach the homework step I screenshots below:
-----------------------------------------
![1](https://user-images.githubusercontent.com/797346/132868679-53de66bf-6444-4b29-ae05-8da9dbe6e70b.png)
![2](https://user-images.githubusercontent.com/797346/132868685-c29b6c81-71ff-4ab6-a4b1-e8ebfd62f817.png)
![3](https://user-images.githubusercontent.com/797346/132868699-5a5e1462-c415-473c-b8f3-cc1e1042af23.png)
![4](https://user-images.githubusercontent.com/797346/132868712-e202602f-379b-49c5-a845-109d83d075f0.png)
![5](https://user-images.githubusercontent.com/797346/132868729-087acea2-7e1e-4736-8fad-93acf816197f.png)
![6](https://user-images.githubusercontent.com/797346/132868733-628a286a-3733-4b7d-95fc-97dccf1e2ccc.png)
![7](https://user-images.githubusercontent.com/797346/132868738-6b77b5b9-2cd9-4a7f-b560-0546328460f4.png)
![8](https://user-images.githubusercontent.com/797346/132868749-c5f07478-beef-455e-ae6c-d232255225d5.png)
![9](https://user-images.githubusercontent.com/797346/132868758-5497a6f0-64a4-4804-9809-4e1b84bb6c43.png)
![10](https://user-images.githubusercontent.com/797346/132868768-3735f090-8ba2-42c2-ac0e-d8211d506320.png)
![11](https://user-images.githubusercontent.com/797346/132868779-0815a82c-38ad-417e-93a9-6c5fa30a1280.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by sqr00t** [comment]
homework step II (Optional Credit) will be appended later.

**Comment by HadesArchitect** [comment]
Hey **Solomon Yu**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/cp9l-5yFReKyJ5AD-mk8iw
