### ISSUE TITLE
[HW] <TikTok Workshop>

### ISSUE THREAD

**Issue by GeorgeET15** [datastaxdevs/workshop-social-media-tiktok#271]
**Name:** George Emmanuel Thomas
**Email:** ironmanrocks353@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/george-emmanuel-thomas-518060202/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (409)](https://user-images.githubusercontent.com/72024420/134728732-2d22e1f0-7e80-4118-a7f1-2b10673362cf.png)

![Screenshot (408)](https://user-images.githubusercontent.com/72024420/134728786-dea6463c-ac07-4dfe-b9f6-4af6dc9b5ea0.png)
![Screenshot (410)](https://user-images.githubusercontent.com/72024420/134728800-149246f3-ffa0-4ad5-b914-260cb9048923.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

-- images removed by team --

**Comment by HadesArchitect** [comment]
Hey **George Emmanuel Thomas**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/m7x-EXD1Qp2UWaEWHp2_RA

**Comment by SonicDMG** [comment]
Also, I had to remove a set of your images because they contained your Astra token. Please delete your token from the Astra UI to ensure there are no security issues. Thank you. :)

**Comment by GeorgeET15** [comment]
Ok sir, thanks a lot :)
