### ISSUE TITLE
[HW] Shivani Narang

### ISSUE THREAD

**Issue by Shivani-exe** [datastaxdevs/workshop-social-media-tiktok#273]
**Name:** Shivani Narang
**Email:** shivaninarang20@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/shivani-narang-a86298141/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
<img width="957" alt="tiktop-app" src="https://user-images.githubusercontent.com/77279946/136337723-363f60c5-f4f3-4ef1-aa52-baf77c8f215f.PNG">
[Attach]([url](url)) the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by Shivani-exe** [comment]
Please review tiktok clone app: https://friendly-newton-88f3c4.netlify.app/#/

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Shivani Narang

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/cm9TzWtfR0S1TCeiPC7KBw

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
