### ISSUE TITLE
[HW] <Ian>

### ISSUE THREAD

**Issue by ianlaporte** [datastaxdevs/workshop-social-media-tiktok#279]
**Name:** Ian Laporte
**Email:** ianlaporte@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ianlaporte/
**Imgur for these screenshot:** https://imgur.com/a/pvZLmzB

**Netlify Link to my TikTok app made today:**  https://tiktoknetlifyian.netlify.app 
(Issue made as Homework to get my Badge. Thank you)

Thanks to the DataStax team at : 
   [https://www.datastax.com/](url)  ,  or  
   [https://www.eventbrite.com/o/datastax-23222864038](url)

Attach the homework step I screenshots below:
-----------------------------------------
<SCREENSHOTS>
https://i.imgur.com/dFln6u0.jpg
[https://i.imgur.com/dFln6u0.jpg](url)

Attach the homework step II screenshots below:
-----------------------------------------
<SCREENSHOTS>
https://i.imgur.com/dFln6u0.jpg
[https://i.imgur.com/4tUT4gq.jpg](url)

--
![tiktokLiveByIanLaporteCassandraNetlify01](https://user-images.githubusercontent.com/44279639/137190436-33823c4f-f6e6-4e9f-a2a8-9f77a811ae7e.jpg)
-
![tiktokLiveByIanLaporteCassandraNetlify02](https://user-images.githubusercontent.com/44279639/137190455-53481568-825f-4076-8f10-798894a91384.jpg)
-

**Comment by HadesArchitect** [comment]
<img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.istockphoto.com%2Fvectors%2Fcongratulations-greeting-sign-congrats-graduated-vector-id1148641884%3Fk%3D6%26m%3D1148641884%26s%3D170667a%26w%3D0%26h%3Dsu9WLQGWgcHmCjBwkVLEg6hWDH0eQLcmynVYfHQOFl0%3D&f=1&nofb=1" width="300px" height="100px"/>

# Ian Laporte

*Thank you for your efforts, it is a pleasure for us to give you your well deserved BADGE at the following link* 
- https://api.badgr.io/public/assertions/boRwUTTRT-u2y9tTFuJJqA

*You can now brag about it on Twitter, Facebook or LinkedIn. It helps the workshops to be more visible and encourages us Advocates coming back every week with new content. Please make sure to use the hashtag **#DatastaxDevWorkshops.***

💚   🙏🏻    🙏🏽   🙏🏿
**The Datastax Advocates Team** (@DatastaxDevs)
**#DatastaxDevWorkshops**

<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-facebook.png"/></a>

<a href="https://twitter.com/intent/tweet?url=https://www.linkedin.com/sharing/share-offsite/?url=https://www.datastax.com/workshops"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-twitter.png"/></a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=https://www.datastax.com/workshops&title=DatastaxDevWorkshops&summary=I attended a FREE LIVE workshop on @DatastaxDev youtube channel where I even earn badge. Thank you ! #DatastaxDevWorkshops. To know the incoming sessions"><img src="https://github.com/datastaxdevs/workshop-battlestax/raw/master/tutorial/share-linkedin.png"/></a>
