### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by 1bigmuscle** [datastaxdevs/workshop-social-media-tiktok#28]
**Name:** <NAME>
**Email:** <email>
**Linkedin Profile:** <LINK>

Attach the homework step I screenshots below:
-----------------------------------------
![IMG_20210527_102112](https://user-images.githubusercontent.com/81053710/119799552-75995e00-bedc-11eb-84b0-7aa642e15c9f.jpg)
#

**Comment by RyanWelford** [comment]
We need a name to issue badges, and a full screen screenshot is preferred.

**Comment by 1bigmuscle** [comment]
Linda Kalendzhiev 
Gesendet von Yahoo Mail auf Android 
 
  Am Do., Mai 27, 2021 at 16:50 schrieb ***@***.***>:   


We need a name to issue badges, and a full screen screenshot is preferred.

**Comment by RyanWelford** [comment]
Thanks!
