### ISSUE TITLE
[HW] Shalini Sil

### ISSUE THREAD

**Issue by sal81** [datastaxdevs/workshop-social-media-tiktok#29]
**Name:** <Shalini Sil>
**Email:** <shalinisil81@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/shalinisil81/>

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (28)](https://user-images.githubusercontent.com/56610069/119795939-8e167200-bef6-11eb-9a88-bcdd21b5e52f.png)
![Screenshot (29)](https://user-images.githubusercontent.com/56610069/119795945-8fe03580-bef6-11eb-8654-54c6b34d6c85.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --
![Screenshot (32)](https://user-images.githubusercontent.com/56610069/119801002-e8b1cd00-befa-11eb-950c-320d9e06b80d.png)
![Screenshot (33)](https://user-images.githubusercontent.com/56610069/119801004-e8b1cd00-befa-11eb-93a1-31372ffbd91d.png)
![Screenshot (34)](https://user-images.githubusercontent.com/56610069/119801005-e94a6380-befa-11eb-97ff-417750b9b88a.png)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Awesome work Shalini!

**Comment by SonicDMG** [comment]
Nice job displaying the end result JSON in a parsed format. Looks a lot nicer that way. I should do that myself. Here you go -> https://api.badgr.io/public/assertions/VlrJ1k5pTXOrxjwrx2VltA?identity__email=shalinisil81%40gmail.com
