### ISSUE TITLE
[HW] ARUN

### ISSUE THREAD

**Issue by arun-gautham** [datastaxdevs/workshop-social-media-tiktok#31]
**Name:** Arun Gautham Rajarao
**Email:** arunrajarao@gmail.com
**Linkedin Profile:** [@arun-gautham](https://www.linkedin.com/in/arun-gautham-9a000129/)

Attach the homework step I screenshots below:
-----------------------------------------
[SCREENSHOT-URL](https://romantic-engelbart-6235cc.netlify.app)
[DEPLOY-URL](https://romantic-engelbart-6235cc.netlify.app)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Arun!

**Comment by SonicDMG** [comment]
Awesome job Arun. Here's your badge -> https://api.badgr.io/public/assertions/eKnzWcsNTh-9Q1XrOQdHTg?identity__email=arunrajarao%40gmail.com
