### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Divyanshu-Salve** [datastaxdevs/workshop-social-media-tiktok#32]
**Name:** Divyanshu Salve
**Email:** dsalve@cs.iitr.ac.in
**Linkedin Profile:** https://www.linkedin.com/in/divyanshu-salve-6324b6185/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot from 2021-05-27 14-28-02](https://user-images.githubusercontent.com/47054350/119810784-00418380-bf04-11eb-9d85-f7c612e3801d.png)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you deployed successfully. Thanks Divyanshu!

**Comment by SonicDMG** [comment]
That's great Divy, glad to see it's all working for you. Nice Job. Here's your badge -> https://api.badgr.io/public/assertions/m95wSzA2TKmdsKJBQk2H1A?identity__email=dsalve%40cs.iitr.ac.in. 

BTW, is "Divy" an ok way to say your name or did I totally mess that up during the stream?

**Comment by Divyanshu-Salve** [comment]
> That's great Divy, glad to see it's all working for you. Nice Job. Here's your badge -> https://api.badgr.io/public/assertions/m95wSzA2TKmdsKJBQk2H1A?identity__email=dsalve%40cs.iitr.ac.in.
> 
> BTW, is "Divy" an ok way to say your name or did I totally mess that up during the stream?

Thanks for the appreciation, but, the ok way to say my name is Divyanshu :smile:

**Comment by SonicDMG** [comment]
Ahh, thank you for that. I'll work to get that right in the future. :)
