### ISSUE TITLE
[HW] Shijo prakash

### ISSUE THREAD

**Issue by Shijoprakash** [datastaxdevs/workshop-social-media-tiktok#34]
**Name:** Shijo Praskash
**Email:** <officialshijo@gmail.com>
**Linkedin Profile:** https://www.linkedin.com/in/shijoprakash/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/84899368/119817181-9edfdb80-bf28-11eb-9126-b6ae452a60e6.png)
![image](https://user-images.githubusercontent.com/84899368/119817259-b919b980-bf28-11eb-8574-3cddd3768ed5.png)
![image](https://user-images.githubusercontent.com/84899368/119817398-e5353a80-bf28-11eb-9d12-72ecfecc2a95.png)
![image](https://user-images.githubusercontent.com/84899368/119817823-642a7300-bf29-11eb-873e-bece362cb29c.png)
-- images removed by team --

**Comment by RyanWelford** [comment]
Awesome job, Shijo!

**Comment by SonicDMG** [comment]
Well done, here's your badge -> https://api.badgr.io/public/assertions/G2qTqjG5R-K-5stOAjqbJg?identity__email=officialshijo%40gmail.com
