### ISSUE TITLE
[HW] <SaiRamaKrishna>

### ISSUE THREAD

**Issue by myselfsrk** [datastaxdevs/workshop-social-media-tiktok#35]
**Name:** <Sai RamaKrishna>
**Email:** <sairamakrishna.srk96@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/sai-rama-krishna-srk96/>

Attach the homework step I screenshots below:
-----------------------------------------
![part 1](https://user-images.githubusercontent.com/23332011/119826574-ca0cff80-bf15-11eb-9f2d-14a501228b92.PNG)
<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/23332011/119826769-03456f80-bf16-11eb-8139-43a8c7450c1d.png)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Well done!

**Comment by SonicDMG** [comment]
Great job, here you go. https://api.badgr.io/public/assertions/mteLZKTDTnqZUkLwLYJAAw?identity__email=sairamakrishna.srk96%40gmail.com
