### ISSUE TITLE
[HW] Prafull Kotecha

### ISSUE THREAD

**Issue by prafullkotecha** [datastaxdevs/workshop-social-media-tiktok#36]
**Name:** Prafull Kotecha
**Email:** prafull@direkshan.digital
**Linkedin Profile:** https://www.linkedin.com/in/prafullkotecha

Attach the homework step I screenshots below:
-----------------------------------------
1. DB Created
![image](https://user-images.githubusercontent.com/563146/119807788-808ac900-beb1-11eb-9911-98889f76288d.png)

2. Initial Netlify Deploy complete
![image](https://user-images.githubusercontent.com/563146/119807565-41f50e80-beb1-11eb-9779-7bb850eb4fca.png)

3. GitPod Launched
![image](https://user-images.githubusercontent.com/563146/119808005-b2039480-beb1-11eb-819d-3f8e00d26eca.png)

4. `netlify deploy --prod` output
![image](https://user-images.githubusercontent.com/563146/119816879-41fa0c00-bebb-11eb-887a-fde2c3a581fc.png)

5. App running
![image](https://user-images.githubusercontent.com/563146/119808268-f4c56c80-beb1-11eb-9d86-56a6a1d8b8bc.png)

6. Connect to the Database and Test Swagger endpoint
-- images removed by team --

7. Document API : Get Documents in a Collection
-- images removed by team --

Attach the homework step II screenshots below:
-----------------------------------------
`Work-in-Progress` 🚧

**Comment by RyanWelford** [comment]
Awesome! Thanks for the well documented results, Prafull!

**Comment by SonicDMG** [comment]
Yes, definitely looks good. Here you go Prafull. https://api.badgr.io/public/assertions/ASr2Pi63T3qXGX__5aWoyg?identity__email=prafull%40direkshan.digital
