### ISSUE TITLE
[HW] Praveen Ogirala

### ISSUE THREAD

**Issue by praveenogirala** [datastaxdevs/workshop-social-media-tiktok#38]
**Name:** Venkata Naga Praveen Ogirala
**Email:** nagapraveen.ogirala@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/praveenogirala/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/20016759/119856605-71555b00-bf45-11eb-96ab-f74656f4704d.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/20016759/119856605-71555b00-bf45-11eb-96ab-f74656f4704d.png)

**Comment by SonicDMG** [comment]
Looks good Venkata, thank you. Here's your badge -> https://api.badgr.io/public/assertions/mcPrMn2KThWbXiK9-6JFLA?identity__email=nagapraveen.ogirala%40gmail.com
