### ISSUE TITLE
[HW] Kevin Sunil George

### ISSUE THREAD

**Issue by kevinsunil** [datastaxdevs/workshop-social-media-tiktok#39]
**Name:** Kevin Sunil George
**Email:** kevinsunil.2001@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/kevin-s-george-a0a609206

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![Screenshot (260)](https://user-images.githubusercontent.com/69797975/119875425-5d5d2980-bf44-11eb-8aaf-93ebb5abd295.png)

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Looks like you have a successful deployment, nice work!

**Comment by HadesArchitect** [comment]
Hey **Kevin Sunil George**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/blgCzUvyRKyWuXndzVJm2A
