### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by Nithish2** [datastaxdevs/workshop-social-media-tiktok#45]
**Name:** NITHISH MANI GANGA
**Email:** nithishmani2@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/nithish-mani-ganga-112372213/

![Screenshot (10)](https://user-images.githubusercontent.com/65704266/119888757-643f6880-bf53-11eb-92e0-8874235bc4be.png)

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (10)](https://user-images.githubusercontent.com/65704266/119888697-54c01f80-bf53-11eb-9103-175f6dda34e0.png)

Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (45)](https://user-images.githubusercontent.com/65704266/119888859-81743700-bf53-11eb-9c80-6c2bf7b460ea.png)

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Nithish!

**Comment by Nithish2** [comment]
When will I be receiving my Badge?

**Comment by SonicDMG** [comment]
Here you go -> https://api.badgr.io/public/assertions/nku44iOYTbmg6jXhGfmO9w?identity__email=nithishmani2%40gmail.com. Thank you again for your submission.

**Comment by HadesArchitect** [comment]
Hey **NITHISH MANI GANGA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/c1xRp--uQVSw_2bHTKvywA
