### ISSUE TITLE
[HW] Piotr Wlazeł

### ISSUE THREAD

**Issue by Nieokorzesany** [datastaxdevs/workshop-social-media-tiktok#46]
**Name:** Piotr Wlazeł
**Email:** pancu1222@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/piotr-wlaze%C5%82-896202128/

Attach the homework step I screenshots below:
-----------------------------------------

![datastax-tiktok-clone](https://user-images.githubusercontent.com/38163577/119895466-1b30e980-bf3e-11eb-8c36-5b13dcf1710f.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Piotr, looks like a successful deploy.

**Comment by SonicDMG** [comment]
Nice job Piotr, here's your badge -> https://api.badgr.io/public/assertions/rtMopIziRne1ArT3rvOrxQ?identity__email=pancu1222%40gmail.com
