### ISSUE TITLE
[HW] RIYA TERI

### ISSUE THREAD

**Issue by riya0108** [datastaxdevs/workshop-social-media-tiktok#47]
**Name:** Riya Teri
**Email:** riyateri01@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/riyateri/

Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (100)](https://user-images.githubusercontent.com/70089241/119936729-40a60d80-bfa7-11eb-89ba-c2427a8be285.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (100)](https://user-images.githubusercontent.com/70089241/119936832-659a8080-bfa7-11eb-95ce-e50b681b6d9f.png)

**Comment by riya0108** [comment]
When will the badges be issued?

**Comment by RyanWelford** [comment]
Thanks Riya, we will issue badges as soon as we can.

**Comment by SonicDMG** [comment]
Here you go Riya, thank you so much. https://api.badgr.io/public/assertions/txk9ciZGRGy0gphD9m7IUw?identity__email=riyateri01%40gmail.com

**Comment by riya0108** [comment]
> Here you go Riya, thank you so much. https://api.badgr.io/public/assertions/txk9ciZGRGy0gphD9m7IUw?identity__email=riyateri01%40gmail.com

Thank you so much, looking forward to the Netflix clone workshop!

**Comment by SonicDMG** [comment]
Of course. We are excited for the Netflix workshop as well. See you there. :D
