### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by sushmahs2** [datastaxdevs/workshop-social-media-tiktok#48]
Name: SUSHMA H S
Email: sushmahdkote@gmail.com
Linkedin Profile: https://www.linkedin.com/in/sushma-h-s-457a7418b

Attach the homework step I screenshots below:
![workshop tik tok clone](https://user-images.githubusercontent.com/71074130/119946400-38080400-bfb4-11eb-882a-c6ef14df5b71.PNG)

  
Attach the homework step II screenshots below:
-----------------------------------------
sorry sir I couldn't complete my second homework

**Comment by RyanWelford** [comment]
Thanks Sushma!

**Comment by SonicDMG** [comment]
Sushma, were you able to get the app deployed to Netlify or did you run into trouble there?

**Comment by sushmahs2** [comment]
Badge is not issued for me 🤔

**Comment by sushmahs2** [comment]
> Sushma, were you able to get the app deployed to Netlify or did you run into trouble there?

No I got

**Comment by HadesArchitect** [comment]
Hey **SUSHMA H S**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/ISkq3cb6TvaKbiBZSdduSA
