### ISSUE TITLE
[HW]  Sabrina Mueller

### ISSUE THREAD

**Issue by SabMueller** [datastaxdevs/workshop-social-media-tiktok#49]
**Name:** Sabrina Mueller
**Email:** sabrina@famefox.de
**Linkedin Profile:** https://www.linkedin.com/in/musa180688/

Attach the homework step I screenshots below:
-----------------------------------------
<img width="1437" alt="Bildschirmfoto 2021-05-28 um 19 07 47" src="https://user-images.githubusercontent.com/82114506/120019264-83d4a080-bfe8-11eb-9c0e-b985e6968b8c.png">

**Comment by RyanWelford** [comment]
Great job Sabrina! Looks like you deployed successfully!

**Comment by SabMueller** [comment]
Thank you! It was a lot of fun!

**Comment by SonicDMG** [comment]
Glad you thought so Sabrina, thank you. Here you go -> https://api.badgr.io/public/assertions/EHxL4arPTzS0DKPgCCoXTA?identity__email=sabrina%40famefox.de
