### ISSUE TITLE
[HW] Bejan Afshar

### ISSUE THREAD

**Issue by bejanaf** [datastaxdevs/workshop-social-media-tiktok#50]
**Name:** Bejan Afshar
**Email:** da_reggaeman_@gmx.de
<img width="1440" alt="Screenshot 2021-05-28 at 19 05 31" src="https://user-images.githubusercontent.com/82392827/120019157-630c4b00-bfe8-11eb-9305-10b48b5ea4c3.png">

**Linkedin Profile:** https://www.linkedin.com/feed/?trk=onboarding-landing

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by RyanWelford** [comment]
Thanks Bejan!

**Comment by SonicDMG** [comment]
Awesome job Bejan, here you go -> https://api.badgr.io/public/assertions/iAcycki2QNOeINRgF_7ySg?identity__email=da_reggaeman_%40gmx.de
