### ISSUE TITLE
[HW] <SIDDHARTH GOENKA>

### ISSUE THREAD

**Issue by siddharth214** [datastaxdevs/workshop-social-media-tiktok#52]
**Name:** <SIDDHARTH GOENKA>
**Email:** <siddharthgoenka17@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/siddharth-goenka-22b75a169/>

Attach the homework step I screenshots below:
-----------------------------------------

<[SCREENSHOTS](https://drive.google.com/drive/folders/1WehUBFCA5HIyHM8urUvG84D7D_IPIHHH?usp=sharing)>
<[OUTPUT](https://keen-leavitt-0b06db.netlify.app/)>

**Comment by RyanWelford** [comment]
Thanks Siddharth!

**Comment by siddharth214** [comment]
Thank You Sir !

**Comment by SonicDMG** [comment]
Hey Siddarth. I reopened this so you could get your badge. Here you go -> https://api.badgr.io/public/assertions/1Rv2bxR4S86SE-49iBo_jA?identity__email=siddharthgoenka17%40gmail.com. Thanks for your submission.
