### ISSUE TITLE
[HW] <NAME>

### ISSUE THREAD

**Issue by ChaudhariNilesh** [datastaxdevs/workshop-social-media-tiktok#56]
**Name:**  Chaudhari Nilesh
**Email:**  nileshchaudhary1905@gmail.com
**Linkedin Profile:**  https://www.linkedin.com/in/nilesh-chaudhari100/
Attach the homework step I screenshots below:
-----------------------------------------
![Screenshot (1294)](https://user-images.githubusercontent.com/47267076/120110732-5f192e00-c18c-11eb-96e7-a64e5d6f69c5.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Chaudhari, thank you. Here's your badge -> https://api.badgr.io/public/assertions/CuUVkv49S46O07yLilVWBw?identity__email=nileshchaudhary1905%40gmail.com
