### ISSUE TITLE
[HW] Kenneth Heung

### ISSUE THREAD

**Issue by kennethheung** [datastaxdevs/workshop-social-media-tiktok#58]
**Name:** Kenneth Heung
**Email:** kenneth.heung@gmail.com

Attach the homework step I screenshots below:
-----------------------------------------

## Up and running app in Netlify (I am using custom domain name)

<img width="1437" alt="Screenshot 2021-06-01 at 10 40 30 AM" src="https://user-images.githubusercontent.com/9417297/120262355-2a13f500-c2cc-11eb-80be-94738cbdd506.png">

## Using Swagger to examine the actual data in Astra

<img width="1447" alt="Screenshot 2021-06-01 at 10 55 16 AM" src="https://user-images.githubusercontent.com/9417297/120262456-4d3ea480-c2cc-11eb-9acf-8951a2beab0f.png">
  
Attach the homework step II screenshots below:
-----------------------------------------

## using Ania video to Build-My-Own-App

1. I am running it in my local environment with `netlify dev` 
2. Originally, Ania teach ppl to use username/password to connect to Astra, we will need to change the function with application token
3. although Ania also provide full final src, it is already 6 months ago - we will need to aware the version dependencies - using latest version of package - or just refer to datastaxdevs repo to resolve the errors
4. actual, datastaxdevs src (this repo) got some enhancements on Ania's code, e.g. putting Astra connection under utils and just reuse instead of having it in all add / addData / edit / posts

<img width="2285" alt="Screenshot 2021-06-01 at 11 23 45 AM" src="https://user-images.githubusercontent.com/9417297/120262977-5e3be580-c2cd-11eb-8095-e940916093df.png">

**Comment by SonicDMG** [comment]
Wow Kenneth, nice job not only doing the initial homework, but getting through Ania's content as well along with providing feedback. Simply awesome.

**Comment by SonicDMG** [comment]
Here's your well earned badge -> https://api.badgr.io/public/assertions/QsKqoTVzRZy09yN6g1Hq6Q?identity__email=kenneth.heung%40gmail.com

**Comment by SonicDMG** [comment]
Hey there Kenneth, are you on our Discord perchance? If so, what's your handle?
