### ISSUE TITLE
[HW] <Hirokjyoti Dutta>

### ISSUE THREAD

**Issue by ShadowXHunter** [datastaxdevs/workshop-social-media-tiktok#59]
**Name:** Hirokjyoti Dutta
**Email:** hjduttaxx@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/hirokjyoti-dutta-6a2938183/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/45921454/120595188-9f63ff00-c45f-11eb-83e5-4257e2363d90.png)

![image](https://user-images.githubusercontent.com/45921454/120595247-af7bde80-c45f-11eb-93d5-295c4204d320.png)

![image](https://user-images.githubusercontent.com/45921454/120595283-bd316400-c45f-11eb-860d-42694fe2ee7f.png)

**Comment by SonicDMG** [comment]
Nice job deploying to production Hirokjyoti. I've removed your images because some included your AstraDB token. Please delete the token within the AstraDB UI. Here's your badge -> https://api.badgr.io/public/assertions/_uIbIxpQQ5mhmX2tosvKmw?identity__email=hjduttaxx%40gmail.com. Thank you again.

**Comment by ShadowXHunter** [comment]
Thanks for removing those images. I have updated it now. Also, thanks for issuing the badge.
@SonicDMG

**Comment by SonicDMG** [comment]
Awesome Hirokjyoti, thank you.
