### ISSUE TITLE
[HW] <MALLA HASWANTH>

### ISSUE THREAD

**Issue by mallahaswanth** [datastaxdevs/workshop-social-media-tiktok#60]
**Name:** <MALLA HASWANTH>
**Email:** <mallahaswanth99@gmail.com>
**Linkedin Profile:** <https://www.linkedin.com/in/malla-haswanth-41ba5817a/>

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
![Screenshot (293)](https://user-images.githubusercontent.com/47265019/120525301-9c342900-c3f5-11eb-918f-b84a1846c6dd.png)

>
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Nice job deploying to production Malla, thank you. Here's your badge -> https://api.badgr.io/public/assertions/gVEfpyMISyKrP9_xOK1VdA?identity__email=mallahaswanth99%40gmail.com
