### ISSUE TITLE
[HW] Pulkit Saini

### ISSUE THREAD

**Issue by sainipulkit0007** [datastaxdevs/workshop-social-media-tiktok#61]
**Name:** Pulkit Saini
**Email:** pulkitsainisre@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pulkit-saini-444a6b176/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

![image](https://user-images.githubusercontent.com/56683585/121345619-b82e5200-c942-11eb-8ca5-c0e17025518c.png)

![Screenshot (73)](https://user-images.githubusercontent.com/56683585/121345718-d2683000-c942-11eb-808f-cae9153f2048.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/56683585/121345827-f592df80-c942-11eb-8052-111d11cfef70.png)

<SCREENSHOTS>

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/4dtbL9-1RN6XzV_ej_u3wA?identity__email=pulkitsainisre@gmail.com
