### ISSUE TITLE
[HW] SINI T P

### ISSUE THREAD

**Issue by sini-kannan** [datastaxdevs/workshop-social-media-tiktok#63]
Name:  Sini T P
Email: sinitp2015@gmail.com
Linkedin Profile: https://www.linkedin.com/in/sini-t-p-11846a169/

Attach the homework screenshots below:
-----------------------------------------

<SCREENSHOTS>

I am sorry , couldnt take screenshot of every step. I have attached images of the final steps.
I have inserted a movie named **BAHUBALI** in **_FANTASY_** genre.
Excited for the badge!!

![seg](https://user-images.githubusercontent.com/42380005/121471792-e4e37780-c9dd-11eb-96f6-3c5035b0fc0f.jpeg)

![ush](https://user-images.githubusercontent.com/42380005/121472607-0b55e280-c9df-11eb-97ad-5debd204bfbc.jpeg)

![1](https://user-images.githubusercontent.com/42380005/121471403-3c351800-c9dd-11eb-938f-6cadbae750ea.jpeg)
![2](https://user-images.githubusercontent.com/42380005/121471407-3dfedb80-c9dd-11eb-906c-531f87ab29b4.jpeg)
![3](https://user-images.githubusercontent.com/42380005/121471409-3e977200-c9dd-11eb-8b47-62088c3786e1.jpeg)
![4](https://user-images.githubusercontent.com/42380005/121471411-3f300880-c9dd-11eb-861d-5b2aa6f1d887.jpeg)
![5](https://user-images.githubusercontent.com/42380005/121471413-3fc89f00-c9dd-11eb-89b0-d5389c5d590e.jpeg)
![WhatsApp Image 2021-06-10 at 10 52 58](https://user-images.githubusercontent.com/42380005/121471416-40613580-c9dd-11eb-9aa2-84ccee1ac945.jpeg)

**Comment by clun** [comment]
Hello, 

oohhh you submitted the Netflix assignments in the tiktok repository. No worries the badge will be the netflix one.

Great Job, thank you for your work.

Here is your badge:

https://badgr.com/public/assertions/vKitnNAsTP2mH8iwryQuxA?identity__email=sinitp2015@gmail.com

**Comment by sini-kannan** [comment]
Thank you so much to this opportunity!!!
