### ISSUE TITLE
[HW] Lucas Herrera

### ISSUE THREAD

**Issue by youngmustafa** [datastaxdevs/workshop-social-media-tiktok#64]
**Name:** Lucas Herrera
**Email:** lucas.herrera@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/lucasaherrera/

Screenshots attached:
[TikTok HW.pdf](https://github.com/datastaxdevs/workshop-astra-tik-tok/files/6634215/TikTok.HW.pdf)

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/MmYzK1hWRauldc5BEELYXA?identity__email=lucas.herrera@datastax.com
