### ISSUE TITLE
[HW] George Cross IV

### ISSUE THREAD

**Issue by GeorgeCrossIV** [datastaxdevs/workshop-social-media-tiktok#65]
**Name:** George Cross
**Email:** George.Cross@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/dr-george-cross-iv/

Attach the homework step I screenshots below:
-----------------------------------------

![tik-tok-configure-netifly](https://user-images.githubusercontent.com/12241449/121674343-efeee400-ca7f-11eb-9746-452cba07fe77.png)
![tik-tok-create-database](https://user-images.githubusercontent.com/12241449/121674344-efeee400-ca7f-11eb-81c8-f1797a9e16ce.png)
![tik-tok-running-app](https://user-images.githubusercontent.com/12241449/121674347-efeee400-ca7f-11eb-9a52-1b831eff3f17.png)
![tik-tok-clone-github](https://user-images.githubusercontent.com/12241449/121674349-f0877a80-ca7f-11eb-8fc8-b353e2d13cf0.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by clun** [comment]
Great Job, thank you for your work. 

Here is your badge:
https://badgr.com/public/assertions/1thxZX7XQNK4OIO7OaRMDw?identity__email=george.cross@datastax.com
