### ISSUE TITLE
[HW - Tiktok Clone Workshop] <Saptarshi Banerjee>

### ISSUE THREAD

**Issue by rishihub86** [datastaxdevs/workshop-social-media-tiktok#66]
Name: Saptarshi Banerjee
Email Id: saptarshi.banerjee86@gmail.com
App URL: https://tiktok-workshop-rishi.netlify.app

1)	Created the tiktok workshop Cassandra db in astra
 
![image](https://user-images.githubusercontent.com/26037424/121787066-a3bbb500-cbe1-11eb-8d63-cd5c9266a7a8.png)
	
2)	Cloned the app into my github repo
 
![image](https://user-images.githubusercontent.com/26037424/121787074-ac13f000-cbe1-11eb-8534-9ce9279c5906.png)

3)	Linked the app to netlify and created the site workspace
 
![image](https://user-images.githubusercontent.com/26037424/121787081-b8984880-cbe1-11eb-9bf9-7108829f83a6.png)
	
4)	Build the app in gitpod and started it dev server
 
![image](https://user-images.githubusercontent.com/26037424/121787087-c221b080-cbe1-11eb-886f-8609c93cb322.png)

5)	Configured the app with Astra db and build it production
 
![image](https://user-images.githubusercontent.com/26037424/121787097-ccdc4580-cbe1-11eb-94f6-aa119d78c178.png)

6)	Deployed the app into prod using netlify
 
![image](https://user-images.githubusercontent.com/26037424/121787103-d665ad80-cbe1-11eb-9418-89ef98de49e1.png)

7)	Tiktok clone successfully deployed in netlify
 
![image](https://user-images.githubusercontent.com/26037424/121787112-e41b3300-cbe1-11eb-9299-19a883985c68.png)

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/rxIqW0t4Qh-s30Kjexhk4Q?identity__email=saptarshi.banerjee86@gmail.com

I am pretty sure I also look at homework for the Netflix workshop coming for you. Thank you for being with us for multiple weeks, appreciate the quality work.

**Comment by rishihub86** [comment]
Thanks Cedrick, I am looking forward for more sessions like this. This actually helping me to learn new concepts.. Great efforts from datastax team.
