### ISSUE TITLE
[HW] Adam Fortuno

### ISSUE THREAD

**Issue by ghost** [datastaxdevs/workshop-social-media-tiktok#67]
**Name:** Adam Fortuno
**Email:** adam.fortuno@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/adamfortuno/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/85810034/121795452-0d868f80-cbdf-11eb-9a7f-b64ad94faa5f.png)

![image](https://user-images.githubusercontent.com/85810034/121795554-ee3c3200-cbdf-11eb-9209-d73608f2030c.png)
 
![image](https://user-images.githubusercontent.com/85810034/121795878-c1d5e500-cbe2-11eb-81d5-344697bce064.png)

Attach the homework step II screenshots below:
-----------------------------------------

List collections in namespace...

![image](https://user-images.githubusercontent.com/85810034/121795633-876b4880-cbe0-11eb-983c-9f161dd38de7.png)

Search documents in a collection...

![image](https://user-images.githubusercontent.com/85810034/121795772-dd8cbb80-cbe1-11eb-9dec-5b406ce305cc.png)

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/X02SK21cTW-SBiM5ohX2dw?identity__email=adam.fortuno@datastax.com
