### ISSUE TITLE
[HW] Steven Matison

### ISSUE THREAD

**Issue by ds-steven-matison** [datastaxdevs/workshop-social-media-tiktok#68]
**Name:** Steven Matison
**Email:** steven.matison@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/steven-matison/

Attach the homework step I screenshots below:
-----------------------------------------

The tiktok katacode scenario did not exist so could not complete this.  
I also could not get GitPod IDE (Chome) to install so I did not finish in  netlify context.
I had previously completed this during the first live run of tiktok clone w/ Ania.

Attach the homework step II screenshots below:
-----------------------------------------

I completed a manual install:

<img width="1383" alt="Screen Shot 2021-06-14 at 12 15 18 PM" src="https://user-images.githubusercontent.com/70520951/121925201-abc34400-cd0a-11eb-8cb0-f4b9211a0af1.png">

and here is my working application:

<img width="1781" alt="Screen Shot 2021-06-14 at 12 14 45 PM" src="https://user-images.githubusercontent.com/70520951/121925223-b1b92500-cd0a-11eb-87fb-18bb5ff57f52.png">

My Repos:

https://github.com/ds-steven-matison/workshop-astra-tik-tok

https://github.com/ds-steven-matison/astra-tik-tok

**Comment by clun** [comment]
Great Job, thank you for your work.

Here is your badge:
https://badgr.com/public/assertions/X0O_rO6qT0Ow-KN189UBYw?identity__email=steven.matison@datastax.com
