### ISSUE TITLE
[HW] Omer Saeed

### ISSUE THREAD

**Issue by osaeed-ds** [datastaxdevs/workshop-social-media-tiktok#69]
**Name:** Omer Saeed
**Email:** omer.saeed@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/omermsaeed/

Attach the homework step I screenshots below:
-----------------------------------------

![e2s1-1](https://user-images.githubusercontent.com/64428512/122309116-8da04400-cec2-11eb-92bf-a033f5bd4767.png)
![e2s1-2](https://user-images.githubusercontent.com/64428512/122309120-8ed17100-cec2-11eb-8084-5e798a444607.png)
![e2s1-3](https://user-images.githubusercontent.com/64428512/122309121-8f6a0780-cec2-11eb-9392-8be55b22a287.png)
![e2s1-4](https://user-images.githubusercontent.com/64428512/122309127-90029e00-cec2-11eb-8e6e-719072db6f60.png)
![e2s1-5](https://user-images.githubusercontent.com/64428512/122309129-909b3480-cec2-11eb-8abd-174dcac56db5.png)
![e2s1-6](https://user-images.githubusercontent.com/64428512/122309132-9133cb00-cec2-11eb-81a3-12b9a9f27140.png)
![e2s1-7](https://user-images.githubusercontent.com/64428512/122309133-91cc6180-cec2-11eb-84bb-d8627ad5402a.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![e2s2-1](https://user-images.githubusercontent.com/64428512/122309154-9d1f8d00-cec2-11eb-8172-c8420a145c54.png)
![e2s2-2](https://user-images.githubusercontent.com/64428512/122309157-9db82380-cec2-11eb-83cc-81369e90f736.png)

**Comment by clun** [comment]
Good Job mate, Thank you!

Here is the badge
https://api.badgr.io/public/assertions/fiQkh92jRSCb_cIpkMwZMg?identity__email=omer.saeed%40datastax.com
