### ISSUE TITLE
[HW] Geni Gomez

### ISSUE THREAD

**Issue by Cienfueguero** [datastaxdevs/workshop-social-media-tiktok#71]
**Name:** Geni Gomez
**Email:** geni.gomez@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/geni-gomez/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/70808007/122471295-17b4df00-cf8d-11eb-88cf-c1e46aee87dc.png)
![image](https://user-images.githubusercontent.com/70808007/122471392-3d41e880-cf8d-11eb-8179-32718dd68666.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/70808007/122471467-5480d600-cf8d-11eb-923d-957e8893d73c.png)
![image](https://user-images.githubusercontent.com/70808007/122471514-5ea2d480-cf8d-11eb-8867-ebce63ba8297.png)

**Comment by clun** [comment]
This is perfect! Thank you 

Here is the badge
https://api.badgr.io/public/assertions/us9yCzJMTsimeJKmzJV25g?identity__email=geni.gomez%40datastax.com
