### ISSUE TITLE
[HW] Karsten Stoehr

### ISSUE THREAD

**Issue by dskarsten** [datastaxdevs/workshop-social-media-tiktok#72]
**Name:** Karsten Stoehr
**Email:** karsten.stoehr@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/karsten-stoehr-7a2397/

Attach the homework step I screenshots below:
-----------------------------------------
<img width="1670" alt="Bildschirmfoto 2021-06-18 um 15 46 36" src="https://user-images.githubusercontent.com/46535108/122571486-121ece00-d04d-11eb-933b-bd9beab57fbe.png">

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------

<img width="1868" alt="Bildschirmfoto 2021-06-18 um 15 47 27" src="https://user-images.githubusercontent.com/46535108/122571524-19de7280-d04d-11eb-926d-525cbc91fecb.png">

<SCREENSHOTS>

**Comment by clun** [comment]
Danke Schön.

https://api.badgr.io/public/assertions/hAF-eZHKSY2ykDRCpqwj-w?identity__email=karsten.stoehr%40datastax.com
