### ISSUE TITLE
[HW] David LECONTE

### ISSUE THREAD

**Issue by davidleconte** [datastaxdevs/workshop-social-media-tiktok#73]
**Name:** David LECONTE
**Email:** david.leconte@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/davidleconte/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
<img width="1911" alt="Screen Shot 2021-06-20 at 10 31 09" src="https://user-images.githubusercontent.com/45590398/122668294-a5741280-d1b7-11eb-8697-965bd88f90b9.png">

  
<img width="1905" alt="Screen Shot 2021-06-20 at 10 31 32" src="https://user-images.githubusercontent.com/45590398/122668308-b755b580-d1b7-11eb-8aaf-dd36870ad221.png">
<img width="1916" alt="Screen Shot 2021-06-20 at 10 31 40" src="https://user-images.githubusercontent.com/45590398/122668314-bae93c80-d1b7-11eb-8b86-13c5af203ca6.png">
<img width="940" alt="Screen Shot 2021-06-20 at 10 35 30" src="https://user-images.githubusercontent.com/45590398/122668322-bfadf080-d1b7-11eb-9032-a98cd028a7fc.png">
<img width="1874" alt="Screen Shot 2021-06-20 at 10 45 54" src="https://user-images.githubusercontent.com/45590398/122668329-c3417780-d1b7-11eb-85af-52351f76ae8e.png">
<img width="1875" alt="Screen Shot 2021-06-20 at 10 49 07" src="https://user-images.githubusercontent.com/45590398/122668344-d5231a80-d1b7-11eb-8969-3ae828c3fb56.png">
-- images removed by team --
<img width="1876" alt="Screen Shot 2021-06-20 at 10 52 38" src="https://user-images.githubusercontent.com/45590398/122668354-e835ea80-d1b7-11eb-889b-1b812f1cd3f6.png">
<img width="1872" alt="Screen Shot 2021-06-20 at 10 53 09" src="https://user-images.githubusercontent.com/45590398/122668355-eb30db00-d1b7-11eb-8ffe-2bb102c64da9.png">
-- images removed by team --

Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good David, nice job.

BTW, I noticed some of your images contained your Astra key. I have removed these, but please go and delete your key from the Astra UI.

**Comment by SonicDMG** [comment]
Here's your badge -> https://api.badgr.io/public/assertions/hrLP4ba-R5mVI_cKG2IEGg?identity__email=david.leconte%40datastax.com
