### ISSUE TITLE
[HW] Michel de Ru

### ISSUE THREAD

**Issue by michelderu** [datastaxdevs/workshop-social-media-tiktok#74]
**Name:** Michel de Ru
**Email:** michel.deru@datastax.com
**Linkedin Profile:** https://www.linkedin.com/in/mderu/

Attach the homework step I screenshots below:
-----------------------------------------

<img width="1066" alt="Screenshot 2021-06-21 at 16 26 14" src="https://user-images.githubusercontent.com/14891355/122778822-9a9ba980-d2ad-11eb-9e32-db2652c3f53c.png">
<img width="1699" alt="Screenshot 2021-06-21 at 16 25 48" src="https://user-images.githubusercontent.com/14891355/122778829-9c656d00-d2ad-11eb-96c5-3cc2fcbe0e98.png">

  
Attach the homework step II screenshots below:
-----------------------------------------

-- image removed by team --

**Comment by SonicDMG** [comment]
Hi there Michel, thanks for your submission. It looks like you got the app running locally, but I don't see a screen from your netlify deployment to production. Please include that for credit.

Also, one of your images included your Astra token so I removed it. Please delete your token and generate a new one so there are no potential security threats.

**Comment by michelderu** [comment]
Hi David,

Thanks, here's the app running on netlify. Good point about the token. I
deleted it.

[image: Screenshot 2021-06-22 at 12.37.58.png]
Cheers, Michel.


Op ma 21 jun. 2021 om 19:56 schreef David Jones-Gilardi <
***@***.***>:

**Comment by SonicDMG** [comment]
Thank you very much for following up regarding your token. I see you pasted a screenshot, but for some reason it is not embedded in the issue.

**Comment by michelderu** [comment]
Sorry, here it is:

<img width="2560" alt="Screenshot 2021-06-22 at 12 37 58" src="https://user-images.githubusercontent.com/14891355/122936170-3b9f6880-d371-11eb-965a-a091aa7f1831.png">

**Comment by SonicDMG** [comment]
No worries at all. I see it now, nice job. Here you go -> https://api.badgr.io/public/assertions/-jP0_OjbQZWqdtlLT_rlIA?identity__email=michel.deru%40datastax.com
