### ISSUE TITLE
[HW] <AMRIT KALSI>

### ISSUE THREAD

**Issue by Brainmantis07** [datastaxdevs/workshop-social-media-tiktok#75]
**Name:** AMRIT KALSI
**Email:** amritkalsi7@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/amrit-kalsi-399a541a4/

Attach the homework step I screenshots below:
-----------------------------------------
![Capture 1](https://user-images.githubusercontent.com/64483302/122916136-2f6bd900-d37a-11eb-8304-9082fd28d42c.PNG)

<SCREENSHOTS>
  
Attach the homework step II screenshots below:
-----------------------------------------
-- images removed by team --
![Capture 4](https://user-images.githubusercontent.com/64483302/122916233-4ca0a780-d37a-11eb-97fc-63e120f581d7.PNG)
![Capture 5](https://user-images.githubusercontent.com/64483302/122916236-4d393e00-d37a-11eb-9280-acf4a1b0ce8a.PNG)
![Capture 6](https://user-images.githubusercontent.com/64483302/122916239-4dd1d480-d37a-11eb-8686-c47f7351a116.PNG)
![Capture](https://user-images.githubusercontent.com/64483302/122916242-4dd1d480-d37a-11eb-9477-c83df077c7c8.PNG)

<SCREENSHOTS>

**Comment by SonicDMG** [comment]
Looks good Amrit, thank you. Here's your badge -> https://api.badgr.io/public/assertions/q8HpismyRHqgvSVpS8r3pw?identity__email=amritkalsi7%40gmail.com
