### ISSUE TITLE
[HW] Rakesh Pavuluri

### ISSUE THREAD

**Issue by PavuluriRakesh** [datastaxdevs/workshop-social-media-tiktok#76]
**Name:** Rakesh Pavuluri
**Email:** mr.rakeshpavuluri@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rakeshpavuluri/

Attach the homework step I screenshots below:
-----------------------------------------

![Screen Shot 2021-06-25 at 2 33 01 PM](https://user-images.githubusercontent.com/86320877/123488435-d04dd480-d5c4-11eb-96df-9f0ec9228556.png)
![Screen Shot 2021-06-25 at 2 35 22 PM](https://user-images.githubusercontent.com/86320877/123488437-d2179800-d5c4-11eb-8af9-2755ba962bcb.png)
![Screen Shot 2021-06-25 at 2 39 24 PM](https://user-images.githubusercontent.com/86320877/123488442-d479f200-d5c4-11eb-8d89-84beccdac518.png)
![Screen Shot 2021-06-25 at 2 40 28 PM](https://user-images.githubusercontent.com/86320877/123488447-d5128880-d5c4-11eb-9804-ff04d61fee29.png)
![Screen Shot 2021-06-25 at 2 42 21 PM](https://user-images.githubusercontent.com/86320877/123488449-d5ab1f00-d5c4-11eb-868d-058d51cf6709.png)
![Screen Shot 2021-06-25 at 2 42 38 PM](https://user-images.githubusercontent.com/86320877/123488450-d643b580-d5c4-11eb-826a-ec02876c35e3.png)
![Screen Shot 2021-06-25 at 2 52 13 PM](https://user-images.githubusercontent.com/86320877/123488529-f5dade00-d5c4-11eb-86b4-34533873f133.png)
![Screen Shot 2021-06-25 at 2 35 22 PM](https://user-images.githubusercontent.com/86320877/123488535-f8d5ce80-d5c4-11eb-84df-412920e093e5.png)

**Comment by clun** [comment]
All good !

**Comment by HadesArchitect** [comment]
Hey **Rakesh Pavuluri**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qBcccRsMQcKX41Sxspy-Og

**Comment by PavuluriRakesh** [comment]
https://badgr.com/public/assertions/qBcccRsMQcKX41Sxspy-Og?identity__email=mr.rakeshpavuluri@gmail.com
