### ISSUE TITLE
[HW] Pranjul Yaduvanshi

### ISSUE THREAD

**Issue by iampranjul** [datastaxdevs/workshop-social-media-tiktok#78]
**Name:** Pranjul Yaduvanshi
**Email:** py2000boy@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/pranjulyaduvanshi/

https://laughing-lewin-8013d1.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------
![image](https://user-images.githubusercontent.com/56435620/125652179-8fc56582-437a-4788-9bd4-d4809bb3dfd4.png)
![image](https://user-images.githubusercontent.com/56435620/125652363-6a5cd3c9-c580-4f02-92a3-9659e55f8758.png)

**Comment by iampranjul** [comment]
![image](https://user-images.githubusercontent.com/56435620/125653025-0a3fbea5-ed2f-4d7c-a83c-c641297f542d.png)

**Comment by iampranjul** [comment]
Added Custom Post

![image](https://user-images.githubusercontent.com/56435620/125654363-87bc3d7f-7770-4293-86a7-41b290735a61.png)

**Comment by HadesArchitect** [comment]
Hey **Pranjul Yaduvanshi**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/S29VpH2nTLuj8KJ_9mgT3Q
