### ISSUE TITLE
[TIKTOK CLONE] <SMANIKA>

### ISSUE THREAD

**Issue by Smanika** [datastaxdevs/workshop-social-media-tiktok#79]
**Name:**    SMANIKA
**Email:** smanika2222@gmail.com
**Linkedin Profile:** <https://www.linkedin.com/in/smanika-6806441a6/>

!!!! HOMEWORK DONE !!!!

![Screenshot (167)](https://user-images.githubusercontent.com/67970197/125655633-44d865ad-fc5b-4e6c-92f0-566245ef5963.png)
![Screenshot (168)](https://user-images.githubusercontent.com/67970197/125655657-ebd3eb09-0337-48c9-84da-3f57e25fe83a.png)
![Screenshot (169)](https://user-images.githubusercontent.com/67970197/125655767-55533053-2c0b-4fcd-99b4-e949fbf56b6c.png)
![Screenshot (170)](https://user-images.githubusercontent.com/67970197/125655814-8f3b42ff-ab94-43a5-99ff-373b640b6834.png)
![Screenshot (173)](https://user-images.githubusercontent.com/67970197/125655829-42e1474c-f099-4b76-8fb3-d8cc4f55441c.png)
![Screenshot (172)_2](https://user-images.githubusercontent.com/67970197/125656179-56c8946d-9408-47ac-baeb-6152ce261ad4.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (171)](https://user-images.githubusercontent.com/67970197/125656294-e7cae177-48dc-4c08-849d-3817e21728f1.png)

**Comment by SonicDMG** [comment]
Hi Smanika, looks good. I can't tell though if your tiktok app is deployed up on Netlify or in your local environ since the URL is cut off. Could you either provide an updated screen or maybe just your netlify.app link?

**Comment by Smanika** [comment]
yes sure I am attaching the screenshot for that

![Screenshot (174)](https://user-images.githubusercontent.com/67970197/125727374-4e0f8961-dbce-4f10-9c89-b8e1b1b226b6.png)

**Comment by Smanika** [comment]
Netlify link:

https://silly-leakey-0c6284.netlify.app/#/

**Comment by SonicDMG** [comment]
Great, thank you. Looks good.

**Comment by HadesArchitect** [comment]
Hey **SMANIKA**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/qpXaSO39RYaBz04RdtfCqw
