### ISSUE TITLE
[HW] <Tom>

### ISSUE THREAD

**Issue by Dev-Sniper** [datastaxdevs/workshop-social-media-tiktok#80]
**Name:** Tom
**Email:** devsnipermc@gmail.com

Attach the homework step I screenshots below:
-----------------------------------------

SCREENSHOTS
![Screenshot_3](https://user-images.githubusercontent.com/37005521/125663169-aef8f7f8-f04f-4263-add1-a43feb1a64c2.png)
![Screenshot_4](https://user-images.githubusercontent.com/37005521/125663174-5555a856-9a39-45a4-8f3d-8aff97ff320f.png)
![Screenshot_5](https://user-images.githubusercontent.com/37005521/125663730-a6f4205e-ff41-4ad6-b841-38944ed07e5f.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

SCREENSHOTS
![Screenshot_1](https://user-images.githubusercontent.com/37005521/125663237-c54026e2-d592-40f7-9345-dbf1eef98a90.png)
![Screenshot_2](https://user-images.githubusercontent.com/37005521/125663242-95db1c82-c037-45ce-80ba-c45cff689131.png)

**Comment by HadesArchitect** [comment]
Hey **Tom**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/mwM5Ite5T_23iLOPUL6Veg
