### ISSUE TITLE
[HW] Arjun S

### ISSUE THREAD

**Issue by arjunindia** [datastaxdevs/workshop-social-media-tiktok#81]
**Name:** Arjun S
**Email:** arjun8107@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/arjun-s-dev/

The Site : https://tiktokcloned.netlify.app/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![Screenshot 2021-07-14 212310](https://user-images.githubusercontent.com/37960163/125654137-626713f5-e6c1-4b91-a3da-e13479e089f2.png)
![Screenshot 2021-07-14 212643](https://user-images.githubusercontent.com/37960163/125654168-783531e2-8c98-45ee-90bf-ce1149297b96.png)
![Screenshot 2021-07-14 212622](https://user-images.githubusercontent.com/37960163/125654177-9414bc8d-bbf6-4a71-9983-5ae99d88d865.png)
![Screenshot 2021-07-14 215707](https://user-images.githubusercontent.com/37960163/125658850-d9eb79ad-bf5c-49cd-8cdf-726ef9c2e24c.png)
![Screenshot 2021-07-14 220224](https://user-images.githubusercontent.com/37960163/125658863-f844bf2c-5fc1-4572-b1e9-8b0a2be634cf.png)

**Comment by SonicDMG** [comment]
Nicely done Arjun

**Comment by HadesArchitect** [comment]
Hey **Arjun S**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/32K1qOhOTO-X0DV31FBxMw
