### ISSUE TITLE
[HW] Siraj Din

### ISSUE THREAD

**Issue by Sirdmu** [datastaxdevs/workshop-social-media-tiktok#82]
**Name:** Siraj-din Umeya
**Email:** din.siraj7@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/siraj-din-umeya/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/34243798/125662135-4643fd2c-31b6-400c-a301-d0870ea36f6f.png)
  
![image](https://user-images.githubusercontent.com/34243798/125662256-e21e9c79-27f3-4cc2-b97a-be9729504bee.png)

![image](https://user-images.githubusercontent.com/34243798/125662369-edb48cd1-06d7-4489-802c-4d58e7de3c67.png)

**Comment by HadesArchitect** [comment]
Hey **Siraj**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/x00zNmr3QtCBP0Yrj0TXrg
