### ISSUE TITLE
[HW] Manish Kumar Tiwari

### ISSUE THREAD

**Issue by tiwarikmanish** [datastaxdevs/workshop-social-media-tiktok#84]
**Name:** Manish Kumar Tiwari
**Email:** manish.tiwari.270784@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/tiwarikmanish/

Attach the homework step I screenshots below:
-----------------------------------------

![1_CREATE_DB](https://user-images.githubusercontent.com/42186238/125662801-fe94050f-c7bb-4f49-8a84-e57d50676258.jpg)
![2_Deplo_NETLIFY](https://user-images.githubusercontent.com/42186238/125662805-4b57fe1c-0e1e-4147-ab52-123ebfb1f21d.jpg)
![3_GITHUB_REPO](https://user-images.githubusercontent.com/42186238/125662808-70bbef3f-dbbc-4a0b-bec7-4210c5f8aec5.jpg)
![8_LAUNCH_APP](https://user-images.githubusercontent.com/42186238/125662813-5b57f69e-4657-4d02-bfb2-61ae7eced361.jpg)
![10_netlify_prod_deployment](https://user-images.githubusercontent.com/42186238/125662816-ed234e47-f6ac-4987-99d5-89932bb09f4b.jpg)
![PART1_FINAL_NETLIFY_LIVE_APP](https://user-images.githubusercontent.com/42186238/125662817-90048a92-9bee-4a6d-bc66-fa5c82c3a8a8.jpg)

  
Attach the homework step II screenshots below:
-----------------------------------------

![PART2_FIND_DOCUMENTS](https://user-images.githubusercontent.com/42186238/125662840-0fa4afc8-a166-4d47-bc00-b86a7d9b99c1.jpg)
![PART2_STEP1_GET_COLLECTION](https://user-images.githubusercontent.com/42186238/125662843-a7b57ee5-cd3f-4691-9559-c624d7fc8a1c.jpg)

**Comment by HadesArchitect** [comment]
Hey **Manish Kumar Tiwari**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JgX5mAzrT5mvDnXVuG0ZbA
