### ISSUE TITLE
Tiktok Clone Cleon Dsouza

### ISSUE THREAD

**Issue by CleonDsouza** [datastaxdevs/workshop-social-media-tiktok#85]
**Name:** Cleon Dsouza
**Email:**  cleondsouza07@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/cleon-dsouza-a77358217/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>

  
Attach the homework step II screenshots below:
![image](https://user-images.githubusercontent.com/87087817/125663527-e16f01cb-3717-48f8-b50b-872e5a8f2998.png)

![image](https://user-images.githubusercontent.com/87087817/125663369-10a57403-f849-4892-8526-937a63930842.png)

![image](https://user-images.githubusercontent.com/87087817/125662982-f8252ac3-3d16-4a1e-b9fa-9719a191cf84.png)

-----------------------------------------

<SCREENSHOTS>

**Comment by HadesArchitect** [comment]
Hey **Cleon Dsouza**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/sUowREBRR8WrMw6yJ8QtpQ
