### ISSUE TITLE
[HW] Astra DB TikTok Clone Workshop<NAME>Eashaa Shiv Shankar Singh Kushwah

### ISSUE THREAD

**Issue by EashaaKushwah** [datastaxdevs/workshop-social-media-tiktok#86]
**Name:** Eashaa Shiv Shankar Singh Kushwah
**Email:** ekushwah3@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/eashaa-kushwah-404492216/

Attach the homework step I screenshots below:
-----------------------------------------
-- image removed by team --
![image](https://user-images.githubusercontent.com/87125938/125663462-057a8bcd-d4d1-439a-bcc8-afcf2a488510.png)
![image](https://user-images.githubusercontent.com/87125938/125663487-c361fa1b-56d2-455d-aa8f-00878a85669c.png)
![image](https://user-images.githubusercontent.com/87125938/125663507-89895681-f8e4-4af5-a992-c542f6d85ff8.png)
  
Attach the homework step II screenshots below:
-----------------------------------------
-- image removed by team --
![image](https://user-images.githubusercontent.com/87125938/125663553-d5064a9a-79cc-4ab9-b0f7-7b443098bdc9.png)

**Comment by HadesArchitect** [comment]
Hey **Eashaa Shiv Shankar Singh Kushwah**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/4VSa8B2vSZyxfxFeJllnPw

**Comment by SonicDMG** [comment]
Also, I removed a set of images that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.
