### ISSUE TITLE
[HW] Rahul Panday

### ISSUE THREAD

**Issue by rpanday** [datastaxdevs/workshop-social-media-tiktok#87]
**Name:** Rahul Panday
**Email:** rpanshad@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/rahulpanday/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/4745947/125662320-be6b6320-7668-4a89-978b-a255dae3c843.png)

![image](https://user-images.githubusercontent.com/4745947/125662409-e36f7ccf-800e-4e36-8afa-745602833d9b.png)

![image](https://user-images.githubusercontent.com/4745947/125662489-0026b881-d7ae-4a3a-b7f1-014122bb6e06.png)

![image](https://user-images.githubusercontent.com/4745947/125662612-45252315-b9a2-4ced-9f52-1c55d30dd2d9.png)

![image](https://user-images.githubusercontent.com/4745947/125662766-16cbb756-c87e-4d59-840c-41dfa8a4ee7b.png)

![image](https://user-images.githubusercontent.com/4745947/125662902-e91b143f-8174-423f-b9ba-8f4b22cdb921.png)

![image](https://user-images.githubusercontent.com/4745947/125663668-454df73c-c1a0-4132-b945-811600e00192.png)

![image](https://user-images.githubusercontent.com/4745947/125663526-5bfaaf97-ed71-4285-9146-8e7288a5cd17.png)
 
Attach the homework step II screenshots below:
-----------------------------------------

<SCREENSHOTS> - Did not attempt.

**Comment by HadesArchitect** [comment]
Hey **Rahul Panday**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/rRD7XkNMRU6oJ4Fh9A8v-A
