### ISSUE TITLE
[HW] Tiktok app Angelika Zygmunt

### ISSUE THREAD

**Issue by faraday-crypto** [datastaxdevs/workshop-social-media-tiktok#88]
**Name:** Angelika Zygmunt
**Email:** zygmuntange@gmail.com
**Linkedin Profile:** www.linkedin.com/in/angelika-zygmunt-1029671b6

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
-- images removed by team --
![imagen](https://user-images.githubusercontent.com/84669673/125663382-3f0b66b9-a96f-4a0c-b1ac-c3d7573759bb.png)

**Comment by HadesArchitect** [comment]
Hey **Angelika Zygmunt**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/iXMV-MtNQ9a3eHLF_Gu--A
