### ISSUE TITLE
[HW] Michael Quiroga

### ISSUE THREAD

**Issue by m-quirogadev** [datastaxdevs/workshop-social-media-tiktok#90]
**Name:** Michael Quiroga
**Email:** Michael.E.Quiroga@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/michael-e-quiroga-a98634183/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot_10](https://user-images.githubusercontent.com/70244594/125661815-9a481057-320b-4567-a569-27dfcc66367a.png)
![Screenshot_11](https://user-images.githubusercontent.com/70244594/125661817-50426081-6c5d-4e96-ba2a-c295e85444b6.png)
![Screenshot_12](https://user-images.githubusercontent.com/70244594/125661818-4be9d063-003f-4d98-9e59-203f7b14d07c.png)
![Screenshot_13](https://user-images.githubusercontent.com/70244594/125661819-3ce07dc2-f53b-4d52-a63d-cb0487d7f307.png)
![Screenshot_14](https://user-images.githubusercontent.com/70244594/125661820-f73f99fc-065b-4c94-b153-b03f3a946c5a.png)
![Screenshot_15](https://user-images.githubusercontent.com/70244594/125661824-7e7b122a-9faf-437f-b6de-f6afe221c8c0.png)
![Screenshot_17](https://user-images.githubusercontent.com/70244594/125661826-290c9a6c-0aa8-44e4-9b44-0ec5e8a64b26.png)
![Screenshot_18](https://user-images.githubusercontent.com/70244594/125661828-b1c40c9b-25b1-40dc-867d-5f6470cf86be.png)
![Screenshot_19](https://user-images.githubusercontent.com/70244594/125661829-698dad8c-953e-4059-a468-2c238a3600e5.png)
![Screenshot_20](https://user-images.githubusercontent.com/70244594/125661833-5294ec95-4e89-4f0b-b2ac-99c42c42d071.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

**Comment by HadesArchitect** [comment]
Hey **Michael Quiroga**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/WWQqdOl9TGmKfjYw5BEDvg
