### ISSUE TITLE
[HW] Nesrine Sghaier

### ISSUE THREAD

**Issue by nesrinesghaier** [datastaxdevs/workshop-social-media-tiktok#91]
**Name:** Nesrine Sghaier
**Email:** nesrinesghaier10@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/sghaiernesrine/

Attach the homework step I screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/32217702/125663985-5188579e-1270-4df6-ac3a-5020f7b4b302.png)

![image](https://user-images.githubusercontent.com/32217702/125664214-e4328840-7f4f-4844-9cb9-514da6615e81.png)

![image](https://user-images.githubusercontent.com/32217702/125664498-d5b9a50d-67c3-4468-8e70-f0cda626cd6c.png)
  
Attach the homework step II screenshots below:
-----------------------------------------

![image](https://user-images.githubusercontent.com/32217702/125664869-723d0b8c-9d91-4bc9-87bc-46ac0aa6ec43.png)

![image](https://user-images.githubusercontent.com/32217702/125665480-6b575b02-5866-4cd7-84b1-6ac52220db15.png)

**Comment by HadesArchitect** [comment]
Hey **Nesrine Sghaier**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/f3eUhi4URESx3TZyF5Z2zQ
