### ISSUE TITLE
TikTokClone - Niranjana Rao Prabakararao

### ISSUE THREAD

**Issue by NiranjanaRao-P** [datastaxdevs/workshop-social-media-tiktok#92]
**Name:** Niranjana Rao Prabakararao
**Email:** niran21@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/niranjana-rao-prabakararao/

Attach the homework step I screenshots below:
-----------------------------------------

  
Attach the homework step II screenshots below:
-----------------------------------------

![get_tiktokclone](https://user-images.githubusercontent.com/75638383/125666050-8f25ea08-2a66-44e6-8819-626a143052f8.png)
![searchDocs_tiktokClone](https://user-images.githubusercontent.com/75638383/125666056-5c32d9e3-fbb4-46e8-ab30-618fc4fcd004.png)
![Netlify_Sites_Functions_TiktokClone](https://user-images.githubusercontent.com/75638383/125666059-83caf404-64ac-4c5a-9d26-231b182c870b.png)
![Tiktok_Clone](https://user-images.githubusercontent.com/75638383/125666061-e14826fc-6d4c-4607-8991-76129156bd61.png)

**Comment by SonicDMG** [comment]
Hi there Niranjana, thank you for your submission. The todo app looks good, but I am missing the from scratch react app from step 2 of the homework.
2. Create a React app from scratch using NPX. Follow [these instructions](https://github.com/datastaxdevs/react-basics). Take a screenshot of your final working app.

Please complete that step and provide a screenshot of your completed work.

**Comment by SonicDMG** [comment]
Hi Niranjana, were you able to get videos to display in the tiktok app? Please provide an image displaying your app running with videos.

**Comment by NiranjanaRao-P** [comment]
Hi David,

Yes, I was able to deploy successfully. I do not have the screenshot though.

Thanks and Regards,
Niranjana Rao Prabakararao
+1-510-925-3179
***@***.***

**Comment by SonicDMG** [comment]
Hi there. I was able to double check your deployed Netlify app and I do see it is deployed, but both the local app and the deployed app are displaying just the blank TikTok page which indicates to me something is off on the database configuration end. I suggest maybe trying again from step 7 https://github.com/datastaxdevs/appdev-week2-tiktok#7-configure-and-connect-database to see if you can get the local app to run correctly and display the videos.

**Comment by NiranjanaRao-P** [comment]
Thanks David. I'll check it out.

**Comment by SonicDMG** [comment]
Did you have any luck getting the app properly configured?

**Comment by NiranjanaRao-P** [comment]
No David. I couldn't. Moreover, I had to travel. Couldn't attend last
week's webinar either. I'll try to watch it later. Thank you.

Regards
Niranjana Rao Prabakararao

**Comment by SonicDMG** [comment]
Sounds good. I'll keep this one open and we can work through it if you would like. :D

**Comment by NiranjanaRao-P** [comment]
Thank u. :)
