### ISSUE TITLE
[HW] <Ruchi Kandpal>

### ISSUE THREAD

**Issue by Ruch-code** [datastaxdevs/workshop-social-media-tiktok#93]
**Name:** Ruchi Kandpal
**Email:** Ruchi.kandpal@associates.scit.edu
LinkedIn URL:
http://linkedin.com/in/uche-journalism

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>!
![image](https://user-images.githubusercontent.com/67715131/125667017-4f4c1691-3a80-4db4-8154-2ee998aa39dd.png)
![image](https://user-images.githubusercontent.com/67715131/125667046-f60fed09-aa41-413f-b6da-c4d0ca6e08a2.png)![image](https://user-images.githubusercontent.com/67715131/125667105-34e162ee-52f0-4659-b864-fbf3da0d9d2c.png)
  
Attach the homework step II screenshots below:
-----------------------------------------
-- image removed by team --

**Comment by HadesArchitect** [comment]
Hey **Ruchi Kandpal**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/JOfGV76fSkyGffqFfUcuzA

**Comment by SonicDMG** [comment]
I removed an image that included your Astra token. Please ensure to delete your token from the Astra UI so we don't have any security holes, thank you.

**Comment by Ruch-code** [comment]
Yes. I forgot about it. Thank-you for bringing it to light.
