### ISSUE TITLE
[HW] Char Ryder

### ISSUE THREAD

**Issue by bl-kt** [datastaxdevs/workshop-social-media-tiktok#94]
**(Legal) Name:** Charlotte Ryder
**(Preferred) Name:** Char Ryder
**Email:** char.ryder@blkt.co.uk
**Linkedin Profile:** https://www.linkedin.com/in/blkt/

Here are my screenshots, I do not have all of them as I only started taking screenshots an hour through the Wednesday tutorial, due to only realising/being told then

![tiktok clone step 10](https://user-images.githubusercontent.com/56833452/125667287-1cd60839-cb9d-493c-a87b-ab7b8e8d7d51.png)
![tiktok clone step 11](https://user-images.githubusercontent.com/56833452/125667290-4a889f7d-30b2-4ce6-97c5-b103bde04b7e.png)
![tiktok clone step 12](https://user-images.githubusercontent.com/56833452/125667292-2dc4838c-6350-4a6a-ae05-5a3d1b096b11.png)
![tiktok clone step 15](https://user-images.githubusercontent.com/56833452/125667295-ca11dd7e-0ef4-4d80-85aa-082e18293740.png)

**Comment by HadesArchitect** [comment]
Hey ****, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/_dSjVGBlS5ejHJGS8AvOWg
