### ISSUE TITLE
[HW] Osama Buhamad

### ISSUE THREAD

**Issue by OsamaBuhamad** [datastaxdevs/workshop-social-media-tiktok#95]
**Name:** Osama Buhamad
**Email:** osamabuhamad@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/osama-buhamad/

Attach the homework step I screenshots below:
-----------------------------------------
Netlify Deploy:

![1_Netlify_Deploy](https://user-images.githubusercontent.com/7606429/125666897-75538683-9fcb-4122-a957-d8deaeeedd10.PNG)

Build Netlify in Gitpod:

![2_Netlify_Build](https://user-images.githubusercontent.com/7606429/125666945-4148e4fb-5cea-4358-bf6f-3279ca25cdbe.PNG)

  
Attach the homework step II screenshots below:
-----------------------------------------

Connecting to ASTRA DB:

![3_ASTRA_connection](https://user-images.githubusercontent.com/7606429/125667002-6983ca60-03c1-4685-8589-ec6e69daeb9b.PNG)

The App running:

![4_app_running](https://user-images.githubusercontent.com/7606429/125667209-7ae37680-7a45-4e23-9cf2-4288c27c9e3c.PNG)

Call to the Serverless function:

![5_Serverless](https://user-images.githubusercontent.com/7606429/125667262-610bf3fc-50ee-49fd-8494-e369be5f290d.PNG)

**Comment by HadesArchitect** [comment]
Hey **Osama Buhamad**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/mjvdSgVWRwm5c4g8eQtC4g
