### ISSUE TITLE
[HW] Nikhil Yadav

### ISSUE THREAD

**Issue by luciferrr69** [datastaxdevs/workshop-social-media-tiktok#97]
**Name: Nikhil Kumar Yadav
**Email:  yadavnikhil.ny29@gmail.com
**Linkedin Profile: https://www.linkedin.com/in/nikhil-yadav-91a79916a/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot (36)](https://user-images.githubusercontent.com/69397864/125667375-b6421dcd-86da-4894-9b97-6540bb60bf49.png)

![Screenshot (37)](https://user-images.githubusercontent.com/69397864/125667415-1f7cf7e4-727d-49a2-b2fd-d3fbadff2226.png)

  
Attach the homework step II screenshots below:
-----------------------------------------

![Screenshot (38)](https://user-images.githubusercontent.com/69397864/125667554-731c4a6a-67bf-4aff-997a-be440f78c9c9.png)

![Screenshot (39)](https://user-images.githubusercontent.com/69397864/125667576-70f9235e-c071-4e70-b887-2006b4b03138.png)

**Comment by HadesArchitect** [comment]
Hey **Nikhil Kumar Yadav**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/RXBPf0HyScyjGi_ZUB4P5A
