### ISSUE TITLE
[appdev-week2-tiktok] <Preyum Kumar>

### ISSUE THREAD

**Issue by PreyumKr** [datastaxdevs/workshop-social-media-tiktok#98]
**Name:** Preyum Kumar
**Email:** preyumkrsingh@gmail.com
**Linkedin Profile:** <Will Make it Soon :-) >

Site:- https://tiktok-preyumkr.netlify.app/#/

Attach the homework step I screenshots below:
-----------------------------------------

<SCREENSHOTS>
  
![Screenshot (1482)_LI](https://user-images.githubusercontent.com/77330179/125664244-d948dd39-b9bb-4d5c-ac04-faac63c1d2e9.jpg)

![Screenshot (1483)](https://user-images.githubusercontent.com/77330179/125667752-e1527164-6004-443f-bcf4-2e23aaaa2e05.png)

**And with this I completed the 3 events. Now how to get the golden badge :-)**

**Comment by HadesArchitect** [comment]
Hey **Preyum Kumar**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/AEJ76qiWTtKC66QTgcpWxA

**Comment by SonicDMG** [comment]
We'll issue the golden badges at the end of the 3 week series. :D

**Comment by PreyumKr** [comment]
Since I did the netflix clone before I can Skip that right :-)

**Comment by SonicDMG** [comment]
Yes, if you already have your badge you should be good.
