### ISSUE TITLE
[HW] <Ahmed Benyahia>

### ISSUE THREAD

**Issue by AhmedBenyahia** [datastaxdevs/workshop-social-media-tiktok#99]
**Name:** Ahmed Benyahia
**Email:** ahmedbenyahiass@gmail.com
**Linkedin Profile:** https://www.linkedin.com/in/ahmed-benyahia-ss/

Attach the homework step I screenshots below:
-----------------------------------------

![Screenshot from 2021-07-14 18-45-13](https://user-images.githubusercontent.com/16466499/125668581-4a61d62b-367d-4f08-ac1d-b28c52866118.png)
![Screenshot from 2021-07-14 18-47-45](https://user-images.githubusercontent.com/16466499/125668670-e5cf1465-28fa-4dc8-a95c-809e7800831f.png)
![Screenshot from 2021-07-14 18-48-29](https://user-images.githubusercontent.com/16466499/125668747-44310062-eff4-4e42-97db-c4a23d15efb9.png)

  
Attach the homework step II screenshots below:
-----------------------------------------
![Screenshot from 2021-07-14 18-48-29](https://user-images.githubusercontent.com/16466499/125669955-a56d43a2-e66d-4bfa-a288-fbf41be0b076.png)
-- image removed by team --

**Comment by HadesArchitect** [comment]
Hey **Ahmed Benyahia**, great job! Congrats! Here is your badge! https://api.badgr.io/public/assertions/KVDmLkTXSxyABVvZ66Vs1w
